### ISSUE TITLE
docker export <container> fails to export files

### ISSUE THREAD

**Issue by jbulchergist** [docker/docker#10095]
`docker export` should export a tar of all files/folders saved in a data container, right?

I have a simple data container build `FROM scratch`, with a binary executable named `/bin/echo` for starting purposes. Let's call it container '0'

Two containers connect to it to share data - one reads, the other writes. Let's call them 'A' and 'B'. A and B both share `/var/www/html` through 0, but do not access each other directly. Container B can read files generated by A, which means the data must be present in the data container.

Here is the fig file I use to start the application to demonstrate container connectivity:

```
mrtg:
  image: foo:5000/mrtg
  environment:
    TERM: xterm
  volumes:
   - /etc/localtime:/etc/localtime:ro
  volumes_from:
   - data
apache:
  image: foo:5000/apache-php
  environment:
    TERM: xterm
  ports:
   - "80:80"
  volumes:
   - /etc/localtime:/etc/localtime:ro
  volumes_from:
   - data
data:
  image: foo:5000/data-mrtg
```

After running the container, causing data to go into container 0, I have this problem:

```
$ docker export foo_data_1 > foo.tar
$ tar -tf foo.tar
./
.dockerenv
.dockerinit
bin/
bin/echo
dev/
dev/console
dev/pts/
dev/shm/
etc/
etc/hostname
etc/hosts
etc/mtab
etc/resolv.conf
proc/
sys/
var/
var/www/
var/www/html/
# I should be seeing more, something like this:
# var/www/html/index.html
# var/www/html/dirname
# var/www/html/dirname/somefile
# ...
```

I only put one file in the container - `/bin/echo` (and the folder `/var/www/html`); docker must create the rest upon starting the container. Docker export isn't exporting any of the files or folders stored in `/var/www/html`. Shouldn't it?

**Addendum**
#2116 looks like it is the same issue, but it was confirmed possible to export stopped containers. Am I misunderstanding something?
