### ISSUE TITLE
Docker reporting port in use even after container is stopped and destroyed

### ISSUE THREAD

**Issue by amalagaura** [docker/docker#10467]
Referencing: https://github.com/docker/docker/issues/6476#issuecomment-72261362

I created a container with fig with ~~2~~ 1 port~~s~~. 

```
  influxdb: 
    image: influxdb
    volumes: 
      - /space/influxdb:/data
    ports:
      - "8083:8083"
```

I then stopped it and removed the container 
 ```
fig stop influxdb
fig rm --force influxdb
```

After I made a change to the fig.yml config and tried to recreate the container
```
fig up -d --no-deps influxdb
Creating docker_influxdb_1...
```

I got the error message:
**Cannot start container 5cd8d0c944b7a09266aaa3cd8df11bd5b8befcf11030018feeb6e04497175016: Bind for 0.0.0.0:8083 failed: port is already allocated**

I realize this is done with fig and not direct docker, but is it a docker issue or fig? From the error reports it seems to be an issue with docker.
