### ISSUE TITLE
Docker 1.7 on debian 8 doesn't properly add iptables rules for linked containers

### ISSUE THREAD

**Issue by pshoukry** [docker/docker#16193]
Adding a link to a container doesn't add a rule to the docker chain in iptables on debian 8

docker-compose file
```
db:
  image: mongo
nodejs:
  image: nodejs
  volumes:
    - .:/src
  ports:
    - "3000:3000"
  working_dir: /src
  links: 
    - db
```

iptables -L -v
```
Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  !docker0 docker0  anywhere             172.17.0.4           tcp dpt:3000
```

No rule for the mongo linked mongo database ( with exposed port 27017 ) and the result is trying to connect from node container to mongo container gives a destination unreachable.

A working work around is to add a rule to accept traffic on the docker interface.
```
 iptables -A DOCKER -p tcp --dport 27017 -i docker0 -o docker0 -j ACCEPT
```
