### ISSUE TITLE
First Synchronization of 'volumes' command

### ISSUE THREAD

**Issue by lo-tp** [docker/docker#17152]
## What's The Problem
It's about the first time when docker tries to synchronize the directory within the container and the corresponding one on the host according to the `volumes` command.
Docker will always sync the host one with the one within the container.
Sometimes, that's not the behaviour we want.

In some situations, we may want docker to synchronize the host one with container one.

## The Environment I Found this Problem
1.	docker version: 1.8.2, build 0a8c2e3
1.	docker-compose version: 1.4.2
1.	OS: Ubuntu 14.04 
1.	Kernal version: 3.13.0-40-generic

## How to Reproduce This Problem
You need 2 files and one empty directory containing nothing named 'dir' within one blank directory.

1.	test.dockerfile
```yml
FROM ruby:2.2.3
RUN mkdir /tmp/dir
WORKDIR /tmp/dir
RUN touch /tmp/dir/abc
```
1.	docker-compose.yml
```yml
test:
        build: .
        dockerfile: test.dockerfile            
        container_name: tem
        command:  ls
        volumes:
                - ./dir:/tmp/dir
```
After running `docker-compose up`.
Withn 'dir', there is nothing.
But there should be a file named abc.

## The Potential Solution
Maybe we could add an extra arg to `volumes` tell docker the direction we want the synchronization to be.
