### ISSUE TITLE
Proposal: Persistent Daemon Configuration File

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#17559]
This proposal describes a new configuration file format for the docker daemon.  The objective is to provide a consistent mechanism for configuration of the daemon across different operating systems and distributions.  The file should be both human and machine friendly, supporting direct editing by users, as well as by the daemon based on API calls.  The file will be encode in [TOML](https://github.com/toml-lang/toml).

The configuration will live in a well known location of `/var/lib/docker/engine.cfg` with a sym-link from `/etc/docker/engine.cfg`

When the daemon starts, the configuration file will be loaded first.  Then any CLI flags will be processed, and where the CLI flags overlap with the configuration file, the values provided by the CLI flags will override the configuration file.  For map style settings (e.g., labels) the final value will be the union of settings from the configuration file and CLI arguments, and in the case of overlapping keys, the CLI values will override the values in the configuration file.  No mechanism will be provided to “unset” a value via the CLI flags that was set in the configuration file.

The following example illustrates a hypothetical configuration file:

```TOML
# Example docker daemon configuration
cluster-advertise="192.168.1.2:2376"
cluster-store="etcd://192.168.1.2:2379"

[cluster-store-opt]
"kv.cacertfile"="/etc/docker/ssl/ca.pem"
"kv.certfile"="/etc/docker/ssl/cert.pem"
"kv.keyfile"="/etc/docker/ssl/key.pem"

[label]
storage="ssd"
rack="42"
```
