### ISSUE TITLE
Containers become invisible to each other after 1.9.0 update

### ISSUE THREAD

**Issue by Aliance** [docker/docker#17826]
Hello, after updating to `1.9.0` I have a problem of container's visibility. Before update I used `1.8.3` and everything works fine for me.

```
$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 7
Images: 160
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 174
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.797 GiB
Name: <...>
ID: <...>
Username: <...>
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

`uname -a`: `Linux lesnykh 3.19.0-31-generic #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

How reproducible: my `docker-compose.yml`
```yaml
app:
    container_name: project-dev
    build: ./build
    links:
        - redis
        - node
redis:
    container_name: project-redis
    image: redis:3.0.5
    volumes:
        - /var/db/redis:/data
node:
    container_name: project-node
    build: ./build-node
    volumes:
        - /var/log/project/nodejs:/app/log
```

Steps to Reproduce:
1. I run `docker-compose up -d` to up all containers;
2. then run `docker exec -it project-node bash` to enter into nodejs container, which is linked to main (app) container;
3. and after it in nodejs container I run `cat /etc/hosts`.

Expected Results:
In version `1.8.3` I see all other containers:
```
root@665944c01a16:/# cat /etc/hosts
172.17.0.2	665944c01a16
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	project-node
172.17.0.2	project-node.bridge
172.17.0.3	project-redis
172.17.0.3	project-redis.bridge
172.17.0.4	project-dev
172.17.0.4	project-dev.bridge
```

Actual Results:
But in `1.9.0` I see nothing. As I understand, I have to use `--net` parameter to make `bridge`, am I write? How can I do it with `--link`?

**Comment by WeiZhang555** [comment]
I think this is a designed behavior since 1.9.0, see https://github.com/docker/docker/pull/17230.
Hope that can explain your problem.

**Comment by Aliance** [comment]
So, I need to add `--net=bridge` to all containers which I want to enable visibility?

**Comment by WeiZhang555** [comment]
I don't think add `--net=bridge` can solve this problem.
In my understanding, container `app` can see `redis` and `node`, but `node` can't see `app`, and can't see `redis` either.
I have no idea how to solve this, maybe docker's network team can give more suggestions.
ping @aboch @mavenugo

**Comment by Aliance** [comment]
> In my understanding, container app can see redis and node, but node can't see app, and can't see redis either.

Yeap, you are right.

Containers `app` and `node` have to see each other and `redis`

**Comment by cpuguy83** [comment]
The way to fix this is to _not_ use the bridge network.
This implicit discovery that was added in 1.8 was not intentional and was meant only for user created networks, not the bridge network.

In 1.9 the implicit discovery was removed from bridge and is only available in user created networks.
I believe compose has experimental support for user created networks.

**Comment by WeiZhang555** [comment]
@cpuguy83 I have one question, it seems that `--net` can't coexists with `--link` and `--link` is only valid for default `bridge` network now, so how can user link two containers in user defined network?
Or because of implicit discovery, containers in user defined network can see each other by default, so can I say they don't need to link to each other any more,  am I right?

**Comment by cpuguy83** [comment]
@WeiZhang555 That's correct, though on user defined networks it would be nice to be able to alias a container like you do with links... this is coming.

But yes, links are not part of user defined networks due to implicit discovery.

**Comment by WeiZhang555** [comment]
@cpuguy83 That's very clear, thank you. :smile:

**Comment by sanimej** [comment]
@Aliance With the user defined networks you also have to use named (--name) containers for automatic service discovery.

**Comment by Aliance** [comment]
Writing "user defined network" you mean `docker network create`?

**Comment by cpuguy83** [comment]
Yes.

**Comment by Aliance** [comment]
Okay, I see. And what driver should I use? You said "not bridge"?

**Comment by Aliance** [comment]
@sanimej 
> With the user defined networks you also have to use named (--name) containers for automatic service discovery.

Can you explain a little bit more. Now I have already used named containers (see my example) and try to ping each other by this alias, you mean this behavior or something else?

**Comment by sanimej** [comment]
@Aliance Ok, since you are already using the name discovery should work automatically for explicitly created networks..

**Comment by thaJeztah** [comment]
@Aliance I'm going to close this issue, because this is not a bug. I hope the comments/suggestions here help you resolve your issue. :+1: 

Also, feel free to continue the discussion here

**Comment by Aliance** [comment]
I had read [docker container networking](http://docs.docker.com/engine/userguide/networking/dockernetworks/) and understood many interesting facts. Bridge default network - is legacy and deprecated:
> it is better to avoid them and define your own bridge networks instead.

> I believe compose has experimental support for user created networks.
[Documentation](https://docs.docker.com/compose/compose-file/#net) says what you're right.

So I did theese steps:
* created user-defined bridge network `docker network create --driver bridge docker_internal_net`
* removed `link` and added `net` into my `docker-compose.yml`:
```yaml
app:
    container_name: project-dev
    net: docker_internal_net
    build: ./build
redis:
    container_name: project-redis
    net: docker_internal_net
    image: redis:3.0.5
    volumes:
        - /var/db/redis:/data
node:
    container_name: project-node
    net: docker_internal_net
    build: ./build-node
    volumes:
        - /var/log/project/nodejs:/app/log
```

And everything works fine! Thanx everyone involved
