### ISSUE TITLE
Permission denied loading shared libs

### ISSUE THREAD

**Issue by astopy** [docker/docker#19184]
I assume this is related to the seccomp stuff @jfrazelle mentioned on docker-dev. I'm getting the following error trying to run `zooniverse/static`:

```
/usr/bin/python: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Permission denied`
```

And this from `zooniverse/image-processing`:

```
/bin/sh: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied
/bin/sh: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied
```

The `docker-compose.yml` I'm using is as follows:

```
imgproc:
  image: zooniverse/image-processing
  environment:
    - NODE_ENV=production

static:
  image: zooniverse/static
  volumes:
    - /mnt/nginx-cache/:/nginx-cache/
    - /opt/production_configs/nginx-deny/nginx-deny.conf:/etc/nginx-deny.conf
  ports:
    - 80:80
  links:
    - imgproc:imgproc
```

`nginx-deny.conf` can just be a blank file when you test this. And here's some version info:

```
ubuntu@ip-10-170-79-43:~$ uname -a
Linux ip-10-170-79-43 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-10-170-79-43:~$ docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   374a959
 Built:        Thu Jan  7 18:15:43 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   374a959
 Built:        Thu Jan  7 18:15:43 2016
 OS/Arch:      linux/amd64
 Experimental: true
ubuntu@ip-10-170-79-43:~$ docker info
Containers: 3
Images: 32
Server Version: 1.10.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 68
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.613 GiB
Name: ip-10-170-79-43
ID: J36X:GFUU:IDST:QBZV:4KGH:MCPI:HS64:363M:WTJ5:C7JQ:7ICO:ZEEM
WARNING: No swap limit support
Experimental: true
```
