### ISSUE TITLE
Error parsing HTTP response: unexpected end of JSON input: "" push **** image fail, please check!

### ISSUE THREAD

**Issue by ghy200692162** [docker/docker#19366]
Problem
We use s3 as storage and redis as cache for docker hub,and we also use elb in front of the hub host.
First we use docker registry v1,and everything goes well.After we change registry from v1 to v2.We found that we can only push or pull images on the docker hub host,while when wen try to pull or push images on other machines ,we got the error message below

Error parsing HTTP response: unexpected end of JSON input: "" push **** image fail, please check!

Version info
Docker version: 1.8.3, build cedd534-dirty
<img width="339" alt="2016-01-15 11 43 50" src="https://cloud.githubusercontent.com/assets/1029390/12357273/ed2a60da-bbe1-11e5-91b7-91380689d127.png">

Docker info
<img width="463" alt="2016-01-15 11 45 00" src="https://cloud.githubusercontent.com/assets/1029390/12357352/55218cd6-bbe2-11e5-9a03-7a9358320b87.png">

Docker registry: registry:2

Docker registry config.ml
```
version: 0.1
log:
    fields:
        service: registry
http:
    addr: :5000
    secret: no
    headers:
        X-Content-Type-Options: [nosniff]
storage:
    cache:
        layerinfo: redis
    s3:
        accesskey: ouraccesskey
        secretkey:  secretkey
        region: us-east-1
        bucket: docker-use1
        rootdirectory: /registry
```
