### ISSUE TITLE
System error: no such file or directory

### ISSUE THREAD

**Issue by EwanValentine** [docker/docker#19394]
Description of problem:
I've span up the default Docker/Ubuntu 14.04 box on Digital Ocean. I have a project which houses a Javascript (React) ui, inside an nginx container and an API written in Golang. 

I was trying to set the project up, but every time I ran `docker-compose up`, I got the following error:

```
Recreating 051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_bandzest_core-api_1
ERROR: Cannot start container 54bf4d6f4fd89b20de697e83344fc70f988ec030aaea361f25c8ad2f61133042: [8] System error: no such file or directory
```

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 6
Images: 93
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 105
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 490 MiB
Name: bandzest.com
```

`uname -a`:
```
Linux bandzest.com 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
This is running in Ubuntu on a Digital Ocean VPS. 

How reproducible:
docker-compose.yml
```

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - certs:/etc/nginx/certs
  ports:
    - "80:80"
    - "443:443"

core-api:
  build: ./applications/core/api
  ports:
    - 8080
  links:
    - core-datastore 
    - core-cache
  environment:
    - DB_NAME=bandzest
    - VIRTUAL_HOST=core.api.bandzest.dev
  restart: always

core-ui:
  build: ./applications/core/ui
  ports:
    - 80
  environment:
    VIRTUAL_HOST: bandzest.dev

core-datastore:
  image: mongo:3.0
  command: mongod --smallfiles --quiet --logpath=/dev/null

core-cache:
  image: redis
```

Go Dockerfile
```
FROM centurylink/ca-certs
WORKDIR /app
COPY api /app/
ENTRYPOINT ["./api"]
```

Steps to Reproduce:
1. cd /applications/core/api && go build
2. cd /
3. docker-compose build
4. docker-compose up

Actual Results:
```
Recreating 051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_051010d58e_bandzest_core-api_1
ERROR: Cannot start container 54bf4d6f4fd89b20de697e83344fc70f988ec030aaea361f25c8ad2f61133042: [8] System error: no such file or directory
```

The images build and run, however my go api and js front-end don't build/run. 

Expected Results:
I should see 5 containers, including my go api and my js front-end. 

Additional info:

This codebase works perfectly on my Macbook Pro: 
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```
