### ISSUE TITLE
[1.10] Can't push to private registry

### ISSUE THREAD

**Issue by geissdoerfer** [docker/docker#20104]
Running a registry (`registry:2.3`) on `somehost:5000` with TLS. 

Pushing the images from docker 1.9
```
docker --version
Docker version 1.9.1, build a34a1d5
``` 
works as expected.

When pushing from docker 1.10 
```
docker --version
Docker version 1.10.0, build 590d5108
```

```
docker push somehost:5000/someimage
The push refers to a repository [somehost:5000/someimage]
88845c8d6bba: Pushed 
ee2754fa8a70: Pushed 
af802994b36b: Pushed 
d570987b7ef3: Pushed 
d889f924f1e7: Pushed 
f1f9da510ceb: Pushed 
12bfb8bedc56: Pushed 
d9a5758a1233: Pushed 
553f5b0fe85e: Pushed 
bacf371c2eee: Pushed 
c8e22318f4c4: Pushed 
01ec7f26f836: Pushed 
095dc581fddf: Pushed 
5f70bf18a086: Pushed 
314fc1ee156b: Pushed 
4d6aa1aa583e: Pushed 
cde9196e5cc7: Pushed 
283b24c4a7bb: Pushed 
f5c1535f7dcf: Pushed 
6859151bd499: Pushed 
2c63ca40402a: Pushed 
c48b7334bb1a: Pushed 
1f253a0703ec: Pushing 1.895 kB/1.895 kB
80ec921b230b: Retrying in 4 seconds 
227021bc9aa6: Pushing 32.66 MB/187.7 MB
Get http://somehost:5000/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

**Comment by tiborvass** [comment]
@geissdoerfer would you mind providing more information for us to reproduce? Is there maybe a docker hub image you can reproduce it with?

**Comment by aaronlehmann** [comment]
@geissdoerfer: Can you please run the Docker daemon with `-D` (debug) and capture its log?

`Get http://somehost:5000/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"` indicates that the Docker engine tried to fall back to plaintext HTTP after encountering an error. Unfortunately, we don't see the original error here, only the error when plaintext HTTP doesn't work. Are you passing `--insecure-registry` to the daemon? If so, I'd suggest removing this flag, since the registry is using TLS. This fallback behavior could also happen if `somehost` resolves to a local IP address.

**Comment by geissdoerfer** [comment]
@tiborvass Of course not.. I will check with the default ubuntu image on wednesday, if that is helpful.
@aaronlehmann  no, i have a signed certificate so i don't use `--insecure-registry` i'm starting the registry using ansible
```
- name: launch docker registry
  docker:
    image: registry:2.3
    name: some-registry
    ports: 
      - "5000:5000"
    state: started
    volumes:
      - /etc/certs:/certs:ro
    env:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/somecert.crt
      REGISTRY_HTTP_TLS_KEY: /certs/somekey.key
```
and calling docker with `docker push somehost:5000/someimage`. I have neither set any environment variables nor changed any configuration files. Indeed somehost resolves to a local IP. Why is that a problem? Were there any changes in recent version? As it works with 1.9..
I will post the debug capture on wednesday as well.
