### ISSUE TITLE
command with CRLF

### ISSUE THREAD

**Issue by vutran** [docker/docker#20211]
Not sure if this is already reported.

Script doesn't seem to be running (using Windows) when my line endings are CRLF.

***docker-compose.yml***
```
web:
  image: node:4
  volumes:
    - ..:/usr/src/app
  working_dir: /usr/src/app
  command: sh ./init.sh
```

***init.sh*** (line-ending as CRLF)
```
#!/bin/bash

# npm install some-packages

npm start
```

I had to convert the line endings to LF for the container to successfully execute the script.
