### ISSUE TITLE
FreeTDS connection error from within container (but tsql works externally)

### ISSUE THREAD

**Issue by o1lo01ol1o** [docker/docker#20700]
I'm posting here in hopes of getting some advice as the internet seems to be otherwise out of ideas.

I have a working FreeTDS configuration inside of a container: I can both ping and connect to the configured server with `TDSVER=7.2 tsql -H myhost -p 1433 -U user -P pass`

I can even run queries with `isql`, however, my sqlalchemy connection string fails with the well-known:
```
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('08001', '[08001] [unixODBC][FreeTDS][SQL Server]Unable to connect to data source (0) (SQLDriverConnect)')
```
This should point to a configuration issue, however, copying the freeTDS configuration and cloning the repo that is pulled by my dockerfile outside the container yields a working connection with the same connection string.

Is there some magic I'm missing here? 

`$ docker version`
```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
```
 
running Kubuntu:

`$ uname -r`
```
4.3.0-040300-generic
```

**Comment by cpuguy83** [comment]
Really need some more info like how the container is setup, how you are trying to connect, etc.

**Comment by o1lo01ol1o** [comment]
@cpuguy83 Thanks for the response, I didn't post the whole config as I wasn't sure what would be relevant. Let me know what other information I can provide.

Container is deployed to a swarm with agents and master using consul as the kv store (currently only running on one local, physical node).  The container logs show they're able to communicate among one another, they come online with the exception of the aforementioned web service, which fails on trying to reach the external MSSQL server.  Each container builds from the same docker file which clones the same gitrepo on build.

`web2`, which only uses the `front` network is able to access the external server without issues but `web` cannot.  They both use the same connection string.

abridged `docker-compose.yml`
```
version: '2'
services:
  web:
      build:
          context: ./base
          dockerfile: dockerfile
      command: python /home/docker_user/[repo]/runserver.py
      ports:
          - "5000:5000"
      networks:
          - back
          - front

  web2:
      build:
          context: ./base
          dockerfile: dockerfile
      command: python /home/docker_user/[repo]/[sub]/runserver.py
      ports:
          - "5001:5001"
      networks:
          - front

networks:
  front:
      external: true
  back:
      driver: overlay
```

`$ docker info`
```
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 248
Server Version: 1.10.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-26869994-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.841 GB
 Data Space Total: 107.4 GB
 Data Space Available: 97.53 GB
 Metadata Space Used: 22.96 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.125 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: overlay bridge null host
Kernel Version: 4.3.0-040300-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.84 GiB
Name: [Redacted]
ID: L6JC:UUE6:ZXUQ:VA32:LRH5:CAJK:N7UN:MDUX:JJJ5:Z6IR:TN2A:7GZM
WARNING: No swap limit support
Labels:
 device.gpu.0=yes
 device.gpu.1=yes
 rabbitmq-host=yes
Cluster store: consul:[Redacted]
Cluster advertise: [Redacted]
```
