### ISSUE TITLE
build from url with local context of onbuild copy

### ISSUE THREAD

**Issue by tomdavidson** [docker/docker#22101]
Building from URL could be very convenient with onbuild images, but it seems that the context is not the current working path. onbuild copy could not work as one might expect. 

Can can I build from url such as following but have onbuild copy context work against the local working directory?:
```
docker build https://github.com/repo.git#branch:folder
```
or
 ```
services:
  web:
    build: https://github.com/repo.git#branch:folder
    ports:
     - "80:80"
    env_file:
     - stage.env
```
