### ISSUE TITLE
Empty mount points after docker-compose up

### ISSUE THREAD

**Issue by cmaessen** [docker/docker#22430]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 106
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: O63S:R25X:ROPH:XA64:FPN6:I6IG:IAG3:JSJF:ZB6R:EAX6:5QRN:BRUF
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 25
 Goroutines: 64
 System Time: 2016-04-30T04:56:44.27369006Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* Microsoft Windows [Version 10.0.10586]
* VirtualBox 5.0.16 r 10871
* Compose file based on [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-and-phpmyadmin-with-docker-compose-on-ubuntu-14-04) (runs and works)

**Steps to reproduce the issue:**
1. In Virtual Box under 'Settings' -> 'Shared Folders' added 'workspaces' folder that points to 'F:\Workspaces' (Auto-mount and Make Permanent enabled)
2. Add to docker-compose.yml:
```
  volumes:
    - /workspaces/AptanaStudio3/RealScepticTsuno/build/:/var/www/html/wp-content/themes/realsceptictsuno/
```
3. docker-compose up (runs without giving any errors about mounts/volumes)

**Describe the results you received:**
```
docker@default:/workspaces/AptanaStudio3/RealScepticTsuno/build$ ls -hla
total 0
drwxr-xr-x    2 root     root          40 Apr 30 04:33 ./
drwxr-xr-x    3 root     root          60 Apr 30 04:33 ../
```

The WordPress container does see the theme folder and is complaining about the missing theme style file (indicating that the mount is indeed available but doesn't have any content).

**Describe the results you expected:**

File listing as generated by my build process for a WordPress theme.

**Additional information you deem important (e.g. issue happens only occasionally):**

I strongly suspect that I'm doing something that isn't correct. But any documentation I've found, or tutorials, are extremely silent on the details of how these mounts work if you're not in c:/users on Windows. Even the official docker documentation[doesn't mention this in their [WordPress quickstart](https://docs.docker.com/compose/wordpress/) nor does the [docker-compose documentation](https://docs.docker.com/compose/compose-file/) clarify this.

**Comment by fntlnz** [comment]
Files are available in the `/var/www/html/wp-content/themes/realsceptictsuno/` folder?

Can you please post the output of this command? (substitute container-id with your)

```
 docker inspect -f '{{.HostConfig.Binds}}' <container-id>
```

**Comment by cmaessen** [comment]
The default machine in VirtualBox (I started a SSH session to confirm this) nor the container see any files in /var/www/html/wp-content/themes/realsceptictsuno/.

On my machine the files are in the directory F:\Workspaces\AptanaStudio3\RealScepticTsuno\build. I've linked F:\Workspaces to \workspaces in VirtualBox which if I understand the instructions correctly means I can then write an absolute path starting with /workspaces to access the files that I have in F:\Workspaces.

Here's the result of the docker inspect command for the WordPress container:
```
[/workspaces/AptanaStudio3/RealScepticTsuno/build:/var/www/html/wp-content/themes/realsceptictsuno:rw]
```

For context, here's the docker-compose.yml content:
```
wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
  volumes:
    - /workspaces/AptanaStudio3/RealScepticTsuno/build/:/var/www/html/wp-content/themes/realsceptictsuno/
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: examplepass
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass
```
