### ISSUE TITLE
Embedded DNS can't work

### ISSUE THREAD

**Issue by tyrone98** [docker/docker#22545]
docker version 

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

I use docker-compose for our contains

uname -a

```
Linux node1 4.4.0-21-generic #37~14.04.1-Ubuntu SMP Wed Apr 20 16:33:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

OS version

```
Ubuntu 14.04.4 LTS
```

I run ping in my contains

```
#docker exec -it prod_factom_1 ping github.com
ping: unknown host
#docker exec -it prod_factom_1 /tmp/busybox netstat -an 
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.1:8384          0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:8108            0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.11:40917        0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:8089          0.0.0.0:*               LISTEN      
tcp        0      0 ::1:8384                :::*                    LISTEN      
tcp        0      0 :::8108                 :::*                    LISTEN      
tcp        0      0 :::8088                 :::*                    LISTEN      
tcp        0      0 :::8090                 :::*                    LISTEN      
udp     2304      0 172.18.0.2:57972        100.100.2.138:53        ESTABLISHED 
udp     2304      0 172.18.0.2:35288        100.100.2.136:53        ESTABLISHED 
udp        0      0 127.0.0.11:44811        0.0.0.0:*                           
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
unix  2      [ ACC ]     STREAM     LISTENING     111458 /var/run/supervisor.sock.1
```

 I modified /etc/resolv.conf  replace nameserver from 127.0.0.11 to default dns server 100.100.2.136

```
#ping github.com
PING github.com (192.30.252.120) 56(84) bytes of data.
64 bytes from github.com (192.30.252.120): icmp_seq=1 ttl=48 time=244 ms
64 bytes from github.com (192.30.252.120): icmp_seq=2 ttl=48 time=244 ms
64 bytes from github.com (192.30.252.120): icmp_seq=3 ttl=48 time=244 ms
64 bytes from github.com (192.30.252.120): icmp_seq=4 ttl=48 time=244 ms
64 bytes from github.com (192.30.252.120): icmp_seq=5 ttl=48 time=244 ms
```

It's can work 。

It also can work on restart contains , but wait a period of time , the embedded dns can't work and  recv-q > 0 。

**Comment by mavenugo** [comment]
@tyrone98 can you pls share the compose file ?

**Comment by sanimej** [comment]
@tyrone98 This looks like the same issue reported in #22185

**Comment by tyrone98** [comment]
It's my compose file 
```
version: '2'
services:
  frontend:
    environment:
     - "TZ=Asia/Shanghai"
    image: registry.aliyuncs.com/eagle/frontend:production
    volumes:
     - /data/production/frontend:/config
    ports: 
     - 80:80
     - 443:443
    depends_on:
     - backend
  backend:
    environment:
     - "TZ=Asia/Shanghai"
    image: registry.aliyuncs.com/eagle/backend:production
    volumes:
     - /data/production/backend:/config
    depends_on:
     - redis
     - mysql
     - factom
     - factom-sandbox
  factom-sandbox:
    environment:
     - "TZ=Asia/Shanghai"
    volumes:
     - /data/production/factom-sandbox:/home/factom/.factom
    image: tyrone98/factom
  factom:
    environment:
     - "TZ=Asia/Shanghai"
    volumes:
     - /data/production/factom:/home/factom/.factom
    image: tyrone98/factom
  redis:
    environment:
     - "TZ=Asia/Shanghai"
    volumes:
     - /data/production/redis:/data
    image: redis
  mysql:
    environment:
     - "TZ=Asia/Shanghai"
    image: registry.aliyuncs.com/eagle/mysql
    volumes:
      - /data/production/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hello123
      - MYSQL_DATABASE=eagle
```
