### ISSUE TITLE
Daemon config setting to disable 'legacy' mode on the default bridge

### ISSUE THREAD

**Issue by far-blue** [docker/docker#22803]
It would be hugely helpful if there was a daemon config setting to disable 'legacy' mode on the default bridge so it can participate in multi-network setups in docker-compose. Or, alternatively, maybe legacy mode is disabled by default when the daemon is started with the -b config parameter to specify a replacement default bridge.

**Comment by thaJeztah** [comment]
With "legacy mode" you mean the "legacy links"? If you're using the docker compose V2 file format, you'll automatically get the new networking; https://docs.docker.com/compose/compose-file/#versioning

**Comment by far-blue** [comment]
no, it's more to do with how docker-compose uses aliases. If you try to setup a front and a back network where the back network is the default bridge then docker-compose complains with:

> Network-scoped alias is supported only for containers in user defined networks

If, like me, you have overridden the default bridge (in my case, with Ubuntu's Fan Network stuff) and you want to present a limited number of containers from a docker-compose group on that default bridge so others containers can talk to them then at the moment you can't do it.

**Comment by far-blue** [comment]
e.g. as a pseudocode example:
```
version '2'
services:
  web:
    image: nginx
    networks:
      - front
      - default
  db:
    image: mysql
networks:
  front:
    external:
      name: bridge
```
