### ISSUE TITLE
Docker in Docker on Jenkins

### ISSUE THREAD

**Issue by devotox** [docker/docker#22815]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Wed Apr 27 15:27:26 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 113
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 228
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: doctify-dev
ID: DZ7Y:NUVH:7QAW:76P4:N7BZ:Y4OV:XWZY:75YB:ZYIH:6K6O:BV2T:FFIV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 61
 Goroutines: 113
 System Time: 2016-05-18T15:04:01.328784183Z
 EventsListeners: 2
Username: devotox
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtualbox
Jenkins

**Steps to reproduce the issue:**
1. run jenkins container
2. create a build that uses docker-compose
3. docker-compose -p $application_name -f docker-compose/$compose_file up -d

**Describe the results you received:**
The build command works using 
```
docker-compose -p $application_name -f docker-compose/$compose_file build --pull
```
but running
```
docker-compose -p $application_name -f docker-compose/$compose_file up -d
```
does not

```
Successfully built 971eceb71233
consul uses an image, skipping
registrator uses an image, skipping
consul-template uses an image, skipping
Creating doctify_database_1
rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: not a directory"
```

**Describe the results you expected:**

I expect the test file to be able to be run 

The jenkins yml compose file
```

    jenkins:
        build:
            context: ../jenkins
            dockerfile: Dockerfile
        volumes:
            - ../.ebextensions:/var/app/current/.ebextensions
            - /var/run/docker.sock:/var/run/docker.sock
            - ../security:/var/app/current/security
            - ../sslcert:/var/app/current/sslcert
            - ../shared:/var/app/current/shared
            - jenkins_home:/var/jenkins_home
            - ../cron:/var/app/current/cron
            - ../jenkins:/var/jenkins
            - /var/log/jenkins

```

the test yml file

```
version: '2'
services:
    database:
        build:
            context: ../database
            dockerfile: Dockerfile
        volumes:
            - ../database/build.sql:/docker-entrypoint-initdb.d/build.sql
            - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - /var/run/docker.sock:/var/run/docker.sock
            - ../database:/var/app/current/database
            - ../sslcert:/var/app/current/sslcert
            - ../shared:/var/app/current/shared
            - /var/lib/postgresql
            - /var/log/postgresql
        ports:
            - 5432
        extends:
            service: base
            file: ../shared/base.yml
    website:
        privileged: true
        command: bash -c "sysctl -w fs.inotify.max_user_watches=1048576 && grunt serve 2>&1 | tee -a /var/log/website/website.log"
        build:
            context: ../website
            dockerfile: Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/app/current/website/bower_components
            - /var/app/current/website/node_modules
            - ../website:/var/app/current/website
            - ../shared:/var/app/current/shared
            - /var/log/website
            - /tmp/website
        depends_on:
            - database
            - redis
        ports:
            - 9000
            - 39000
        extends:
            service: base
            file: ../shared/base.yml
    intranet:
        privileged: true
        command: bash -c "sysctl -w fs.inotify.max_user_watches=1048576 && ember serve 2>&1 | tee -a /var/log/intranet/intranet.log"
        build:
            context: ../intranet
            dockerfile: Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/app/current/intranet/bower_components
            - /var/app/current/intranet/node_modules
            - ../intranet:/var/app/current/intranet
            - ../shared:/var/app/current/shared
            - /var/log/intranet
            - /tmp/intranet
        ports:
            - 8000
            - 38000
        depends_on:
            - database
            - redis
        extends:
            service: base
            file: ../shared/base.yml
    api:
        privileged: true
        command: bash -c "sysctl -w fs.inotify.max_user_watches=1048576 && gulp start 2>&1 | tee -a /var/log/api/api.log"
        build:
            context: ../api
            dockerfile: Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/app/current/api/bower_components
            - ../sslcert:/var/app/current/sslcert
            - /var/app/current/api/node_modules
            - ../shared:/var/app/current/shared
            - ../api:/var/app/current/api
            - /var/log/api
            - /tmp/api
        volumes_from:
            - website
            - intranet
        depends_on:
            - database
            - redis
        ports:
            - 3000
            - 9999
        extends:
            service: base
            file: ../shared/base.yml
    server:
        build:
            context: ../nginx
            dockerfile: Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ../security:/var/app/current/security
            - ../sslcert:/var/app/current/sslcert
            - ../shared:/var/app/current/shared
            - ../nginx:/etc/nginx
            - /var/log/nginx
        volumes_from:
            - api
            - redis
            - website
            - intranet
            - database
        ports:
            - 8080:8080
            - 8443:8443
            - 5432:5432
            - 6379:6379
            - 38100:38100
            - 39100:39100
        extends:
            service: base
            file: ../shared/base.yml
    redis:
        privileged: true
        image: torusware/speedus-redis
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /data
        ports:
            - 6379
    registrator:
        image: devotox/registrator
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/run/docker.sock:/tmp/docker.sock
        depends_on:
            - consul
        extends:
            service: base
            file: ../shared/base.yml
    consul:
        command: -bootstrap
        image: gliderlabs/consul-server
        ports:
            - 53
            - 8301
            - 8302
            - 8300
            - 8400
            - 8500
            - 53/udp
            - 8301/udp
            - 8302/udp
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - server
        extends:
            service: base
            file: ../shared/base.yml
    consul-template:
        image: devotox/consul-template
        command: >
            -consul consul:8500
            -template /etc/nginx/templates/upstream_servers.ctmpl:/etc/nginx/conf.d/upstream_servers.conf
            -template /etc/nginx/templates/upstream_stream_servers.ctmpl:/etc/nginx/conf.d/streams/upstream_servers.conf
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        volumes_from:
            - server
        depends_on:
            - consul
            - registrator
        extends:
            service: base
            file: ../shared/base.yml
```

**Additional information you deem important (e.g. issue happens only occasionally):**
