### ISSUE TITLE
container volumes don't respect host's folder contents

### ISSUE THREAD

**Issue by satboy78** [docker/docker#22858]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 102
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: FBGE:GI35:DJTM:ERRB:FOJH:TPYV:6VP7:347F:VQJO:LPG2:TJO6:6XL7
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 23
 Goroutines: 50
 System Time: 2016-05-20T16:23:59.569855833Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm using docker beta on OS X Yosemite v10.10.4 (14e46)

**Steps to reproduce the issue:**
1. docker-compose up -d
2. enter in apache container
3. check contents of mounted volume: it doesn't respect host's folder contents

**Describe the results you received:**

/ # cd projects/
/projects # ls -la
total 4
drwxr-xr-x    3 root     root            60 May 20 14:24 .
drwxr-xr-x   38 root     root          4096 May 20 15:39 ..
drwxr-xr-x    4 root     root            80 May 20 14:24 orientdb

**Describe the results you expected:**

drwxrwxrwx  14 sviluppo  staff       476 May 20 15:16 api.dta.vn.com
drwxrwxrwx  20 sviluppo  staff       680 May 17 18:24 cy.com
drwxrwxrwx  12 sviluppo  staff       408 May 12 17:44 cra-vmn
drwxrwxrwx   9 sviluppo  staff       306 May 13 10:03 cra-vn-1-0
drwxrwxrwx  16 sviluppo  staff       544 May 18 15:02 ddtv.com
drwxrwxrwx   4 sviluppo  staff       136 May 20 16:26 orientdb
drwxrwxrwx  10 sviluppo  staff       340 May  6 14:50 pushnotifications

**Comment by thaJeztah** [comment]
Can you;

- share your docker-compose file
- tell which directory you're running this from (is the directory that your project / docker-compose file is in inside `/Users` or outside?
- check if you're able to reproduce this issue with just docker (no docker-compose), so something like:


```bash
docker run -it -v $(pwd):/host-mount --rm alpine ls -la /host-mount
```

**Comment by satboy78** [comment]
Sure!
Here the additional informations.

**docker-compose file:**
```
version: '2'
services:
  webserver:
    image: quay.vn.io/ment/me-dev-apache
    volumes:
      - "/projects/api.dta.vn.com:/projects/api.dta.vn.com"
    ports:
      - "80:80"

  php:
    image: quay.vn.io/ment/me-dev-php7
    volumes:
      - "/projects/api.playplex.vimn.com:/projects/api.dta.vn.com"
    network_mode: "service:webserver"

  redis:
    image: quay.vn.io/ment/redis
    network_mode: "service:webserver"
```

I run docker-compose file from a subfolder of my user (so /Users/sviluppo/docker-env)


I use the same images in a vagrant-docker environment (so docker inside a vagrant ubuntu 14.04 vm), and I don't have any problems, I can see all files and folders; I run this vagrant-docker environment from a subfolder of my user (so /Users/sviluppo/vagrant-docker-env)
