### ISSUE TITLE
Shared volumes within containers are getting corrupted.

### ISSUE THREAD

**Issue by Milewski** [docker/docker#23194]
When mounting a shared volume within two images

```yml
php:
  image: php:fpm-alpine
  container_name: php
  volumes:
    - .:/var/www

gulp:
  build: .
  dockerfile: ./build/docker/gulp/Dockerfile
  container_name: gulp
  volumes_from:
      - php
  entrypoint: top -b
```

when i update from gulp the file on **/var/www/test.css** for example the change got reflected on the host machine, however not in php container. 

actually at this point something really weird start happening, these characters start appearing on all over the file "���������....."

if i delete the file **/var/www/test.css** and create again with the new content, then no issues.

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 30
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 127
 Dirperm1 Supported: true
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: ubuntu
ID: IAII:URKY:RGHO:H4UG:BB3N:LMXI:6FJM:DZRX:2GKT:N3RB:5BNR:5LW7
Debug mode (server): true
 File Descriptors: 28
 Goroutines: 86
 System Time: 2016-06-02T10:33:20.145533786Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: 
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: rmilewski
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
