### ISSUE TITLE
Cannot access the docker container via OpenVPN

### ISSUE THREAD

**Issue by phlegx** [docker/docker#23298]
I have a docker (version 1.11.1) `openvpn_client` container running that connects the host to my VPN network. This is working just fine. 
However, when I start my `munin` container and bind it to the VPN IP `172.18.5.9:8080` then I cannot access the container from my remote (local host). 
I tried via telnet to access 172.18.5.9 on port 8080 but no luck. I can however access to my hosts 'native' SSH server via VPN (172.18.5.9 port 22) just fine.

Here is my docker-compose file just to make my setup clear.

```
version: "2"
services:
    munin:
      build: munin
      ports:
        - "172.18.5.9:8080:8080"

    openvpn_client:
      build: ../openvpn_client
      environment:
        CLIENT_CONFIG: server01.example.com.conf
      network_mode: host
      devices:
        - /dev/net/tun:/dev/net/tun
      cap_add:
        - NET_ADMIN
```

Maybe someone can give me a hint! Thanks!

PS: 

Actually I now also tried to simply map the port `8080` to ``0.0.0.0` so that it listens on all interfaces, but also that is not working. I'm out of ideas actually... 

As already stated the VPN works as expected and the iptable routes are ok. I can access the port 8080 via public IP just fine. Via VPN it is not working.

---

**docker version**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**docker info**

```
Containers: 22
 Running: 8
 Paused: 0
 Stopped: 14
Images: 528
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 633
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-70-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.69 GiB
Name: machine.example.com
ID: QYQV:YBR4:WAQQ:ONCC:VRCU:3COL:ZT72:G4ZW:236F:BGDZ:5HT2:QFSL
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**iptables -t nat -L -nv**

See: https://gist.github.com/phlegx/de09ddd55091da486a021021823fc8e9
