### ISSUE TITLE
Strange behavior on Named Volumes and Dockerfile ADD/COPY commands

### ISSUE THREAD

**Issue by boramod** [docker/docker#23357]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 61
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 58
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: TLS3:EGZW:PFMY:SDXL:3QN5:RZAM:DMJC:3TZ2:3NWB:57N2:5IL4:QCNQ
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 29
 Goroutines: 52
 System Time: 2016-06-07T22:11:28.545309066Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Local machine, Mac OS X 10.11

**Steps to reproduce the issue:**
1 Create a project `docker-compose.yml` file
```
version: '2'
services:
  app:
    container_name: app
    build: ./app
    volumes:
      - appVolume:/var/www/app
  web:
    extends:
      file: docker-compose-common.yml
      service: web
    ports:
      - "80:80"
      - "443-443"
      - "9000:9000"
    volumes:
      - appVolume:/var/www/app
    env_file:
      - ./config/prod/common.env
      - ./config/prod/db.env
      - ./config/prod/phinx.env
volumes:
  appVolume:
```
Where: 
`app` — container for dockerized php application, 
`web` — nginx+php-fpm container (working fine, without problems),
`appVolume` — named volume for share app container php application files between other containers. 

2 Create base `Dockerfile` for `app`
```
FROM debian:jessie
MAINTAINER Alex Fatyeev <alex.fatyeev@gmail.com>
COPY . /var/www/app/
VOLUME ["/var/www/app"]
CMD ["true"]
```
3 Create test `index.php`
```
<?php
echo "Hello World V1";
```
4 Build & start project
`docker-compose up`

5 Check result in browser:

> Hello World V1

5 Make some changes in index.php
```
<?php
echo "Hello World V2";
```
6 Rebuild image & recreate `app` container
`docker-compose --file docker-compose.yml up --build --force-recreate -d app`

7 Check result in browser:

> Hello World V1

**Describe the results you received:**
In both attempts I received same result:
> Hello World V1

**Describe the results you expected:**
After changes in `index.php` and successfully rebuild & recreate image and container I expected
> Hello World V2

**Additional information you deem important (e.g. issue happens only occasionally):**
Both builds & recreation done **without cache** of COPY command. But second without overriding exiting index.php.   

First: build & creation:
```
Building app
Step 1 : FROM debian:jessie
 ---> 1742affe03b5
Step 2 : MAINTAINER Alex Fatyeev <alex.fatyeev@gmail.com>
 ---> Using cache
 ---> 99f856fed701
Step 3 : COPY . /var/www/app/
 ---> 2d4b92ec125e
Removing intermediate container ed79f6e0d862
Step 4 : VOLUME /var/www/app
 ---> Running in 81dcdf678812
 ---> b094dbf8dd0f
Removing intermediate container 81dcdf678812
Step 5 : CMD true
```
Second: rebuild & recreation:
```
Building app
Step 1 : FROM debian:jessie
 ---> 1742affe03b5
Step 2 : MAINTAINER Alex Fatyeev <alex.fatyeev@gmail.com>
 ---> Using cache
 ---> 99f856fed701
Step 3 : COPY . /var/www/app/
 ---> d14f24390bf8
Removing intermediate container 6e4b32d74649
Step 4 : VOLUME /var/www/app
 ---> Running in 223df2c97f6f
 ---> d974160b589f
Removing intermediate container 223df2c97f6f
Step 5 : CMD true
 ---> Running in f0750d1e8860
 ---> 494ff04c636a
Removing intermediate container f0750d1e8860
Successfully built 494ff04c636a
Recreating app
```
