### ISSUE TITLE
Connection refused between linked containers in a custom network

### ISSUE THREAD

**Issue by atanass** [docker/docker#23849]
I have the following case with Docker:

In a compose file I create a custom network the following way:

```
networks:
  my-docker-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.238.0/24
          gateway: 172.20.238.1
```

After that I create a couple of containers that are part of that network. They are linked and they both expose the same ports to the host (I don't want to publish the port, I just want to make it accessible from the host and the other container)

```
  web-backend-2:
    build: ./backend-web
    hostname: web-backend-host-2
    links:
      - web-backend-1
    expose:
      - 47500
    networks:
      my-docker-network:
        aliases:
          - backend2
    container_name: web-backend-2-service

  web-backend-1:
    build: ./backend-web
    hostname: web-backend-host-1
    expose:
      - 47500
    networks:
      my-docker-network:
        aliases:
          - backend1
    container_name: web-backend-1-service
```

The backend-web project is a simple centos7 container with a tomcat and some specific tomcat configurations. Now, when I compose the whole thing everything is just fine with one exception: I cannot connect from backend1 to backend2 (and vice-versa) on port 47500:

```
telnet backend1 47500
Trying 172.20.238.3...
telnet: connect to address 172.20.238.3: Connection refused
```

What's even more puzzling is that a telnet is successful on port 8080 without any EXPOSE declaration for it.

```
Docker version 1.11.2, build b9f10c9
docker-compose version 1.7.1, build 0a9ab35
```

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 133
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-101267493-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.475 GB
 Data Space Total: 107.4 GB
 Data Space Available: 22.88 GB
 Metadata Space Used: 14.12 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 15.51 GiB
Name: il-container01
ID: RYJN:UNCF:XOSQ:M6QN:HJAU:7JPY:HRZE:RFBA:N6AA:UD22:WL6V:3GBH
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual machine on VMWare
