### ISSUE TITLE
docker-compose with docker-swarm deploys all containers to same node

### ISSUE THREAD

**Issue by charlesmims** [docker/docker#23885]
**Output of `docker version`:**

[22:39:30] cmims@MBP:~/dc-mesos$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      swarm/1.2.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   eaa53c7
 Built:        Fri May 27 17:25:03 UTC 2016
 OS/Arch:      linux/amd64
[22:39:34] cmims@MBP:~/dc-mesos$

This is on OSX el capitan, all recent updates applied.  Previously I was running docker-toolbox 1.10 or 1.11, and today I installed OSX native docker and the most recent docker-toolbox. 

**Output of `docker info`:**

[22:39:34] cmims@MBP:~/dc-mesos$ docker info
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 17
Server Version: swarm/1.2.3
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 3
 swarm-demo-1: 192.168.99.103:2376
  └ ID: SGMI:VTIP:F5UD:AN4M:ADT7:GA5Y:DNDA:S362:LITZ:QAKG:MIEC:OAT6
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=, kernelversion=4.4.13-boot2docker, operatingsystem=Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-06-23T03:40:09Z
  └ ServerVersion: 1.12.0-rc2
 swarm-demo-2: 192.168.99.102:2376
  └ ID: SVL3:FEDI:ZIEX:MD5F:TWSA:V34I:EHLZ:EURR:VVGV:S7L7:R2F3:CB5T
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=, kernelversion=4.4.13-boot2docker, operatingsystem=Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-06-23T03:40:05Z
  └ ServerVersion: 1.12.0-rc2
 swarm-demo-3: 192.168.99.101:2376
  └ ID: SNXV:XMFE:KZXV:NVVX:3CM4:KK2F:H2U2:RV5B:TVVG:JCLI:5ORK:CWM4
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=, kernelversion=4.4.13-boot2docker, operatingsystem=Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-06-23T03:40:09Z
  └ ServerVersion: 1.12.0-rc2
Plugins:
 Volume:
 Network:
Swarm:
 NodeID:
 IsManager: No
Security Options:
Kernel Version: 4.4.13-boot2docker
Operating System: linux
Architecture: amd64
CPUs: 3
Total Memory: 3.063 GiB
Name: d5f281428064
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support

**Steps to reproduce the issue:**

  1- create a file called "swaminate" with the following:
```
set -e

create() {
  echo Setting up kv store
  docker-machine create -d virtualbox kvstore > /dev/null && \
  docker $(docker-machine config kvstore) run -d --net=host progrium/consul --server -bootstrap-expect 1

  # store the IP address of the kvstore machine
  kvip=$(docker-machine ip kvstore)

  echo Creating cluster nodes
  docker-machine create -d virtualbox \
    --engine-opt "cluster-store consul://${kvip}:8500" \
    --engine-opt "cluster-advertise eth1:2376" \
    --swarm \
    --swarm-master \
    --swarm-discovery consul://${kvip}:8500 \
    swarm-demo-1 > /dev/null &

  for i in 2 3; do
    docker-machine create -d virtualbox \
      --engine-opt "cluster-store consul://${kvip}:8500" \
      --engine-opt "cluster-advertise eth1:2376" \
      --swarm \
      --swarm-discovery consul://${kvip}:8500 \
      swarm-demo-$i > /dev/null &
  done
  wait
}

teardown() {
  docker-machine rm kvstore &
  for i in 1 2 3; do
    docker-machine rm -f swarm-demo-$i &
  done
  wait
}

case $1 in
  up)
    create
    ;;
  down)
    teardown
    ;;
  *)
    echo "I literally can't even..."
    exit 1
    ;;
esac
```

  2- bring the cluster up

```
chmod +x swarminator
./swarminator up
```

  3- create docker-compose.yml with the following:

```
version: '2'
services:
  zookeeper:
    image: garland/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  mesosmaster:
    image: garland/mesosphere-docker-mesos-master
    ports:
      - "5050:5050"
    links:
      - zookeeper:zk
    environment:
      - MESOS_ZK=zk://zk:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_WORK_DIR=/var/lib/mesos
  marathon:
    image: garland/mesosphere-docker-marathon
    links:
      - zookeeper:zk
      - mesosmaster:master
    command: --master zk://zk:2181/mesos --zk zk://zk:2181/marathon
    ports:
      - "8080:8080"
  mesosslave:
    image: garland/mesosphere-docker-mesos-master
    ports:
      - "5051:5051"
    links:
      - zookeeper:zk
      - mesosmaster:master
    entrypoint: mesos-slave
    environment:
      - MESOS_HOSTNAME=192.168.99.100
      - MESOS_MASTER=zk://zk:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_LOGGING_LEVEL=INFO
```

  4- run the docker compose on the swarm

```
eval $(docker-machine env --swarm swarm-demo-1)
docker-compose up
```

**Describe the results you received:**

The above steps will create 4 containers all on the same node of the swarm.  Attempting to scale up mesos slaves with `docker-compose mesoslave=2` will give the following error:

```
[22:50:16] cmims@MBP:~/dc-mesos$ docker-compose scale mesosslave=2
WARNING: The "mesosslave" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting dcmesos_mesosslave_2 ... error

ERROR: for dcmesos_mesosslave_2  Unable to find a node that satisfies the following conditions
[port 5051 (Bridge mode)]
[available container slots]
[--link=dcmesos_mesosmaster_1:dcmesos_mesosmaster_1 --link=dcmesos_mesosmaster_1:master --link=dcmesos_mesosmaster_1:mesosmaster_1 --link=dcmesos_zookeeper_1:dcmesos_zookeeper_1 --link=dcmesos_zookeeper_1:zk --link=dcmesos_zookeeper_1:zookeeper_1]
```

```
[22:50:18] cmims@MBP:~/dc-mesos$ docker-machine ls
NAME           ACTIVE      DRIVER       STATE     URL                         SWARM                   DOCKER        ERRORS
kvstore        -           virtualbox   Running   tcp://192.168.99.100:2376                           v1.12.0-rc2
swarm-demo-1   * (swarm)   virtualbox   Running   tcp://192.168.99.103:2376   swarm-demo-1 (master)   v1.12.0-rc2
swarm-demo-2   -           virtualbox   Running   tcp://192.168.99.102:2376   swarm-demo-1            v1.12.0-rc2
swarm-demo-3   -           virtualbox   Running   tcp://192.168.99.101:2376   swarm-demo-1            v1.12.0-rc2
```

```
[22:51:43] cmims@MBP:~/dc-mesos$ docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                                                                         NAMES
41b081c97fd4        garland/mesosphere-docker-mesos-master   "mesos-slave"            2 minutes ago       Up 2 minutes        192.168.99.101:5051->5051/tcp                                                                 swarm-demo-3/dcmesos_mesosslave_1
a648d51dc63d        garland/mesosphere-docker-mesos-master   "mesos-master"           2 minutes ago       Up 2 minutes        192.168.99.101:5050->5050/tcp                                                                 swarm-demo-3/dcmesos_mesosmaster_1
df8a8408daa2        garland/zookeeper                        "/opt/run.sh"            2 minutes ago       Up 2 minutes        192.168.99.101:2181->2181/tcp, 192.168.99.101:2888->2888/tcp, 192.168.99.101:3888->3888/tcp   swarm-demo-3/dcmesos_zookeeper_1
ef66edee029a        nginx                                    "nginx -g 'daemon off"   25 minutes ago      Up 25 minutes       443/tcp, 192.168.99.102:8080->80/tcp                                                          swarm-demo-2/silly_pasteur
c3f8eb723c9d        nginx                                    "nginx -g 'daemon off"   25 minutes ago      Up 25 minutes       443/tcp, 192.168.99.101:8080->80/tcp                                                          swarm-demo-3/amazing_lumiere
c4f01a22354c        nginx                                    "nginx -g 'daemon off"   25 minutes ago      Up 25 minutes       443/tcp, 192.168.99.103:8080->80/tcp                                                          swarm-demo-1/big_wing
```

As a counter example, I can run `docker run -d -p 8080:80 nginx` as many times as there are nodes in the swarm, and it will create <number of swarm nodes> containers all listening on port 8080, each running on its own node at its own IP address, as shown in the above `docker ps` output.

**Describe the results you expected:**

I expected the output of `docker ps` to show that `docker-compose up`  deployed the containers from dc-mesos/docker-compose.yml to each of the nodes of the swarm, such that I could scale up mesosslave to at least the number of nodes in my swarm.

**Additional information you deem important (e.g. issue happens only occasionally):**

This has happened consistently through half a dozen attempts in various iterations since I updated to OSX native docker and 1.12.0-rc toolbox.  I don't know if it worked on what I was on before.  I think it was docker-toolbox with docker version 1.10 or 1.11.  I included the examples that I think are most illustrative of the problem in the steps to reproduce and output of `docker ps`.  If there is anything I can do to help isolate this further, or if others are unable to reproduce, please let me know at charlesmims@gmail.com.
