### ISSUE TITLE
Service not getting restarted after removal

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#24256]
Using `1.12.0-rc2-beta17`, single node Swarm cluster on Mac.

Use `docker-compose.yml`:

```
version: "2"
services:
  db:
    container_name: "db"
    image: arungupta/oreilly-couchbase:latest
    ports:
      - 8091:8091
      - 8092:8092 
      - 8093:8093 
      - 11210:11210
  web:
    image: arungupta/oreilly-wildfly:latest
    depends_on:
      - db
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080
```

Create DAB using `docker-compose bundle`

Deploy stack `docker deploy -f hellojavaee.dsb hellojavaee`

See the list of services:

```
docker service ls
ID            NAME             REPLICAS  IMAGE                                                                                                COMMAND
2950nqzptm75  hellojavaee_web  1/1       arungupta/oreilly-wildfly@sha256:d567ade7bb82ba8f15a85df0c6d692d85c15ec5a78d8826dfba92756babcb914    
9806venmps0f  hellojavaee_db   1/1       arungupta/oreilly-couchbase@sha256:f150fcb9fca5392075c96f1baffc7f893858ba763f3c05cf0908ef2613cbf34c  
```

Remove the `hellojavaee_web` service:

```
docker service rm hellojavaee_web
```

The service never restarted even after waiting for 10 minutes.
