### ISSUE TITLE
set volume size when create container

### ISSUE THREAD

**Issue by davidstack** [docker/docker#24318]
we can set volume size when create volume explicitly with command：
 `docker volume create --name volume1 -d driver-plugin -o size=1G`
but i can not find a way to set the volume size when create container except set a default value in mine volume plugin.
   `docker create -it -v wangdk2:/mnt --volume-driver=driver-plugin ubuntu:15.04 bash`
so when i use docker-compose to create container with volume,i can not set the volume size. Is there any methon to set the container volume size when create container? thanks.

**Comment by vdemeester** [comment]
@davidstack I don't think there is a way to pass driver options to volume driver directly in the `run` command. But with `docker-compose`, you can define the size on the volume when creating it using the `v2` compose files:

```yaml
version: "2"

services:
  myservice:
    # […]

volumes:
  wangdk2:
    driver: driver-plugin
    driver_opts:
      size: 1G
```
