### ISSUE TITLE
docker container not writing to mounted volume on host

### ISSUE THREAD

**Issue by babatundebusari** [docker/docker#24508]
I am having issue writing to the mounted volume on host filesystem from docker container

Is there some special thing i have to do when building the container to make the container write data to the mounted volume on host for persistency?

I have seen containers that write to host filesystem like the official mysql docker image and several others but when i build my own images, and i mount the volume on host, i find out it doesn't write to host, but only reads from the host.

Not sure what to add here code wise but if you guys need anything please ask and i will update my question.

Thanks

**Comment by Purple90** [comment]
Can you post your run command? You are probably not mapping it correctly. You need to do something like

docker run -v /foo/bar:/containerfolder

That will then be written on the host

**Comment by babatundebusari** [comment]
i am using docker-compose and yes i am mapping it properly, like i said it reads but does not write, so it won't be able to read either if am not mapping it well

Here is docker-compose of two images, grafana official image maps PROPERLY and writes ad reads, but the custom graphite image does NOT write but read only.

```
graphite:
    image: devsystem.com/graphite
    container_name: graphite
    restart: always
    ports:
        - "8080:80"
        - "2003:2003"
        - "2003:2003/udp"
        - "2004:2004"
        - "7002:7002"
        - "8125:8125"
        - "8126:8126"
    volumes:
        - "/data/var/lib/graphite/storage/whisper:/var/lib/graphite/storage/whisper"

grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
        - "80:3000"
    volumes:
        - "/data/var/lib/grafana:/var/lib/grafana"
    links:
        - graphite
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=whatever
```

**Comment by vdemeester** [comment]
@babatundebusari can you give us more information about your setup ?

- `docker version`, `docker info`
- The OS/Plateform you're running on (windows, mac, linux — docker for mac, docker toolbox, etc…)
- Are you pointing to a remote engine ?

Thanks 👼

**Comment by babatundebusari** [comment]
@vdemeester 

```
~# docker info

Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 116
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 144
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: complex-elk
ID: 34WC:25GN:4AMK:FJDZ:WNRN:FFRK:RWHW:BAOD:5OG4:LLBU:GTYU:MCO5
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```


```
~# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

```
~# cat /etc/*release*

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
```


No it is mounting to host filesystem on the docker engine host from container

**Comment by babatundebusari** [comment]
I am thinking there is something am doing wrong when building my custom images, because this always happen to my custom images

I also built an nginx-php-fpm image and it does not write to mounted volume on host filesystem as well, but reads.

So can someone tell me it there is anything i need to do apart from exposing that volume path to be mounted on Dockerfile, do i need to do anything else?

**Comment by vdemeester** [comment]
@babatundebusari how does your `Dockerfile` looks like ? Note that you don't need to declare a `VOLUME` in your `Dockerfile` to use `-v` flag on it :wink:

**Comment by babatundebusari** [comment]
@vdemeester 

looks like this

```
FROM ubuntu:14.04
MAINTAINER Babatunde Busari

ENV DEBIAN_FRONTEND noninteractive

RUN	echo 'deb http://us.archive.ubuntu.com/ubuntu/ trusty universe' >> /etc/apt/sources.list
RUN	apt-get -y update

RUN apt-get install -y software-properties-common && \
  add-apt-repository -y ppa:chris-lea/node.js && \
  apt-get update -y 
  
# Install required packages
RUN	apt-get -y install git python-ldap python-cairo python-django python-twisted python-django-tagging python-simplejson python-memcache python-pysqlite2 python-support python-tz python-pip gunicorn supervisor nginx-light nodejs build-essential curl
RUN	pip install whisper==0.9.15
RUN	pip install --install-option="--prefix=/var/lib/graphite" --install-option="--install-lib=/var/lib/graphite/lib" carbon==0.9.15
RUN	pip install --install-option="--prefix=/var/lib/graphite" --install-option="--install-lib=/var/lib/graphite/webapp" graphite-web==0.9.15


# install statsd
RUN git clone -b v0.7.2 https://github.com/etsy/statsd.git /opt/statsd

# ADD system service config
ADD	./nginx.conf /etc/nginx/nginx.conf
ADD	./supervisord.conf /etc/supervisor/conf.d/supervisord.conf
ADD ./statsd_config.js /etc/statsd/config.js


# ADD graphite config
ADD	./initial_data.json /var/lib/graphite/webapp/graphite/initial_data.json
ADD	./local_settings.py /var/lib/graphite/webapp/graphite/local_settings.py
ADD	./carbon.conf /var/lib/graphite/conf/carbon.conf
ADD	./storage-schemas.conf /var/lib/graphite/conf/storage-schemas.conf
RUN	mkdir -p /var/lib/graphite/storage/whisper
RUN	touch /var/lib/graphite/storage/graphite.db /var/lib/graphite/storage/index
RUN	chown -R www-data /var/lib/graphite/storage
RUN	chmod 0775 /var/lib/graphite/storage /var/lib/graphite/storage/whisper
RUN	chmod 0664 /var/lib/graphite/storage/graphite.db
RUN	cd /var/lib/graphite/webapp/graphite && python manage.py syncdb --noinput


# Setup Volume
VOLUME ["/var/lib/graphite/storage/whisper"]


# Nginx
EXPOSE	80
# Carbon line receiver port
EXPOSE	2003
# Carbon UDP receiver port
EXPOSE	2003/udp
# Carbon pickle receiver port
EXPOSE	2004
# Carbon cache query port
EXPOSE	7002
# StatsD UDP
EXPOSE 8125 
# StatsD Admin
EXPOSE 8126

CMD	["/usr/bin/supervisord"]
```

**Comment by thaJeztah** [comment]
@babatundebusari can you try with a minimum example? For example;

```yaml
tester:
    image: alpine
    volumes:
        - "./hostmount/:/var/lib/graphite/storage/whisper"
    command: "sh -c 'echo hello >> /var/lib/graphite/storage/whisper/blabla'"
```

This will create a directory `hostmount` on the host, and write a "blabla" file in it, containing "hello";

```bash
$ docker-compose up
Creating repro24508_tester_1
Attaching to repro24508_tester_1
repro24508_tester_1 exited with code 0

$ cat hostmount/blabla
hello
```
