### ISSUE TITLE
Change UID and GID on Windows (hyper-v) mounted volume

### ISSUE THREAD

**Issue by jenkys** [docker/docker#24733]
My OS is Windows 10, using client and server docker v 1.12.0-rc4.

Dockerfile:
```
FROM php:7.0-apache
WORKDIR /var/www
```

Docker-compose:
``` 
version: '2'

services:

  sandbox:
    build: .
    volumes:
      - ".:/var/www"
    ports:
      - 80:80
```

I build an image ` docker-compose up --build` and get in to the container by `winpty docker exec -it sandbox bash`.
Mounted dir /var/www is owned by root:root.
I want to be owned by www-data:www-data. 
On Kubuntu host system I just write `chown -R www-data:www-data /var/www`, but from Windows host system it does nothing and dir still owhned by root:root.
I want this to have ability to run composer, saving files, etc. from image, to user www-data have permission to write these files AND I want have permissions from host (windows) to edit these files by PHPStorm.

In docker running from windows - is there any solution to mount drive as specific UID/GID?
