### ISSUE TITLE
Unable to get environment variables from linked containers

### ISSUE THREAD

**Issue by ikhere** [docker/docker#25480]
I have docker-compose file with certain containers reading environment variables from ```.env``` file. 

But the linked containers are not seeing these variables at all. I'm not sure if I'm missing some step here. Any help would be appreciated.

**docker-compose.yml**
```
version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env

  redis:
    image: redis

  web:
    build: .
    command: bash -c "./runserver.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
      - redis:redis
      - rabbitmq:rabbitmq

  worker:
    build: .
    command: bash -c "./runcelery.sh"
    volumes:
      - .:/code
    links:
      - db:db
      - rabbitmq:rabbitmq
      - redis:redis
```

**List of docker containers**
```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                             NAMES
08ca06e59231        vader_worker        "bash -c ./runcelery."   11 minutes ago      Up 10 minutes                                                                                         vader_worker_1
c8aecf2511ef        vader_web           "bash -c ./runserver."   11 minutes ago      Up 10 minutes       0.0.0.0:8000->8000/tcp                                                            vader_web_1
733c2b6c670c        postgres            "/docker-entrypoint.s"   11 minutes ago      Up 10 minutes       5432/tcp                                                                          vader_db_1
6e547af9e7e4        rabbitmq            "docker-entrypoint.sh"   11 minutes ago      Up 10 minutes       4369/tcp, 0.0.0.0:5672->5672/tcp, 5671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   vader_rabbitmq_1
aa9e542f1d1a        redis               "docker-entrypoint.sh"   11 minutes ago      Up 11 minutes       6379/tcp                                                                          vader_redis_1
```

**Environment of web container**
```
$ docker exec 6c4dbd21ac09 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=6c4dbd21ac09
LANG=C.UTF-8
GPG_KEY=C01E1CAD5EA2C4F0B8E3571504C367C218ADD4FF
PYTHON_VERSION=2.7.12
PYTHON_PIP_VERSION=8.1.2
PYTHONUNBUFFERED=1
HOME=/root
```

**Environment of db container**
```
$ docker exec 733c2b6c670c env
PATH=/usr/lib/postgresql/9.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=733c2b6c670c
POSTGRES_PASSWORD=mysecretpassword
GOSU_VERSION=1.7
LANG=en_US.utf8
PG_MAJOR=9.5
PG_VERSION=9.5.3-1.pgdg80+1
PGDATA=/var/lib/postgresql/data
HOME=/root
```

**Environment of rabbitmq container**
```
$ docker exec 6e547af9e7e4 env
PATH=/usr/lib/rabbitmq/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=6e547af9e7e4
RABBITMQ_PASS=mypass
GOSU_VERSION=1.7
RABBITMQ_LOGS=-
RABBITMQ_SASL_LOGS=-
RABBITMQ_VERSION=3.6.4
RABBITMQ_DEBIAN_VERSION=3.6.4-1
HOME=/var/lib/rabbitmq
```

**Docker info and version**
```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 56
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: HKW6:3DCS:7QO4:GSCP:4EHS:LS5Y:K6S6:SBXM:SE4B:I6NB:4CH5:7RKN
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 49
 Goroutines: 106
 System Time: 2016-08-08T06:43:58.246543557Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
