### ISSUE TITLE
Not able to connect to mysql through java application in docker !!!

### ISSUE THREAD

**Issue by rg25** [docker/docker#25562]
Issue Detail
1.)  I have a java application running in a docker container.
2) Also mysql is running in another docker container.
3) I am trying to  connect the java application to mysql using this configuration -
db.driver: com.mysql.jdbc.Driver
db.url: jdbc:mysql://mysql_docker_IP:3306/Database_Name
db.username: user
db.password: password

4) However the java application docker-container is not able to connect to the mysql-container:
ERROR LOG

2016-08-10 06:36:04 WARN  JdbcServicesImpl:204 - HHH000342: Could not obtain connection to query metadata : Communications link failure
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Does anybody have an idea about what the issue is?

**Comment by thaJeztah** [comment]
This looks like a support question, and the GitHub issue tracker is not really intended for that (it's for reporting bugs and feature requests). It's hard to answer this, because there's not a lot information to go on, for example;

- how did you start the containers, with what options/flags?
- are both containers on the same docker network?
- what version of docker are you using? (output of `docker version` and `docker info`)
- is the MySQL container a custom image, or the official image from Docker Hub? Using a custom configuration file?
- how did you get mysql_docker_IP? Did the IP address change?

This question is better asked on https://forums.docker.com, so I'll close it here, but feel free to comment after

**Comment by rg25** [comment]
I am gona raise this issue on the suggested forum. 
To answer you questions, if you can provide some help:
1) sudo docker run --name mysql -p 3306:3306 -t -i mysql bash
sudo docker run --name sss -p 1112:1112 -t -i sss bash
2) both the containers are on the same network
3) docker Version: 1.11.2'
4) Using a custom mysql configuration file
5) mysql-docker-ip  was obtained by running the container and using ifconfig to get the container IP.

Please feel free to suggest any solution to connect mysql in an alternative way.

**Comment by thaJeztah** [comment]
Some things I notice;

First of all, you're starting the mysql container interactively, and overriding the default command with `bash`; doing so will result in the actual `mysql` server not being initialized and started (just `bash`). You should not run the container interactively, but `detached` (`-d`). If you need a shell in the mysql container (e.g. for debugging), use `docker exec -it mysql bash` (if the container is named `mysql`).

Also; by using `-p 3306:3306` you're publishing the MySQL port to the hosts public interface, making it publicly accessible; if you don't need that, I suggest removing the `-p` option.

I see you don't specify a `--net` option for the containers, so they're both connected to the default (`bridge`) network. If you use a custom network, you'll get the advantage of DNS based service discovery, making it easier (and reliable) to let containers communicate with each other based on their name, instead of trying to find the IP-address; the IP address of a container can change (for example, if the container is restarted), which would result in your Java app being unable to communicate.

For example, you could realize this doing;

```bash
# create a  network
docker network create my-network

# start both containers, and attach them both to the `my-network` network
# I named the mysql container `mydatabase`, just for demonstrating
docker run -d --net=my-network --name=mydatabase mysql

docker run -d --net=my-network --name=myapp myappimage
```

After this, the Java application inside the `myapp` container can connect to the mysql database using the container-name of the mysql container as hostname (`mydatabase` in the example I used above), for example:

```
db.driver: com.mysql.jdbc.Driver
db.url: jdbc:mysql://mydatabase:3306/Database_Name
db.username: user
db.password: password
```

Note that the `myapp` container can connect to port 3306 of the mysql container, because it's connecting over the internal docker "my-network" network; no need to publish the port on the host, and the mysql database is "safe" because it's not accessible from outside the docker host.

Finally; if you're using a custom configuration for you mysql database, make sure it's listening on `0.0.0.0`, and not on `127.0.0.1`, otherwise you'll only be able to connect to the database from *inside* the mysql container (`127.0.0.1` is "localhost" inside each container, not localhost on the "docker" host)

Hope this helps!

**Comment by rg25** [comment]
Thanku, theJeztah for the help, while I am trying out the above things, I have created docker-compose file through which I am running these containers:
version: '2'
services:
  mysqll:
    build:
      context: ./mysql
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
  sss:
    build:
      context: .
    container_name: sss
    image: sss
    ports:
      - "1112:1112"
      - "1114:1114"
So, my query is, there anything missing here?

**Comment by thaJeztah** [comment]
> So, my query is, there anything missing or incorrect here?

It looks like you're *building* an image for both, but tag the image built by the `mysql` service as `mysql`; that's dangerous, because you may overwrite the "official" `mysql` image locally; better give it a custom name.

Also, by setting `container_name`, the container name is *fixed*, and no longer dependent on the compose project name. Docker Compose automatically adds a network-alias for the `service` name (i.e., the container may be named `myproject_mysql`, but if the service is named `mysql`, other containers can still access it under the name of that service (`mysql`). Giving it a fixed name, may make it more complicated to run multiple instances of the same project under different names, or, multiple projects that use a `mysql` container. If not really needed, just skip it

As mentioned earlier, doing `ports: 3306:3306` publishes the mysql ports on the host, so the database is "publicly" accessible; if not needed, you could skip that

Finally; I think you have a typo in your mysql service; `mysqll:` (there's two `l`'s at the end)

**Comment by rg25** [comment]
Hi @thaJeztah ,
I tried the above things you suggested as follows:
1.) started my-sql container (detached mode) and after creating "my-network"
 sudo docker run -d --net=my-network --name=my-sql my-sql
sudo docker exec -it my-sql bash
2) started my application service (detached mode) as follows:
sudo docker run -d --net=my-network --name=uma uma
sudo docker exec -it uma bash
3) Java app inside  my service container connects to my-sql as follows
db.driver: com.mysql.jdbc.Driver
db.url: jdbc:mysql://my-sql:3306/Database_Name
db.username: user
db.password: password
3) sudo docker logs uma prints
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
Caused by: java.net.ConnectException: Connection refused

4) The service app is unable to connect to my-sql.
5) Also my-sql is listening on 0.0.0.0, which I verified using netsat -lnp|grep 3306
6) Attached is my-sql Dockerfile and shell script which I am using to create mysql image.

Please suggest what you think may be the issue here?

**Comment by rg25** [comment]
[Dockerfile.docx](https://github.com/docker/docker/files/415082/Dockerfile.docx)
[sql-setup.docx](https://github.com/docker/docker/files/415081/sql-setup.docx)

**Comment by abhishekaj** [comment]
Hi @thaJeztah ,
I have followed the way you suggested. But I am getting the same error as rg25 is getting. Can u suggest something?

**Comment by DILEEP-YADAV** [comment]
Hi! same issue here. please help anyone. I am using spring boot app with MySQL. using  docker-compose up command
**# docker images create with this cmd:**
`docker build -f src/main/docker/Dockerfile -t techlaviya .`

**# After that using docker-compose cmd**
`docker-compose up`

**# application.yml**
```
spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate
  datasource:
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        driver-class-name: com.mysql.jdbc.Driver
```
**# docker-compose.yml**

```
version: '2.1'

services:
  techlaviya-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=TechlaviyaDB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
  techlaviya:
    image: techlaviya
    depends_on:
      - techlaviya-mysql
    ports:
      - 8080:8080
    links:
         - techlaviya-mysql
    environment:
      - DATABASE_HOST=techlaviya-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=TechlaviyaDB
      - DATABASE_PORT=3306
```
**# Dockerfile**
```
FROM openjdk:8
VOLUME /tmp
ADD target/techlaviya.jar techlaviya.jar
RUN bash -c 'touch techlaviya.jar'
ENTRYPOINT ["java","-jar","techlaviya.jar"]
```

**# app.sh**
```

#!/bin/sh

MYSQL_LOOPS="10"
i=0
while ! nc $DATABASE_HOST $DATABASE_PORT >/dev/null 2>&1 < /dev/null; do
  i=`expr $i + 1`
  if [ $i -ge $MYSQL_LOOPS ]; then
    echo "$(date) - ${DATABASE_HOST}:${DATABASE_PORT} still not reachable, giving up"
    exit 1
  fi
  echo "$(date) - waiting for ${DATABASE_HOST}:${DATABASE_PORT}..."
  sleep 1
done

java  -jar techlaviya.jar
```

![capturecapture](https://user-images.githubusercontent.com/8583769/30499765-71f42b94-9a79-11e7-824d-b6f724a84244.PNG)

**Comment by bddenhartog** [comment]
Came across this due to an unrelated query... Just wanted to correct something!

@thaJeztah said:

> It looks like you're building an image for both, but tag the image built by the mysql service as mysql; that's dangerous, because you may overwrite the "official" mysql image locally; better give it a custom name.

That's actually not true, and never has been when using `docker-compose`. When an image is built in a project, the image gets the project's directory name (`$PWD` from where you ran `docker-compose`) prefixed to the image name.

As an example, if I'm in a directory `/foo/bar/baz` and run `docker-compose up` with the following service in my Dockerfile (taken example above):

```dockerfile
services:
  mysql:
    build:
      context: ./mysql
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
```
With this service definition, the service name (that top-level `mysql`) will be prefixed with the directory name (`baz`). Upon running `docker-compose up [--build]`, an image named `baz_mysql` will be built. Because this compose file _also_ specifies the `container_name` property, the container started from our `docker-compose up` command will be named `mysql`.

**Comment by gokhanayhan38** [comment]
I realize docker containers can't communicate with 127.0.0.1 so I use their container ip

    docker inspect <container_id>
then find IpAddress. Use this for DATABASE_HOST.
That solves my problem.

**Comment by thaJeztah** [comment]
@gokhanayhan38 if you `docker exec` into the container, can you ping the other container by name? There shouldn't be a need to hard-code the IP-address; inside the container you can access the other container by name.

**Comment by gokhanayhan38** [comment]
@thaJeztah I can ping with IpAddress. I tried to access the other containers by name but I couldn't. I don't know why.

**Comment by dromadaire54** [comment]
Hello everybody
I've the same problem with the springboot when it wants to connect to the mysql. I replace the container nae by the IP address in the docker-compose yaml file and it works. But, it's possible to use the container name from the springboot container I can ping the mysql container by the name. It's annoying because the IP address can change and for the docker good practice  it's better to use the conatiner name. Anyone can help please ?

**Comment by gokhanayhan38** [comment]
@thaJeztah you right solved my problem with container name

**Comment by workmanw** [comment]
Did anyone get a lead on this problem? I have it happening pretty intermittently (~25% of connections). I can use the `mysql` CLI utility perfectly fine when attached to the docker container so I don't suspect it's a network configuration issue.

**Comment by rakeshpandey19** [comment]
I am also facing similar issue, 
$ docker container ls
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                                                                                                                                    NAMES
6b9aa704c108        mysql:5.7.18            "docker-entrypoint.s…"   2 hours ago         Up 2 hours          0.0.0.0:3306->3306/tcp                                                                                                                   demo_mysql

But at local system, to connect jdbc url with localhost:3306 doesn't connect, when I try to build package at local, with 'mvn clean install -Pclean-database' I get this error

[ERROR] Failed to execute goal org.codehaus.mojo:sql-maven-plugin:1.5:execute (clean-db) on project cx6: Communications link failure
[ERROR]
[ERROR] The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.: Connection refused: connect

**Comment by mhkarimi** [comment]
I used this configuration for my docker-compose.yml and it works fine  : 
```
version: '3'

services:
  mysql-docker-container:
    image: mysql/mysql-server:latest
#    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_HOST=%
    volumes:
      - /data/mysql
  myredis:
    image: redis
    ports:
      - 6379:6379

  my-first-docker:
    restart: on-failure
    image: mhmhnew
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
      - myredis
    ports:
      - 9010:9010
    volumes:
      - /data/mhmhnew
```
