### ISSUE TITLE
Replicas stack YAML support

### ISSUE THREAD

**Issue by frimdo** [docker/docker#26148]
Stack yaml should support replicas. Example of yaml code:

```
lb:lb:
  image: dockercloud/haproxy
  ports:
    - "80:80"
  replicas: 5
```

This would be equal to:

```
docker service create -p 80:80 --name lb:lb --replicas=5 dockercloud/haproxy
```
