### ISSUE TITLE
Mount directory from other container

### ISSUE THREAD

**Issue by rprots** [docker/docker#26202]
Would like to have ability to mount directory (which has application binary in it) into container (`container1`) from other container (`container2`).

Here is `docker-compose.yml` that was tried:

```
version: '2'
services:
  container1:
    build:
      context: container1
    depends_on:
      - container2
    volumes_from:
      - container2:ro
  container2:
    build:
      context: container2
    volumes:
      - /dir_with_app
```  

But whenever binary app changes and `container2` image gets built the `container1` still sees the old binary app.
