### ISSUE TITLE
Mounted subdirectory is empty in mounted directory in Docker?

### ISSUE THREAD

**Issue by bernex** [docker/docker#26232]
I'm using this docker-compose file:

```
version: '2'

services:
    php:
        container_name: "php"
        build: ./php
        volumes:
           - ./../php:/var/www
           - ./../core:/var/www/core
```

`./../php` - does not have core dir. After starting everything is ok. But after 5 seconds `/var/www/core` is empty and I see empty core directory inside `./../php/core`.

I think container reload this empty directory(`./../php/core`) from host and ignores second volume binding(`./../core:/var/www/core`)

How use correctly? Or bug?
