### ISSUE TITLE
Cannot start service nginx: oci runtime error: caused "not a directory"

### ISSUE THREAD

**Issue by dev6** [docker/docker#26822]
**Mounting files or volumes from Linux host to container in docker-machine**

I have this user rights problem which I think is an issue with the docker itself and user rights assigned to it in Ubuntu version of Linux.
I first installed `docker engine, docker compose` and created basic Nginx, PHP containers. I used sudo privileges when creating and running these containers with no issues using `docker-compose` commands. The below error shows up when tried to up the containers without sudo privilege. But with sudo privilege, it goes just fine.

Then I had to install `docker-machine` on the same host for a different project with profiling tools in another container of the same machine. I have used docker compose for multiple containers inside default docker machine and this error shows up again. and if I use the sudo privilege to up the machines with `docker-compose`, it starts the previously created machines but not the ones from docker machine.

`ERROR: for nginx2  Cannot start service nginx2: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1/var/lib/docker/aufs/mnt/6b530a05f392226181b788163191f813676f15e093f6118428c6b8f170966dad/etc/nginx/conf.d/default.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/6b530a05f392226181b788163191f813676f15e093f6118428c6b8f170966dad" caused "not a directory"`

**Steps to reproduce the issue:**
1. Install docker engine and docker compose and create basic LEMP machines using compose with sudo privileges.
2. Install docker machine on the same host and create a new project for LEMP using compose 2 without sudo privileges.
3. Try to up the containers from docker machine both with and without sudo privileges using compose version 2.

**Additional information important:**
All other containers are created successfully without sudo privileges except nginx2 service which has a mounting file option. The composer file looks like this:

```
version: '2'

volumes:
    database_data:
        driver: local

services:
  nginx2:
      image: nginx:latest
      ports:
          #- 8080:80
          - 8000:80
      volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      volumes_from:
          - phphalcon
  phphalcon:
      #container_name: phalcon
      #image: mileschou/phalcon
      #used dockerfile from phalcon repository defined above.
      build: ./php/
      expose:
          - 9000
      volumes:
          - .:/home/arch/Projects/Imgcs/docker/app2/app
  mysql2:
      image: mysql:latest
      expose:
          - 3306
      volumes:
          - database_data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: project
          MYSQL_USER: project
          MYSQL_PASSWORD: project
```
and if I am commenting out the volumes option from the nginx2 service, the container is created successfully without any requirement of sudo privileges.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 9
 Running: 3
 Paused: 0
 Stopped: 6
Images: 9
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: MUKX:D7B5:6G3Z:KD7W:TCX3:MUEO:5DP4:ZDIA:IB6P:PPDR:EYA5:AL3S
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 42
 Goroutines: 72
 System Time: 2016-09-22T14:45:20.667103537Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

```
