### ISSUE TITLE
[window] can't mount a folder from window to container 

### ISSUE THREAD

**Issue by ducduongtmb** [docker/docker#27210]
this is **compose file** 
```
version: '2'

services:
  finsify-postgres:
    image: postgres:9.5.4
    # init database and user
    environment:
      - POSTGRES_PASSWORD=32014a0c
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-initdb/dump:/tmp/dump
      - ./postgres-initdb/scripts:/docker-entrypoint-initdb.d
    ports:
      - "3101:5432"
  finsify-redis:
    image: redis:3.2.3
    ports:
      - "3001:6379"
```

output command  : 
```
...............................................
[33mfinsify-postgres_1  |[0m waiting for server to start....LOG:  database system was shut down at 2016-10-07 04:07:24 UTC
[33mfinsify-postgres_1  |[0m LOG:  MultiXact member wraparound protections are now enabled
[33mfinsify-postgres_1  |[0m LOG:  database system is ready to accept connections
[33mfinsify-postgres_1  |[0m LOG:  autovacuum launcher started
[33mfinsify-postgres_1  |[0m  done
[33mfinsify-postgres_1  |[0m server started
[33mfinsify-postgres_1  |[0m ALTER ROLE
[33mfinsify-postgres_1  |[0m
[33mfinsify-postgres_1  |[0m
[33mfinsify-postgres_1  |[0m /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
[33mfinsify-postgres_1  |[0m
[33mfinsify-postgres_1  |[0m LOG:  received fast shutdown request
[33mfinsify-postgres_1  |[0m LOG:  aborting any active transactions
[33mfinsify-postgres_1  |[0m LOG:  autovacuum launcher shutting down
[33mfinsify-postgres_1  |[0m LOG:  shutting down
[33mfinsify-postgres_1  |[0m waiting for server to shut down....LOG:  database system is shut down
[33mfinsify-postgres_1  |[0m  done
[33mfinsify-postgres_1  |[0m server stopped
............
```

in docker-entrypoint-initdb.d , There are two bash script , they create a database and import from dump file to this database .
but it didn't work in window 10.

These script work well in MAC OS , Ubuntu , I use docker 1.12.1 .
I tried to run a other container with same config and ```exec``` to container but docker-entrypoint-initdb.d didn't include script which I written .

Thanks for help .
