### ISSUE TITLE
IPv4 forwarding fails with static IP address and compose up

### ISSUE THREAD

**Issue by reypm** [docker/docker#27319]
**Description**
I have configured my network to be static rather than DHCP at office. The content of the configuration is as follow:
```
TYPE=Ethernet
BOOTPROTO=none
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=no
IPV6_AUTOCONF=no
IPV6_DEFROUTE=no
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=enp0s31f6
ONBOOT=yes
DNS1=8.8.8.8
DNS2=8.8.4.4
IPADDR=192.168.1.66
PREFIX=24
GATEWAY=192.168.1.1
IPV6_PEERDNS=no
IPV6_PEERROUTES=no
```
Then I have tried to test a docker compose I am working on by running:
```
docker-compose up php-apache
```
Everything went fine but at some point the build stopped with this message:
> ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
I am not sure how to fix this or if I am missing something. This is the content of the `docker-compose.yml` file:
```
version: '2'
services:
    php-apache:
        env_file:
          - dev_variables.env
        build:
            context: .
            args:
                - PUID=1000
                - PGID=1000
        expose:
            - "80"
            - "9001"
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:192.168.1.66"
    volumes_source:
        image: tianon/true
        volumes:
            - ../:/var/www
    volumes_data:
        image: tianon/true
        volumes:
            - ./data/sessions:/sessions
```

I have found [this](https://github.com/docker/docker/issues/490) and [this](https://github.com/docker/docker/issues/2396) but doesn't found how to fix my issue or if there is any flag and I am missing something (although I have read [this](https://docs.docker.com/compose/compose-file/) and didn't found anything helpful)

**Steps to reproduce the issue:**
1. Clone [this repo](https://github.com/reypm/php55-dev)
2. Run `docker-compose up php-apache`

**Describe the results you received:**
The build process end with the following message:
> ---> [Warning] IPv4 forwarding is disabled. Networking will not work.

**Describe the results you expected:**
The image gets build properly

**Output of `docker version`:**
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-1844828-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 259.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 44.83 GB
 Metadata Space Used: 974.8 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.6-200.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.667 GiB
Name: rperez.dev
ID: 55JR:BLZC:AN4Q:PBVU:IGTB:XJLB:UFAF:LP2J:NCQE:LDS7:OL4H:A4DN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: IPv4 forwarding is disabled
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```
