### ISSUE TITLE
Windows container name DNS resolution issue

### ISSUE THREAD

**Issue by friism** [docker/docker#27499]
This is a tracking issue for a DNS problem with how container DNS resolution works on Windows. The problem will only manifest for some DNS configurations.

@msabansal is tracking resolution in Windows.

**Workaround**

Add this in the `Dockerfile`:

```
RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord
```

This causes the in-container Windows DNS Client to not start skipping the built-in Docker DNS server (used for resolving container names). 

**Steps to reproduce the issue:**

```
version: '2'
services:
  db:
    image: microsoft/windowsservercore
    command: powershell /c sleep 3600

  web:
    image: microsoft/windowsservercore
    command: ping db
    depends_on:
      - "db"

networks:
  default:
    external:
      name: nat
```

```
FROM microsoft/windowsservercore

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord
RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ScreenDefaultServers -Value 0 -Type DWord
# RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ScreenUnreachableServers -Value 0 -Type DWord
```

Then run `docker-compose build --no-cache` and `docker-compose up --force-recreate`.

**Describe the results you received:**

Ping doesn't work

**Describe the results you expected:**

Ping works

**Additional information you deem important (e.g. issue happens only occasionally):**

Failure depends on behavior of the hosts DNS server.

![image](https://cloud.githubusercontent.com/assets/126104/19486974/6cf9ae12-9515-11e6-8560-05330792e5f5.png)
