### ISSUE TITLE
Vagrant with Docker-compose - chown remains root:root

### ISSUE THREAD

**Issue by shahar-drvway** [docker/docker#27549]
Main issue involves 2 dockers.
First Docker: Data-docker , a directory that needs to hold files.

_Dockerfile.shared-data-dev:_
```
FROM busybox:latest

RUN mkdir -p /data/shared
RUN chown -R www-data:www-data /data/shared
RUN chmod -R 775 /data/shared

VOLUME /data/shared
```

This is then being called from docker-compose like so:
_docker-compose.yml:_
```
version: '2'
services:
 shared_data:
    build:
      context: .
      dockerfile: Dockerfile.shared-data-dev
    volumes:
      - "~/.data/shared:/data/shared"
  api:
    build:
       ....
    volumes_from:
      - "shared_data"
```

running `docker-compose up` does create and binds the volume to the vagrant, but the chown doesn't propogate which leaves it as `root:root`.

The only workaround I could have find is that if I change it manually after the directories exist.
Is this known? I've seen similar things, but none of them could have tackle this so far.
