### ISSUE TITLE
Cannot create container for service data: network www_default not found

### ISSUE THREAD

**Issue by prohonestdev** [docker/docker#27589]
#docker -compose.yml

```yaml
version: '2'

services:
  www:
    restart: always
    build: . 
    command: tail -f /dev/null
    #command: npm run dev
    env_file:
      - .env.honestdev 
    links:
      - mongo:mongo
    volumes:
      - ./:/usr/local/resly-web
      # use the node modules and bower already built with the package
      - 
      # don't track dist
      -
    volumes_from:
      - data
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - public
      - private
    depends_on:
      - mongo
  mongo:  
    image: mongo:3.3
    hostname: mongo
    volumes_from:
      - data
    ports:
      - "27017:27017"
      - "28017:28017"
    expose:
      - "27017"
      - "28017"
    command: --smallfiles --rest  --noauth
    networks:
      - private
  data:
    image: ubuntu:16.04
    command: echo 'Data Container'
    volumes:
      - /data
      - /data/db
      - /var/local

networks:
  public:
  private:
```

When run "docker-compose create", I can see above error(title).
Thanks
