### ISSUE TITLE
I cannot access to a container using localhost

### ISSUE THREAD

**Issue by vistiyos** [docker/docker#27682]
**Description**

I have a docker-composer.yml file to create the structure I need for my project. It used to work but suddenly it stops. I have tested in my Apple Macbook Pro with other version and it does not work too. I'm not using docker-machine at all.

``` yaml
version: '2'

networks:
  erp-login-network:
    external:
      name: erp-login-network
  erp-network:
    external:
      name: erp-network

services:
  erp-login:
    build: ./login
    volumes:
      - ./login:/data/www:rw
    depends_on:
      - erp-login-data-redis
      - erp-login-data-mysql
    links:
      - erp-login-data-redis
      - erp-login-data-mysql
    ports:
      - 3456:80
      - 3457:443
    networks:
      default: {}
      erp-login-network:
        aliases:
          - erp-login

  erp-login-haproxy:
    image: haproxy
    depends_on:
      - erp-login
    environment:
      - DNS_TCP_ADDR=127.0.0.1
      - DNS_TCP_PORT=53
    volumes:
      - ./erp-login/docker/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      default: {}
      erp-network:
        aliases:
          - erp-login

  erp-login-data-redis:
    image: redis

  erp-login-data-mysql:
    image: percona
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=21ju2013
    volumes:
      - ./login/docker/mysql:/docker-entrypoint-initdb.d:ro
  
  erp-kong-data-management:
    build: ./kong-data-management/docker/app
    depends_on:
      - kong
      - rabbitmq
    links:
      - kong
      - rabbitmq
    volumes:
      - ./kong-data-management:/usr/src/myapp:rw

  kong-database:
    image: mashape/cassandra
    expose:
      - 9042

  # Kong
  kong:
    build: ./kong-data-management/docker/kong
    #restart: always
    privileged: true
    links:
      - kong-database:kong-database
    ports:
      - 8000
      - 8443
      - 8001
    expose:
      - 7946
      - 7946/udp
    volumes:
      - ./kong-data-management/docker/kong/kong.conf:/etc/kong.conf:rw
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_PORT: 9042

  rabbitmq:
    image: rabbitmq
```

This is the Dockerfile for erp_login container:
```
FROM ubuntu:14.04

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# PHP 7
RUN apt-get update && apt-get install -y software-properties-common \
  && apt-add-repository ppa:ondrej/php && apt-get purge -y software-properties-common \
  && apt-get update \
  && apt-get install -y nginx-light php7.0-fpm php-xdebug php7.0-mbstring php7.0-mysql php7.0-common php7.0-cli php-pear php7.0-curl php7.0-gd php7.0-gmp php7.0-intl php7.0-imap php7.0-json php7.0-ldap php7.0-mcrypt php7.0-mysql php7.0-ps php7.0-readline php7.0-tidy php7.0-xmlrpc php7.0-xsl php7.0-bcmath supervisor openssl curl unzip zip php7.0-zip git \
  && apt-get clean \
  && apt-get autoremove -y
RUN mkdir -p /run/php
RUN sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php/7.0/fpm/php.ini
RUN echo 'fastcgi_read_timeout 7200s;' >> /etc/nginx/fastcgi_params
COPY ./docker/php/php.ini /etc/php/7.0/fpm/php.ini
COPY ./docker/php/xdebug.ini /etc/php/7.0/cli/conf.d/20-xdebug.ini
COPY ./docker/php/xdebug.ini /etc/php/7.0/fpm/conf.d/20-xdebug.ini

# Nginx
#RUN { echo 'daemon off;'; cat /etc/nginx/nginx.conf; } > /tmp/nginx.conf && mv /tmp/nginx.conf /etc/nginx/nginx.conf

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

RUN rm -v /etc/nginx/sites-available/default
ADD ./docker/default /etc/nginx/sites-available/default
COPY ./docker/supervisor.conf /etc/supervisord.conf
RUN service php7.0-fpm start

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


EXPOSE 80 443 9000
CMD ["echo", "-e \"Host github.com\n\tStrictHostKeyChecking no\n\" >> ~/.ssh/config"]

WORKDIR /data/www
CMD ["/usr/local/bin/composer", "update"]
CMD ["/usr/bin/supervisord", "-n"]
```

**Steps to reproduce the issue:**
1. Just execute docker-compose up
2. 
3.

**Describe the results you received:**
I try to access to the erp_login container through http://localhost:3456 and Chrome says that the connection was rejected

**Describe the results you expected:**
Access to the container as I used to do in the past.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 17
 Running: 6
 Paused: 0
 Stopped: 11
Images: 239
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 339
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.75 GiB
Name: victor-nwd
ID: 4BTK:AESE:5XV4:JGDD:FD4V:6VJN:76CR:EYG7:DIBT:UTWE:VGD2:Y6LP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
