### ISSUE TITLE
compose v2 creates volumes and networks with a prefix

### ISSUE THREAD

**Issue by renier** [docker/docker#27927]
**Description**

docker-compose will add a prefix to any top-level network or volume specified in the docker-compose.yml file.

**Steps to reproduce the issue:**

You can use this docker-compose.yml to reproduce the behavior:

```yaml
version: '2'
services:
  consul:
    container_name: foobar-consul0
    image: consul
    networks:
      foobar:
        ipv4_address: ${CONSUL_HOST}
    ports:
      - ${CONSUL_PORT}:${CONSUL_PORT}
    volumes:
      - "foobar-consul0:/consul/data"
    command: agent -server -bootstrap -client=0.0.0.0 -http-port=${CONSUL_PORT} -node=foobar
networks:
  foobar:
    ipam:
      config:
        - subnet: 172.25.0.0/16
volumes:
  foobar-consul0:
```

**Describe the results you received:**

A volume called `consul_foobar-consul0` and a network called `consul_foobar` are created. `consul_` is the unexpected prefix being added to the top-level network and volume.

**Describe the results you expected:**

I expected the volume and network to be created with the specified names unadultered.

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-boot2docker
Operating System: Boot2Docker 1.12.3 (TCL 7.2); HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: TCUN:EDPH:SFV5:244T:UWIP:44VJ:YCCT:FWG3:AOOM:6B3H:CNQE:NKVC
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 29
 System Time: 2016-11-01T04:02:35.186348142Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 docker-registry.danube.ibm.com:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using docker-machine on the mac.
