### ISSUE TITLE
Apache error after uploading my previous Wordpress and DB folders, w/o using Apache

### ISSUE THREAD

**Issue by ScottBu** [docker/docker#27982]
**Description**

I was working for months with Docker version 1.11.2, build b9f10c9 and Docker Compose version 1.8.0-rc1, build 9bf6bc6, everything was working fine. You will find below my docker-compose.yml, which was working without any problems.

I decided to change my server provider. First I had a lot of problems with Ubuntu 16.04 so I decided to build my new server with 14.04 like my previous one.

My DataBase folder and my Wordpress folder are copied in a directory (read conf file). I used to download them in ftp and then upload them on other servers running the same configuration, I was able to move my website super quickly. 

I have installed the latest versions of Docker and Docker Compose.

**My Problem :**

After uploading my folders, the website isn't working and I'm getting an Apache error, whereas... I'm not using Apache ? And, Apache Debian Server ? I'm on Ubuntu ?  : )

"You don't have permission to access / on this server.
Apache/2.4.10 (Debian) Server at mywebsite.com Port 80"

**Steps to reproduce the issue:**
1. Install Ubuntu 14.04, update, upgrade
2. Install Docker & Compose
3. Build containers with my compose .yml file (see below)
4. Wordpress installation is displayed on the website - Working
5. Upload my database folder and wordpress folder via ftp (well, can't really give you this :( )
6. Website not working anymore, Apache error.

**docker-compose.yml :**

```
version: '2'

services:
  https-portal:
    image: steveltn/https-portal
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - giwordpress
    environment:
      DOMAINS: "mywebsite.com -> http://giwordpress"
      STAGE: 'production'
      FORCE_RENEW: 'true'

  gidb:
    image: mysql:5.7
    volumes:
      - "./.data/gidb:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: giwpdb

  giwordpress:
    depends_on:
      - gidb
    image: wordpress:latest
    links:
      - gidb
    working_dir: "/var/www/html/"
    volumes:
      - "./.data/wordpress:/var/www/html/"
    restart: always
    environment:
      WORDPRESS_DB_HOST: gidb:3306
      WORDPRESS_DB_PASSWORD: password

```

**Describe the results you received:**
Forbidden
You don't have permission to access / on this server.
Apache/2.4.10 (Debian) Server at gamers-industry.com Port 80

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 44
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.822 GiB
Name: GamersIndustry
ID: GCOK:3GO4:YCW7:NOOY:N6LK:3HHD:IPZ6:A6HO:BWTR:OWHZ:L4OL:3TV2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
