### ISSUE TITLE
Cannot connect call api from host. 

### ISSUE THREAD

**Issue by mccormickma** [docker/docker#28123]
I'm new to docker and have started with a standard test app, Web.Api. I have added docker support in Visual Studio and when I debug the app I get back the values from the GET method http://localhost:5000/api/values. 
My problem comes from accessing the api when I am not debugging. I can see the container is running and i can run it myself by using the following compose command

```bash
docker-compose -f "C:\Users\ton\MicroserviceStateZor\src\MicroserviceStateZor\docker-compose.yml" -f "C:\Users\ton\MicroserviceStateZor\src\MicroserviceStateZor\docker-compose.dev.debug.yml" -p "microservicestatezor" up -d
```
What I cant do is access the api, http://localhost:5000/api/values doesnt work

My dockerfile is as follows:

```Dockerfile
FROM microsoft/dotnet:latest
ENTRYPOINT ["dotnet", "MicroserviceStateZor.dll"]
ARG source=.
WORKDIR /app 
EXPOSE 5000
COPY $source .
```

My docker-compose.dev.debug.yml is as follows:

```yaml
version: '2'

services:
  microservicestatezordb:
    image: postgres 
    environment:
      - POSTGRES_PASSWORD=test123!
    networks:
      - zordbwebinternalst
  microservicestatezor:
    depends_on: 
      - microservicestatezordb 
    build:
      args:
        source: obj/Docker/empty/
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - POSTGRES_DB=microservicestatezordb
      - POSTGRES_PASSWORD=test123!
    ports:
      - 5000:5000
    networks:
      - zordbwebinternalst
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
networks:
  zordbwebinternalst:
    driver: bridge
```

My docker-compose.yml file is as follows:

```yaml
version: '2'

services:
  microservicestatezordb:
    image: postgres 
    environment:
      - POSTGRES_PASSWORD=test123!
    networks:
      - zordbwebinternalst
  microservicestatezor:
    depends_on: 
      - microservicestatezordb
    image: user/microservicestatezor${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
networks:
  zordbwebinternalst:
    driver: bridge
```
