### ISSUE TITLE
Deadlock with docker-compose internal logs

### ISSUE THREAD

**Issue by presidento** [docker/docker#28236]
**Description**

It is quite easy to put docker in a deadlock-state when I use a container in docker-compose to catch logs from other containers. After that event `docker ps` does not work, only restarting the docker service helps

**Steps to reproduce the issue:**

1. Create a `docker-compose.yml` with the content pasted below
2. Start running the in an infinite loop: `while true; do docker-compose up test; done`
3. Kill all the containers repeatedly with `docker ps -aq  | xargs docker rm -f`

```yaml
version: '2'

services:
  syslog:
    image: factorish/syslog
    networks:
      test-network:
        ipv4_address: 172.19.1.1
  test:
    image: ubuntu
    command: sleep 9999d
    depends_on:
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://172.19.1.1:514"

networks:
  test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
```

**Describe the results you received:**

After 2-3 try the docker service seems to be in a deadlock state. Nothing works, even `docker ps`. It happens, when the killing step kills only 1 container (the syslog service) when the docker-compose is in starting state. 

**Describe the results you expected:**

Error messages, crash, silent death, etc. And after some *cleanup everything* it starts working. Like when I have `depends_on` setting in docker-compose, but without logging wired:

```yaml
version: '2'

services:
  syslog:
    image: factorish/syslog
  test:
    image: ubuntu
    command: sleep 9999d
    depends_on:
      - syslog
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: user-desktop
ID: YPQR:MRZG:K2KP:TNTL:4ODG:75BR:VS74:VCTL:I5U4:S3Y6:4DGB:V5I6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Output of `docker-compose version`:**

```
docker-compose version 1.8.0, build 94f7016
docker-py version: 1.9.0
CPython version: 3.5.2
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical computer. 

I created an issue here and not on Docker Compose project, because it killed the Docker service.
