### ISSUE TITLE
docker deploy with compose file not working

### ISSUE THREAD

**Issue by yashgt** [docker/docker#28582]
This is

```
[admin@gol05854 compose]$ ~/docker/docker -v
**Docker version 1.13.0-rc1, build 75fd88b**

[admin@gol05854 compose]$ ~/docker/docker -l debug deploy --compose-file docker-compose.yml e1
Ignoring unsupported options: build

Ignoring deprecated options:

expose: Exposing ports is unnecessary - services on the same network can access each other's containers on any port.

Creating network e1_mynet
**Error response from daemon: rpc error: code = 3 desc = driver name: if driver is specified name is required**
[admin@gol05854 compose]$ cat docker-compose.yml
```

```yaml
version: '3'
services:
  my_client_1:
    image: yashgt/client
    build: ../client
    #restart: on-failure:3
    volumes:
    - serverlog:/log
    depends_on:
    - my_server
    networks:
    - mynet
  my_server:
    image: yashgt/proc1
    #image: gophernet/netcat
    #command: -v -l -p 5000
    expose:
     - "5000"
    build: ../proc1
    #restart: on-failure:3
    volumes:
    - serverlog:/log
    networks:
    - mynet
volumes:
    serverlog:
         driver: local
networks:
    mynet:
        driver: overlay
```
