### ISSUE TITLE
Volumes using Docker Deploy via Compose File don't support template string

### ISSUE THREAD

**Issue by techninja1008** [docker/docker#29217]
**Description**

When trying to `docker deploy` a compose file containing a section similar to this:
```
...
    db:
        volumes:
          - db_{{.Task.Slot}}:/data
...
```

It doesn't evaluate the string as a template, and therefore states a lack of the volume.

**Steps to reproduce the issue:**
1. Save the attached compose file as docker-compose.yml
2. Run `docker deploy --compose-file docker-compose.yml my_stack`
3. See the error

**Describe the results you received:**

```
$ docker deploy --compose-file docker-compose.yml my_stack
undefined volume: es_data_{{.Task.Slot}}
```

**Describe the results you expected:**

```
Updating service my_stack_c9
Updating service my_stack_es
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Here's the compose file:
```
version: "3"

services:
    c9:
        image: tcjn/cloud9-docker
        volumes:
          - workspace:/workspace
        ports:
          - 8181:80
          - 3000:3000
    es:
        deploy:
            replicas: 3
        image: elasticsearch
        command: -Ediscovery.zen.ping.unicast.hosts="es"
        volumes:
          - es_data_{{.Task.Slot}}:/var/lib/elasticsearch
volumes:
    workspace:
    es_data_1:
    es_data_2:
    es_data_3:
```

The easiest way to fix this would be to add an option to specify mounts using the same syntax as `--mount` on `docker service create`. This could also potentially satisfy various other issues with volumes and `docker deploy` with `--compose-file`.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 06:32:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 06:32:39 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Output of `docker info`:**

```
Containers: 164
 Running: 9
 Paused: 0
 Stopped: 155
Images: 307
Server Version: 1.13.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1085
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 8agsrahzgub7m48dr66508iuv
 Is Manager: true
 ClusterID: 9l3fu4qrystn2d4h5dgly9uhc
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.2.52
 Manager Addresses:
  192.168.2.52:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56 GiB
Name: docker-x86-1
ID: NKCQ:BOL4:6JUP:BUHD:LU46:KLAQ:FDKZ:VP7I:U5FN:VYDI:OS2J:SP3K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running Ubuntu 16.04 LTS on an Intel NUC

**Lastly, why do pull requests have a field for a cute animal, whereas issues do not?**
