### ISSUE TITLE
Docker 1.13 rc4 (stack)- driver_opts not working from yaml compose file!

### ISSUE THREAD

**Issue by yogiGueta** [docker/docker#29662]
I am using Docker stack (1.13 rc4). When I am using the flowing command:
Cmd: `docker volume create --opt type=none --opt device=/my-path-on-host --opt o=bind –name try3`
everything is working fine as you can see:
cmd: “docker volume inspect try3”:

```json
[
    {
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/try3/_data",
        "Name": "try2",
        "Options": {
            "device": "/my-path-on-host ",
            "o": "bind",
            "type": "none"
        },
        "Scope": "local"
    }
]
```

But when I am using the command in yaml compose file format for docker stack like this: 

```yaml
version: '3'
volumes:
  try3:
    driver_opts:
      device: =/my-path-on-host
      o: bind
      type: none
    external: true
```

The volume try3 is created but all under driver_opts is ignored!
Cmd: “docker volume inspect try3”:

```json
[
    {
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/try3/_data",
        "Name": "try2",
        "Options": { },
        "Scope": "local"
    }
]
```
What am I doing wrong? Or it’s a docker bug? If so when do you going to fix it?
Thanks!
