### ISSUE TITLE
Unrecognized character in docker-compose.

### ISSUE THREAD

**Issue by arantessergio** [docker/docker#29753]
**Description**

Invalid character when start registrator container with docker.compose.yml

**Steps to reproduce the issue:**
1.  In docker.compose.yml add this session:
```
registrator:
    image: gliderlabs/registrator
    container_name: registrator
    network_mode: "host"
    depends_on:
      - consul
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock
    command: --ip="192.168.99.102" consul://localhost:8500
```

2. Run docker.compose.exe up -d
3. Alternatively, I commented the registrator session on `docker.compose.yml` and execute a specyfic command to registrator:
```
docker run -d \
    --name=registrator \
    --net=host \
    --volume=/var/run/docker.sock:/tmp/docker.sock \
    gliderlabs/registrator:latest \
	  --ip="192.168.99.102" \
	  consul://localhost:8500`
```
**Describe the results you received:**
1. `ERROR: for registrator  Cannot create container for service registrator: create \var\run\docker.sock: "\\var\\run\\docker.sock" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
[31mERROR[0m: Encountered errors while bringing up the project.`

**Describe the results you expected:**
3. All containers running

**Additional information you deem important (e.g. issue happens only occasionally):**
1. In a previous version it doesn't happened.

**Output of `docker version`:**

```
Docker version 1.12.5, build 7392c3b
```

**Output of `docker info`:**

```
Containers: 15
 Running: 15
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 146
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-boot2docker
Operating System: Boot2Docker 1.12.5 (TCL 7.2); HEAD : fc49b1e - Fri Dec 16 12:44:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: X5GS:KLGV:2Y6M:7ND3:EG3B:52ZR:JBP6:TBDB:TZ33:22EP:F4YZ:ITJ3
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 135
 Goroutines: 114
 System Time: 2016-12-28T12:33:31.130791192Z
 EventsListeners: 0
Username: wssim
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

Using Docker Toolbox on Windows 10.
