### ISSUE TITLE
docker 1.13.0-rc4 (stack)- error: driver name: if driver is specified name is required

### ISSUE THREAD

**Issue by yogiGueta** [docker/docker#29809]
I have the same issu like #28528 but with1.13.0-rc4:
Error response from daemon: rpc error: code = 3 desc = driver name: if driver is specified name is required.
I get the error when i'm trying to define a static IP address for a container.
**My version is:**
Client:
Version: 1.13.0-rc4
API version: 1.25
Go version: go1.7.3
Git commit: 88862e7
Built: Fri Dec 16 22:55:47 2016
OS/Arch: linux/amd64

Server:
Version: 1.13.0-rc4
API version: 1.25 (minimum version 1.12)
Go version: go1.7.3
Git commit: 88862e7
Built: Fri Dec 16 22:55:47 2016
OS/Arch: linux/amd64
Experimental: true

**My compose file is (i'm using docker stacks):**
```yaml
networks:
default_network:
driver: overlay
ipam:
config:
- subnet: 10.5.0.0/16
gateway: 10.5.0.1
```

**Comment by vdemeester** [comment]
@yogiGueta thanks for the report. I can reproduce it with the following composefile. Working on a fix

```yaml
version: "3.0"

services:
  test:
    image: busybox
    command: top
    networks: [hello]

networks:
  hello:
    driver: overlay
    ipam:
      config:
        - subnet: 172.10.0.0/16
```
