### ISSUE TITLE
Are we forgetting `docker secret update` command in cli?

### ISSUE THREAD

**Issue by realityone** [docker/docker#29882]
Hi there,

I'm trying to use docker secret to manage our private keys, but I find that we support `/secrets/<id>/update` in API,  but no `docker secret update` command in cli, even in client.

- https://github.com/docker/docker/blob/master/client/interface.go#L164
- https://github.com/docker/docker/blob/master/api/server/router/swarm/cluster.go#L50

Are we just forgetting it or it's by designed? 

I'm working on Docker 1.13.0-rc4.

**Comment by realityone** [comment]
Oh, this is by designed at https://github.com/docker/docker/blob/master/daemon/cluster/secrets.go#L109.

**Comment by thaJeztah** [comment]
I think updating is currently an API only feature; the secret (data) itself is immutable, and only "labels" can be updated.  We decided that having a `secret update` command would be more confusing than "not" having this, so (at least for now) updating through the CLI is not implemented.

Thanks for checking though, and paying attention :smile: 👍 !

**Comment by s4s0l** [comment]
Hmm, so in order to update secret the only available procedure is to remove all services using it, recreate secret and start services from scratch?

**Comment by thaJeztah** [comment]
You cannot update the secret itself, but you can update the service that's using it, and add a different secret;

```
echo foo | docker secret create secret-1 -

docker service create \
  --secret src=secret-1,target=db-password \
  --name web \
  nginx:alpine

echo foo2 | docker secret create secret-2 -

docker service update \
  --secret-rm secret-1 \
  --secret-add src=secret-2,target=db-password \
  web
```

**Comment by s4s0l** [comment]
Reasonable as not many images will support password change on the fly. Thanks.

**Comment by thaJeztah** [comment]
One of the considerations to make the secret itself immutable is to allow rolling back a service definition to a previous version. A PoC version of the feature had built-in versioning of the secret itself, but this added a lot of complexity with not a lot to gain, so if was decided to keep this out.

**Comment by kleptog** [comment]
TBH, when rolling back to a previous service definition it doesn't seem at all unreasonable to get the new version of the secret. After all, the secret (generally) gives access to a resource outside the swarm, and that is not being rolled back.

Not having an update command is also annoying when you are deploying your infrastructure via ansible. It means that password rollover will never happen because you can't reliably script everything that needs to be updated.

Interestingly, "docker stack" does have all the necessary info to rebuild the system, but it would be weird if docker stack changed the name of the secret for you.

This is one of those situations where I wish docker would give you just a bit more rope.

**Comment by RehanSaeed** [comment]
> You cannot update the secret itself, but you can update the service that's using it, and add a different secret;

That seems suboptimal. I expected to see an update command too. It would be nice if the secret was updated in running containers too but I'd settle for having to redploy a service if I could get my hands on this feature.

Can we consider re-opening this issue?

**Comment by vizv** [comment]
And it's quite annoying change compose file every time when updating a config or secret.

**Comment by MLescaudron** [comment]
I don't understand why the command is unavailable because of UpdatedAt field : 
```
[
    {
        "ID": "l2qnmoxtlopsgij9ayu4pgbsj",
        "Version": {
            "Index": 47914
        },
        "CreatedAt": "2017-09-20T03:46:16.035020938Z",
        "UpdatedAt": "2017-09-20T03:46:16.035020938Z",
        "Spec": {
            "Name": "test_1",
            "Labels": {}
        }
    }
]
```

So, while waiting, I created a script that allows to do it easily.
It updates all services using the secret.
If this interests you : https://gist.github.com/MLescaudron/e8248d32d3a5b8caaf622c1a829cf067

**Comment by rgardam** [comment]
Also this is quite painful as you cant use variables in the docker-compose file for secret versions.

**Comment by stevelacy** [comment]
As a workaround for using `docker stack deploy` (which would need to be modified for the new secret name) I am using this script to update a swarm wide secret.
It does have the issue of two `docker service update` rolls.

https://github.com/stevelacy/docker-secret-update

**Comment by ilyasotkov** [comment]
Follow this issue <https://github.com/docker/cli/issues/667> and pull request <https://github.com/docker/cli/pull/668>, which will add a "name" field to both configs and secrets. It will allow updates via environmental variables like so:
```yaml
version: "3.5" # future Compose file version

secrets:
  my-secret:
    name: my-secret-${VERSION} # name of the Docker Secret with variable interpolation
    file: ./secret.html

configs:
  my-config:
    name: my-config-${VERSION} # same thing for configs
    file: ./default.conf

services:
  web:
    image: nginx:1.13.6-alpine
    ports:
      - "80:80"
    secrets:
      - source: my-secret # reference by the name of the key, consistent with how it is for volumes now in 3.4
        target: /usr/share/nginx/html/index.html
    configs:
      - source: my-config # same thing for configs
        target: /etc/nginx/conf.d/default.conf
```

**Comment by yangm97** [comment]
So, the solution is adding arbitrary names to secrets? Why not do it like environment variables management? How do I remove orphaned secrets?

**Comment by immerrr** [comment]
> Updating is currently an API only feature; the secret (data) itself is immutable, and only "labels" can be updated.

Ok, but the problem is that the labels cannot be updated without hipping through the hoops of finding all services that use that specific secret label, unlinking them manually and then doing the `rm; create`. 

Making secrets immutable is a nice feature, so why don't do it the Git way? I mean, you already do it with images and their hashes, where each image is uniquely identified with a hash, but you can also add a human-readable tag and then it will be resolved upon container creation. Then you are free to push a new image and update the tag, but the old image is still there referenceable by its hash until it's garbage-collected.  @thaJeztah, was there a reason why the same approach was unapplicable for secrets?

**Comment by thaJeztah** [comment]
@immerrr see some of my comments in https://github.com/moby/moby/issues/35048#issuecomment-333778750 (with a possible approach)

**Comment by dlibanori** [comment]
It is very frustrating to manage secrets this way :(

I would love to have my secrets versioned, just update it and docker relaunches my services, just rollback it and docker gets my previous secret.

**Comment by timrazik** [comment]
I know this is an older thread but as someone who manages a large number of secrets, I have a suggestion here.  If you want to change a secret with minimal to no impact you can create credentials that work in parallel. This comes in handy if you want to expire credentials periodically to meet security compliance or close gaps in cases where people change teams or leave your organization.  Let's take an example of a database ID and Password.  What we can do is actually create TWO sets of credentials with the same security permissions.  

```
database:  myDockerDB
userId_A:    appUserID_A
password_A:  some_password#1234
userId_B:  appUserID_B     // This User would be INACTIVE for now.
password_B:  some_other_password#9876

```
In our docker stack/compose file we would then map our secrets as such

```
services:
  myService :
    image: dtr.docker.com/mycompany/dockerService:1.0.0
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:-TieredCompilation -XX:+ParallelRefProcEnabled
    deploy:
      mode: global
    networks:
      - bridge
    configs:
    secrets:
      - mode: 444
        source: userId_A
        target: userId
      - mode: 444
        source: password_A
        target: password

```

Now here comes the fun part.  When we want to change the password, what you do is have your DBA ACTIVATE userId_B and you set your password for it.  BOTH userId_A and userId_B would be active for an overlap (say 7 days).

You would then just update your stack file or service update to map the B credentials.  This would be allowed because no service is utilizing B.  The beauty here is that no code change is required as you are not changing the key that the code is using to look up the credentials. Now you can roll through your service(s) during the overlap period.  Once complete you have your administrator deactivate the old account so that it can no longer be used.

```
services:
  myService :
    image: dtr.docker.com/mycompany/dockerService:1.0.0
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:-TieredCompilation -XX:+ParallelRefProcEnabled
    deploy:
      mode: global
    networks:
      - bridge
    configs:
    secrets:
      - mode: 444
        source: userId_B
        target: userId
      - mode: 444
        source: password_B
        target: password

```
