### ISSUE TITLE
Deploying a stack from compose file does no variable substitution

### ISSUE THREAD

**Issue by tevjef** [docker/docker#30175]
Docker 1.13 will allow users to define a stack with a compose file with `docker stack deploy -c docker-compose.yml <stack>` . 

If the compose file contains any variables they will not be substituted.

.env
```
SOME_ENV=myenv
```
docker-compose.yml
```
version: '3'
services:
   redis:
     image: redis
     environment:
       SOME_ENV: ${SOME_ENV}
```

`docker inspect -f '{{.Config.Env}}' $CONTAINER_ID`
```
[SOME_ENV= ]
```
