### ISSUE TITLE
`docker stack deploy` errors with volume labels in compose v3 yaml

### ISSUE THREAD

**Issue by jlhawn** [docker/docker#30297]
**Description**

`docker stack deploy` doesn't like it when you give it a compose yaml file which tries to add labels to a volume:

```yaml
...
volumes:
  vol1:
    driver: local
    labels:
      com.docker.ucp.access.label: test
```

Error: `labels Additional property labels is not allowed`

**Steps to reproduce the issue:**
1. Create a compose file which tries to specify volume labels.
2. Try to deploy the stack
3. See the error that results

**Describe the results you received:**

An error message: `labels Additional property labels is not allowed`

**Describe the results you expected:**

I expected it to deploy the services, networks, and volumes in the stack with no issue.

Docker 1.13.0
