### ISSUE TITLE
Service network alias not working for services created using stack deploy on 1.13

### ISSUE THREAD

**Issue by byrnedo** [docker/docker#30313]
**Description**

When creating a stack using `docker stack deploy --compose-file=./docker-compose.yml`  I am not able to resolve the alias as a hostname from within the network.

Docker compose file:
```
version: "3"
services:
    elasticsearch:
        image: elasticsearch:2
        command: elasticsearch -Des.network.host=0.0.0.0
        networks:
            default:
                aliases: 
                    - elasticsearch.service.acme
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.role.tools==true
        healthcheck:
            test: "/usr/bin/curl --silent --fail -o /dev/null -w %{http_code} http://localhost:9200 || exit 1"
            interval: 30s
            timeout: 10s
            retries: 3
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
    logstash:
        image: logstash:2
        command: logstash -f /etc/logstash/conf.d/logstash.conf
        networks:
            default:
                aliases: 
                    - logstash.service.acme
        depends_on: 
            - elasticsearch
        ports: 
            - "12001:12001/udp"
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.role.tools==true
        healthcheck:
            test: "/bin/nc -z -w3 localhost 5000 || exit 1"
            interval: 30s
            timeout: 10s
            retries: 3

networks:
    default:
        driver: overlay

volumes:
    elasticsearch: 
        driver: local

```

Service Inspect ouput:

```
[
    {
        "ID": "1wrccq7kgzn6ztjgwonuyirfk",
        "Version": {
            "Index": 5621
        },
        "CreatedAt": "2017-01-20T13:00:09.007260649Z",
        "UpdatedAt": "2017-01-20T13:00:09.008047248Z",
        "Spec": {
            "Name": "test_elasticsearch",
            "Labels": {
                "com.docker.stack.namespace": "test"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "elasticsearch:2@sha256:0b0b493c0ad7c0af88bcecc2060f8e16feea1713c908570ab9872fe8ada919ca",
                    "Labels": {
                        "com.docker.stack.namespace": "test"
                    },
                    "Args": [
                        "elasticsearch",
                        "-Des.network.host=0.0.0.0"
                    ],
                    "Mounts": [
                        {
                            "Type": "volume",
                            "Source": "test_elasticsearch",
                            "Target": "/usr/share/elasticsearch/data",
                            "VolumeOptions": {
                                "Labels": {
                                    "com.docker.stack.namespace": "test"
                                },
                                "DriverConfig": {
                                    "Name": "local"
                                }
                            }
                        }
                    ],
                    "Healthcheck": {
                        "Test": [
                            "CMD-SHELL",
                            "/usr/bin/curl --silent --fail -o /dev/null -w %{http_code} http://localhost:9200 || exit 1"
                        ],
                        "Interval": 30000000000,
                        "Timeout": 10000000000,
                        "Retries": 3
                    }
                },
                "Resources": {},
                "Placement": {
                    "Constraints": [
                        "node.labels.role.tools==true"
                    ]
                },
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "Networks": [
                {
                    "Target": "wmto6bxovgfv3fuxz5r2ql862",
                    "Aliases": [
                        "elasticsearch.service.acme",
                        "elasticsearch"
                    ]
                }
            ],
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip"
            },
            "VirtualIPs": [
                {
                    "NetworkID": "wmto6bxovgfv3fuxz5r2ql862",
                    "Addr": "10.0.1.13/24"
                }
            ]
        },
        "UpdateStatus": {
            "StartedAt": "0001-01-01T00:00:00Z",
            "CompletedAt": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Steps to reproduce the issue:**
1. Run the stack from a docker-compose file as above (assigning a network alias)
2. Use ping to check hostnames

**Describe the results you received:**
```
root@logstash:/# ping test_elasticsearch
PING test_elasticsearch (10.0.1.15): 56 data bytes
64 bytes from 10.0.1.15: icmp_seq=0 ttl=64 time=0.142 ms
64 bytes from 10.0.1.15: icmp_seq=1 ttl=64 time=0.189 ms
64 bytes from 10.0.1.15: icmp_seq=2 ttl=64 time=0.105 ms

root@logstash:/# ping elasticsearch
ping: unknown host

root@logstash:/# ping elasticsearch.service.acme
ping: unknown host
```

**Describe the results you expected:**

All 3 above dns names to work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 10:05:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**
Of manager
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: nf60k2co676qt6s8rykklvqv5
 Is Manager: true
 ClusterID: mae52778wpstynpij553uji54
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.100
 Manager Addresses:
  192.168.99.100:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.43-boot2docker
Operating System: Boot2Docker 1.13.0 (TCL 7.2); HEAD : 5b8d9cb - Wed Jan 18 18:50:40 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: swnode1
ID: S5C6:YG6T:SBP3:HS3K:5T7P:HHT4:DABN:3QVO:JPXH:6Z6G:NKKA:DC2Q
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 43
 Goroutines: 187
 System Time: 2017-01-20T13:14:04.088855925Z
 EventsListeners: 0
Username: byrnedo
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using docker-machine virtualbox driver and swarm mode.

**Comment by thaJeztah** [comment]
ping @dnephin @vdemeester ptal 

fwiw, `--network-alias` is not yet supported on `docker service create`, but perhaps the API supports it (https://github.com/docker/docker/issues/24787)

**Comment by dnephin** [comment]
The inspect looks correct (the alias is there), which means the error is in swarmkit (or possibly in the docker engine API). The client (`stack deploy`) is setting things up correctly.

**Comment by zarbis** [comment]
@thaJeztah I was about to open issue about unexpected results with:
`docker service create --hostname="{{.Service.Name}}.{{.Task.Slot}}"`
where change in hostnames is not reflected in DNS records, but after some RTFM i get that there are 3 separate entities:

1. container name
2. container's hostname
3. container's DNS record

I expected that DNS record would "mimic" changes in hostname pattern.
Can you clarify if I have wrong expectations or is it a legit issue and I should open a new one?

**Comment by thaJeztah** [comment]
@zarbis that's the expected behavior; `--hostname` is local to the container, so only specifies the hostname _inside_ the container. Hostname is not used for container discovery, so changing the hostname does not register it under that name in the DNS.

Hostname _does_ add an entry to the container's `/etc/hosts`

**Comment by hamburml** [comment]
I have the same problem. My swarm currently consists of two root server. Both debian 8.7 with updates kernel from jessie-backports and docker 1.13.0.

I created a network called proxy with `--attachable --opt encrypted --driver overlay `and a service via `docker service create --name proxy .... --constraint ... --network proxy`.

I also used a stack file which creates other services. 

```
Server A:
  Service:
  - proxy
  - basic_portainer

Server B:
  - basic_swarm-listener
```

I used docker exec to get access to the running proxy container. I tried to ping basic_portainer, portainer and basic_swarm-listener and swarm-listener. I found out that I can in fact ping basic_portainer and portainer. But I can't ping the basic_swarm-listener and swarm-listener container running on Server B.
Does the network alias currently only work on the same host machine?

**Comment by s4s0l** [comment]
Not sure if it is a right place to mention my problem because there is a lot of issues related (https://github.com/docker/swarmkit/issues/1242, https://github.com/docker/docker/issues/27080, https://github.com/docker/docker/issues/30447, so on). But it would be nice if there existed any way of reaching container(task) from other service on the same network ON THE SAME NODE. 
Use case: running a log agregator on each node as a global service, all other services do not need to use routing mesh to talk to it as it would cause substantial network traffic.

I think it would be very elegant and powerful to allow temples in alias names:
```networks:
            default:
                aliases: 
                    - "{{.Node.ID}}-serviceName"
```
then in other services we could provide environment variable pointing to DNS name of that service in exactly the same form ("{{.Node.ID}}-serviceName"). This would also solve a lot of other requirements regarding DNS. Everybody has a slightly different preferences, but this way most of them would be fulfilled.

**Comment by byrnedo** [comment]
Anyone know when this issue might be fixed? By 1.13.2 (if there is one) or by 1.14?

**Comment by vdemeester** [comment]
@byrnedo could you try with `v1.13.1` because I can't reproduce with it, it works for me :sweat: 

```
/ # ping elasticsearch
PING elasticsearch (10.0.1.2): 56 data bytes
64 bytes from 10.0.1.2: seq=0 ttl=64 time=0.460 ms
64 bytes from 10.0.1.2: seq=1 ttl=64 time=0.151 ms
^C
--- elasticsearch ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.151/0.305/0.460 ms
/ # ping test_elasticsearch
PING test_elasticsearch (10.0.1.2): 56 data bytes
64 bytes from 10.0.1.2: seq=0 ttl=64 time=0.239 ms
^C
--- test_elasticsearch ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.239/0.239/0.239 ms
/ # ping elasticsearch.service.acme
PING elasticsearch.service.acme (10.0.1.2): 56 data bytes
64 bytes from 10.0.1.2: seq=0 ttl=64 time=0.144 ms
64 bytes from 10.0.1.2: seq=1 ttl=64 time=0.213 ms
^C
--- elasticsearch.service.acme ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.144/0.178/0.213 ms
```

It also might be a network problem. What is your operating system ? is `filerwalld` (or any type of firewall enabled — in this case, which one ?) enabled ? …

/cc @mavenugo @aboch

**Comment by byrnedo** [comment]
I'm running ubuntu 16.10 and I have no firewall. 
I'll give it a go asap with 1.13.1!

**Comment by wangshao** [comment]
same problem here. Using docker stack deploy for multi-host with docker 1.13.1  None of service aliases worked for me, including servicename,  stackname+servicename, servicename...

**Comment by theecodedragon** [comment]
I can confirm that the following format works & has resolved a big pain for me with dns 


```
version: "3"

services:
  webService:
    image: xyz
    ports:
      - 8080
    restart: unless-stopped
    networks:
      platform:
       	aliases:
          - web
          - web.service.works
```


So incase you are deploying the stack with as followed : 

`docker stack deploy -c  network-alias.yml webstack`

Your service should be resolvable as with the following dns:

1) webstack_webservice
2) web
3) web.service.works

**Comment by byrnedo** [comment]
@theecodedragon What's the difference that makes this work?

**Comment by cirocosta** [comment]
hey @theecodedragon @byrnedo, just tried here and having 

```yaml
version: '3.2'  
services:
  webService:
    image: nginx:alpine
    ports:
      - 80
    restart: unless-stopped
    networks:
      platform:
        aliases:
          - web
          - web.service.works
    deploy:
      replicas: 2

networks:
  platform:
```

and issuing

```
docker stack deploy -c ./test.yml teststack
```

you can inspect: `docker inspect teststack_webService`
where you can see:

```
            "Networks": [
                {
                    "Target": "y87javnzaod6jtpbmf31oqcbq",
                    "Aliases": [
                        "web",
                        "web.service.works",
                        "webService"
                    ]
                }
            ],
```

you can then `exec` into one of the containers and check:

```
ciro@dev1:/tmp$ docker ps  
CONTAINER ID        IMAGE                NAMES
fb9cab934162        nginx:alpine         teststack_webService.2.z69xfmcj923fm40w4ur89qcvv
a4b9d2791006        nginx:alpine         teststack_webService.1.wut9xu6wqu4o6f8wxintteu1r
ciro@dev1:/tmp$ docker exec fb9cab934162 ping web
PING web (10.0.1.2): 56 data bytes
64 bytes from 10.0.1.2: seq=0 ttl=64 time=0.071 ms
64 bytes from 10.0.1.2: seq=1 ttl=64 time=0.063 ms
^C
ciro@wedeploy-dev:/tmp$ docker exec fb9cab934162 ping web.service.works
PING web.service.works (10.0.1.2): 56 data bytes
64 bytes from 10.0.1.2: seq=0 ttl=64 time=0.061 ms
^C
ciro@dev1:/tmp$ docker exec fb9cab934162 ping webService
PING webService (10.0.1.2): 56 data bytes
64 bytes from 10.0.1.2: seq=0 ttl=64 time=0.086 ms
64 bytes from 10.0.1.2: seq=1 ttl=64 time=0.081 ms
```

does that fit what you expect?
