### ISSUE TITLE
docker swarm mode - can't reach containers by link alias

### ISSUE THREAD

**Issue by fer2d2** [docker/docker#30362]
Hi,

I have the following docker-compose file, deployed with `docker swam deploy --compose-file` to a swam cluster using **Docker version 1.13.0, build 49bf474**:

```yml
version: '3'
services:
  ### SERVER LAYER ###
  nginx:
    hostname: "nginx"
    domainname: "docker"
    container_name: "mtc_nginx"
    image: radmas/mtc-plus-nginx
    restart: always
    networks:
      - server
    depends_on:
      - fpm
    links:
      - "fpm:fpm.docker"
    expose:
      - "80"
      - "443"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    deploy:
      placement:
        constraints: [node.hostname == mtc-plus-prod-balancer]

  ### APPLICATION LAYER ###
  fpm:
    image: radmas/mtc-plus-fpm
    restart: always
    container_name: "mtc_fpm"
    hostname: "fpm"
    domainname: "docker"
    restart: always
    networks:
      - server
      - application
      - data
    expose:
      - "9000"
    deploy:
      placement:
        constraints: [node.hostname == mtc-plus-prod-applications]

networks:
  server:
    driver: overlay
  application:
    driver: overlay
  data:
    driver: overlay
```

From inside the NGINX container, I can reach the FPM container using `fpm` as hostname, but `fpm.docker` is not valid:

```sh
root@nginx:/# ping fpm.docker
ping: unknown host

root@nginx:/# ping fpm
PING fpm (10.0.0.4): 56 data bytes
64 bytes from 10.0.0.4: icmp_seq=0 ttl=64 time=0.055 ms
64 bytes from 10.0.0.4: icmp_seq=1 ttl=64 time=0.060 ms
64 bytes from 10.0.0.4: icmp_seq=2 ttl=64 time=0.060 ms
```

Is this the expected behaviour?

**Comment by justincormack** [comment]
I don't think that `links` will ever be supported in bundles, no. They are already deprecated, they were introduced before overlay networks and DNS naming, and we would not recommend using them at all now.

**Comment by thaJeztah** [comment]
@justincormack there's a slight difference between "legacy" links (which created an actual "link"), and `--link` in user-defined networks, which create a container-scoped network alias. The last one is not deprecated

**Comment by justincormack** [comment]
@thaJeztah oh. Ignore me then... I guess it might be fixed cc @dnephin

**Comment by dnephin** [comment]
When you run `docker stack deploy` you should see 

```
Ignoring unsupported options: links
```

Links (container-to-container alaises) are not supported by swarm mode.

**Comment by jmcalvar** [comment]
Hi, 

I got a working stack:

```version: "3"

services:`

 mariadb:
   image: registry:5000/mariadb
   networks:
      - "netblog"
   volumes:
      - ./data:/var/lib/mysql
      #- ./dump:/docker-entrypoint-initdb.d
   environment:
      MYSQL_ROOT_PASSWORD: mipass
      MYSQL_DATABASE: blog
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: mipass
   deploy:
      placement:
        constraints: [node.role == manager]

 fpm:
   image: bitnami/php-fpm:5.6.18-0
   networks:
      - "netblog"
   volumes:
     - ./web/html:/app
   ports:
     - 9000:9000

 minginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - "netblog"
    depends_on:
      - mariadb
    deploy:
      mode: replicated
      replicas: 6
      labels: [APP=HTTP]
      placement:
        constraints: [node.role == manager]
    volumes:
 - ./web/nginx/certificados:/etc/nginx/certificados
      - ./web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/nginx/conf.d/fastcgi.conf:/etc/nginx/fastcgi.conf
    links:

      - fpm

networks:
  netblog:
volumes:
  data:
```

What I don't know is if with links, containers are using overlay network or they are directly linked only jailed in the same host.

When I run the stack I see warnings about links option unsupported, but if I comment the line, nginx logs say that it can't find fpm:

``` 2017/01/31 08:53:48 [emerg] 1#1: host not found in upstream "fpm" in /etc/nginx/conf.d/default.conf:54
nginx: [emerg] host not found in upstream "fpm" in /etc/nginx/conf.d/default.conf:54
```

**Comment by simdrouin** [comment]
Did you find any working solution for your nginx to recognize your fpm service through its name?

**Comment by jmcalvar** [comment]
I didn't investigate any more because I was testing environments from normal vm to docker, but really if I didn't define network in compose, I was able to see that with default network containers can reach eath other with the name

**Comment by fer2d2** [comment]
Hi @simdrouin @jmcalvar 

Finally I found a workaround for Docker Swarm-Mode. You must use network-level aliases. Here is an example:

```yaml
  elasticsearch:
    image: radmas/mtc-plus-elasticsearch
    volumes:
      - ./persistent-data/elasticsearch:/usr/share/elasticsearch/data
      - ./persistent-data/elasticsearch-backups:/backups
    command: elasticsearch --default.path.repo=/backups
    networks:
      data:
        aliases:
          - elasticsearch.docker
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.129.26.80:5514"
        tag: "docker[elasticsearch]"
    deploy:
      placement:
        constraints: [node.labels.purpose == extra-data]
```

With this setup, any container in the *data* network can reach the ElasticSearch container using its network alias "elasticsearch.docker". Please note that "elasticsearch.docker" is a "service" DNS, not a container name, and, if you scale your service, your requests to elasticsearch.docker will be load-balanced.
