### ISSUE TITLE
Docker stack file (version 3): Run service on every docker host inside the swarm

### ISSUE THREAD

**Issue by hamburml** [docker/docker#30419]
**Description**

Docker 1.13 is lovely so far! Currently I create stack files (yml v3) to easily start my swarm. For monitoring I use zabbix and portainer. For zabbix I use a network called `zabbix-monitoring` and services which zabbix needs (database, web-ui, ...). Now every docker host which should be monitored via zabbix must run a zabbix-agent (https://hub.docker.com/r/zabbix/zabbix-agent/). The agent sends statistics (ram, cpu, traffic, ...) to the zabbix-server and needs the `--privileged` flag.

Normally I run the zabbix-agent like that (the network has `--attachable`).

```
docker run -d \
   --name zabbix-agent-bottle \
   --network zabbix-network \
   --env ZBX_HOSTNAME="bottle" \
   --env ZBX_SERVER_HOST="zabbix-server" \
   --privileged \
   zabbix/zabbix-agent:alpine-3.2-latest
```

Now I would like to have a way to say in a yml file that this service should run once on every docker host inside the swarm. Something like...

  ```
zabbix-agent:
    image: zabbix/zabbix-agent:alpine-3.2-latest
    networks:
      - zabbix-network
    environment:
      - ZBX_HOSTNAME=<docker hostname>
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="0815rootpw!"
    deploy:
      privileged: true
      replicas: 1
      mode: onceperhost
      placement:
        constraints: [node.hostname == basic-sf-mon-ps, node.role == manager]
```

`privileged: true` and `mode: onceperhost` do not exist.

As far as I know privileged is ignored when deploying to a swarm.

https://docs.docker.com/compose/compose-file/#cpushares-cpuquota-cpuset-domainname-hostname-ipc-macaddress-memlimit-memswaplimit-oomscoreadj-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir

Would love to see this added :)

**Comment by dnephin** [comment]
To run once per host use:
```
deploy:
  mode: global
```

#24862 is the issue for adding privileged. Once it's added to swarm mode it should be added to both the CLI and the Compose file.

**Comment by dnephin** [comment]
I believe these feature are either implemented or tracked in other issues, so I'm going to close this one. Please do comment if you believe there are issues or features not already captured.

**Comment by hamburml** [comment]
@dnephin You are right. I haven't seen `mode: global` before, sorry. But it looks like I can't use this solution because every zabbix-agent needs it's own unique name. With `mode: global` there are as many services as nodes which are all namend the same (I presume load-balancing is used). When using the zabbix-gui you need to add the zabbix-agents one by one via ip or dns-name. Normally I have `zabbix-agent-<hostname>` where <hostname> is the name of the docker host. But that's not working anymore.

Looks like I need a different solution because I need the --privileged. Thanks for helping :)

**Comment by dnephin** [comment]
There should be a way to get a unique hostname for each instance, but I can't recall offhand of it's the container id or the task id.

swarmkit also has support for setting some things based on a template. I'm not sure if discoverable name is one of those yet, but maybe it could be.

**Comment by thaJeztah** [comment]
From a container on the same network, you can `nslookup tasks.<service-name>` to get the names and ip-addresses of all tasks backing the service; see https://docs.docker.com/engine/swarm/networking/#/use-swarm-mode-service-discovery

**Comment by hamburml** [comment]
@dnephin A hostname based on a template would be lovely. Hostnames based on the service name and appenden the hostname of the host would be perfect. For example:

Server A: Hostname: DE-A
Server B: Hostname: DE-B
Server C: Hostname: UK-A

The service is named service-monitoring with mode: global and the instances on Server A, B and C are namend service-monitoring-DE-A, service-monitoring-DE-B and service-monitoring-UK-A.

@thaJeztah Thanks but I need a solution where the names are always the same no matter how often I recreate the swarm.

**Comment by thaJeztah** [comment]
Keep in mind that Hostname for a service does not set the DNS name, hostname is local to the container, so that won't help if you want to use that hostname to connect to  the container.

**Comment by hamburml** [comment]
@thaJeztah You are right. Aliases should be the way I could use for that.

**Comment by thaJeztah** [comment]
There is an issue tracking that; https://github.com/docker/docker/issues/24787 _However_ it may be worth commenting on the issue, because that issue will most likely be for implementing `--network-alias` for a _service_, but what's needed in this case, is also an option to set an alias for individual tasks; this will need a proper design, because that will probably only work with templating

**Comment by si-harps** [comment]
I have a vaguely related issue, so thought I should probably continue this thread. I'm attempting to deploy a SolrCloud setup using docker swarm. I need to set the hostname of each globally deployed service so that i can maintain the network between restarts (its a zookeeper ensemble). The hostname also needs to be unique as I am running an overlay network for comms.

Ideally i would like to use the swarm node name or id so i have set my docker-compose.yml to look similar to this...

```
solr:
        image: solr
        hostname: solr-{{.Node}}
        ports:
            - 8983:8983
        networks:
            - zoonet
        volumes:
            - ./opt/solr/logs:/opt/logs
            - ./opt/solr/store:/store
            - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_HOST: solr-{{.Node}}
            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            SOLR_LOGS_DIR: /opt/logs
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
```

However, the service is being named solr-{nodeID} (with braces) rather than solr-nodeID (without the braces). Any advice would be greatly appreciated.

Many thanks

**Comment by thaJeztah** [comment]
`{{.Node}}` is not a valid option; you're looking for `{{.Node.ID}}`, see  [Create services using templates](https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates)

```yaml
version: '3'
services:
  test:
    image: nginx:alpine
    hostname: test-{{.Node.ID}}
```

Now deploy a stack;

```bash
docker stack deploy -c docker-compose.yml foo
```

And inspect one of the containers of the `test` service (the node ID is `drfinwj2um6lv0pbprh0gzzfm` in this case):

```bash
$ docker inspect 4e97ffa5ec71 --format '{{.Config.Hostname}}'
test-drfinwj2um6lv0pbprh0gzzfm
```

However, following your description, I suspect this may not be what you're looking for: `hostname` is local to the container; in other words, that hostname is _only_ set _inside_ the container, and not used for DNS resolution. Other containers/services won't be able to use the hostname to find the container, because DNS resolution is based on the _name_ of the container (for individual tasks), and the _name_ of the service, not the hostname. See this pull request in libnetwork; https://github.com/docker/libnetwork/pull/1855, and these issues https://github.com/moby/moby/issues/34239, https://github.com/docker/swarmkit/issues/2325, and https://github.com/docker/swarmkit/issues/1242

The last one (https://github.com/docker/swarmkit/issues/1242) is the one that has to be discussed first.

**Comment by si-harps** [comment]
Thanks for your quick response. You're spot on, .Node.ID is what i was looking for and also not! My issue is that i either need to set the DNS hostname of a service or preserve the internal IP between container start/stops otherwise the zookeeper ensemble loses persisted data upon restart.

Is there any way i can uniquely name a **globally deployed service** to accomplish my goal? Please see below for full docker-compose.yml...

```
version: '3'
services:
    zoo-1:
        image: zookeeper
        ports:
            - 2181:2181
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo-2:2888:3888 server.3=zoo-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            replicas: 1
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm1]
    zoo-2:
        image: zookeeper
        ports:
            - 2182:2182
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 2
            ZOO_PORT: 2182
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo-3:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm2]
    zoo-3:
        image: zookeeper
        ports:
            - 2183:2183
        networks:
            - zoonet
        volumes:
            - ./opt/zookeeper:/opt/persist
        environment:
            ZOO_MY_ID: 3
            ZOO_PORT: 2183
            ZOO_SERVERS: server.1=zoo-1:2888:3888 server.2=zoo-2:2888:3888 server.3=0.0.0.0:2888:3888
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_LOG_DIR: /opt/persist/data
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
            placement:
                constraints: [node.hostname == vm3]
    solr:
        image: solr
        hostname: solr-{{.Node.ID}}
        ports:
            - 8983:8983
        networks:
            - zoonet
        volumes:
            - ./opt/solr/logs:/opt/logs
            - ./opt/solr/store:/store
            - ./opt/solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            SOLR_HOST: solr-{{.Node.ID}}
            SOLR_HOME: /store/solr
            ZK_HOST: zoo-1:2181,zoo-2:2182,zoo-3:2183
            SOLR_LOGS_DIR: /opt/logs
        depends_on:
            - zoo-1
            - zoo-2
            - zoo-3
        deploy:
            mode: global
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
            restart_policy:
                condition: any
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - zoonet
networks:
    zoonet:
        driver: overlay
        ipam:
            driver: default
            config:
                - subnet: 10.101.0.0/16
```

Many thanks in advance for any assistance you are able to supply.
