### ISSUE TITLE
error on macvlan mode to passthru 

### ISSUE THREAD

**Issue by aaronfeng** [docker/docker#30490]
I'm trying to figure out how to setup macvlan passthru correctly via docker-compose.  I'm receiving the following error during docker-compose up.

```
ERROR: for myapp  Cannot start service myapp: failed to create the macvlan port: invalid argument
```

Inside docker-compose.yml

```
networks:
  mynet:
    driver: macvlan
    driver_opts:
      parent: "em3"
      macvlan_mode: "passthru"
```

docker version: 1.12.6
