### ISSUE TITLE
Not all ENV are set with docker deploy

### ISSUE THREAD

**Issue by mrmunch** [docker/docker#30670]
I already asked [here](https://github.com/docker/swarmkit/issues/1911#issuecomment-276822560), but was being told to move to docker/docker. So again:

I want to deploy nginx and do `envsubst`. My compose-file looks like this

```
app1:
  ...
app2:
  ...
nginx:
  environment:
    - HOSTNAME_1='app1'
    - HOSTNAME_2='app2'
    - SERVER_NAME='www.mydomain.com'
    - SSL_DOMAIN='mydomain.com'
  command: /bin/sh -c "echo hostname1: $$HOSTNAME_1, ssldomain: $$SSL_DOMAIN && envsubst '$$HOSTNAME_1 $$HOSTNAME_2 $$SERVER_NAME $$SSL_DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
```
In the logs I see this output:
`hostname1: , ssldomain: mydomain.com`
So `HOSTNAME_1` is not set!

I run it via `docker deploy --with-registry-auth --compose-file docker-compose.yml mystack`

When I run this on a standalone machine, it works. So why are not all ENV_VARs available in swarm mode?

**Output of `docker version`:**
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 12
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local azurefile
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: et9swhzrnf75bo7sa4rht94p1
 Is Manager: true
 ClusterID: 2haye8u7irll56bpl1skp8xir
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.0.4
 Manager Addresses:
  192.168.0.4:2377
  192.168.0.7:2377
  192.168.0.8:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.882 GiB
Name: docker-swarm-master-01-master
ID: FJEZ:PTLX:FDQ5:2WN2:GTNX:GHON:RPKR:SZUA:N2D5:UCK7:LRGZ:LWZ2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: stbecker
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Output of `docker-compose --version`:**
```
docker-compose version 1.10.0, build 4bd6f1a
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Azure.

**Comment by tonistiigi** [comment]
cc @dnephin @vdemeester

**Comment by thaJeztah** [comment]
Could you

- do a `docker inspect <container>` and check if the command set for the container is correct
- also check if the env-vars are properly set in the inspect output
- change the command to `/bin/sh -c env` (or just `env` possibly works) and check if that shows all env vars 

Those steps may help narrowing down in what part the issue is

**Comment by mrmunch** [comment]
@thaJeztah 
In both `docker inspect` and also `/bin/sh -c env` only 3 of my 5 env vars are shown.

**Comment by dnephin** [comment]
I can't reproduce the issue. I just tried it with the example config you provided and I see 4 variables in `env` and in `docker inspect`

**Comment by mrmunch** [comment]
@dnephin 
Is there some kind of cache? I just changed one of the vars which were available - but the old value was displayes.
To be clear: Inside `docker-compose.yml` I changed `SSL_DOMAIN=mydomain.com` to `SSL_DOMAIN=mydomain.commm` but after `docker stack rm mystack && docker deploy [...] && docker service logs mystack_nginx` I still got `SSL_DOMAIN=mydomain.com`

**Comment by mrmunch** [comment]
@dnephin Again: Is there some kind of cache? When I execute `docker stack rm mystack` on manager node 1 and then ssh into manager node 2 and do `docker ps -a` there are still some (stopped) containers with my stack prefix. Is there a single command I can execute only on one manager and delete all container on every node?

**Comment by dnephin** [comment]
There is no cache (that I know of). `docker stack rm` is that command. I'm not sure when swarmkit decides to remove the containers.

**Comment by mrmunch** [comment]
I solved it - it was a very stupid mistake:
In my docker-compose.yml I had **two** entries of `environment`. Sth. like:
```
nginx:
  environment:
    - HOSTNAME_1='app1'
    - HOSTNAME_2='app2'
    - SERVER_NAME='www.mydomain.com'
    - SSL_DOMAIN='mydomain.com'
  ...
  environment:
    - SERVER_NAME='www.mydomain.com'
    - SSL_DOMAIN='mydomain.com'
```
So only the 2nd `environment` was taken. I didn't noticed because the argument `networks` (which is typically the very last argument in all of my compose files) was on the last line displayed on my monitor *facepalm*
