### ISSUE TITLE
docker 1.13 with sawrm - syntax to create a secured overlay network with compose-file

### ISSUE THREAD

**Issue by yaakov-berkovitch** [docker/docker#30865]
I'm not reporting for an issue, but have some problem to understand how to configure an overlay network to be secured using compose-file (version 3) with docker swarm 1.13.

I cannot find the documentation that describes it.

Thanks.

**Comment by sandys** [comment]
same here - i have been hunting through documentation for this as well.

**Comment by cpuguy83** [comment]
```yaml
networks:
  backend:
    driver: overlay
    driver_opts:
      encrypted: "true"
```

https://docs.docker.com/engine/userguide/networking/overlay-security-model/
https://docs.docker.com/compose/compose-file/#driveropts-1
