### ISSUE TITLE
Enable Secrets to be Consumed as Environment Variables

### ISSUE THREAD

**Issue by rawkode** [docker/docker#30866]
**Description**

Not all applications make it  easy to load secrets from file, and I'd prefer not to create complicated entry point scripts. So it would be nice if Docker Swarm provided a means to transform our secrets to the Linux environment for our applications to consume.

I believe this is possible through `-e MYSQL_ROOT_PASSWORD='/run/secrets/file'`, but that's extra configuration and I imagine this would work better with syntax like the following:

```
$ docker service create \
    # Not exposes to environment \
    --secret source=mysql_user_password,target=mysql_user_password \
    # Exposed to environment \
    --secret source=mysql_root_password,target=mysql_root_password,env=MYSQL_ROOT_PASSWORD
```

When this is available in Swarm, I guess we'd also need to modify docker/compose syntax v3 to include something akin to the Kubernetes spec:
```
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
```
