### ISSUE TITLE
Swarm/Compose overlay issues, containers can't access services on other hosts

### ISSUE THREAD

**Issue by jonathan-kosgei** [docker/docker#30926]
**Steps to reproduce the issue:**
1.
```
version: '3'
volumes:
  poc:

networks:
 default:
    driver: overlay
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: 100.64.0.0/16
services:
  pgbouncer:
    image: 10.140.0.2:5000/pgbouncer
    ports:
    - "6000:6000"
    logging:
        driver: journald
  flask:
    image: 10.140.0.2:5000/flask
    depends_on:
      - redis
      - stunnel
      - pgbouncer
    command: ["/wait-for-it.sh", "pgbouncer:6000", "--timeout=0", "--strict", "--", "supervisord", "-c", "/supervisord.conf"]
    logging:
        driver: journald
```
2.
Deploy the above compose file to swarm with
```
docker stack deploy --compose-file=docker-compose.yml  stack_1
```
In my setup, the pgbouncer container and the flask container are on two different hosts

**Describe the results you received:**

The flask container logs
```
wait-for-it.sh: waiting for pgbouncer:6000 without a timeout
```
and stays that way indefinitely.

And on manually starting the flask app I get
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection timed out
	Is the server running on host "pgbouncer" (100.64.0.4) and accepting
	TCP/IP connections on port 6000?
```

**Describe the results you expected:**
To be able to access pgbouncer from flask as though they were on the same node.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have the relevant ports open i.e. udp/tcp 7946 and udp 4789

```
root@instance-1:~/docker-setup# nc -z -v -u 10.140.0.4 4789
Connection to 10.140.0.4 4789 port [udp/*] succeeded!
root@instance-1:~/docker-setup# nc -z -v -u 10.140.0.4 7946
Connection to 10.140.0.4 7946 port [udp/*] succeeded!
root@instance-1:~/docker-setup# nc -z -v -t 10.140.0.4 7946
Connection to 10.140.0.4 7946 port [tcp/*] succeeded!
```

I get the above issue with or without the encrypted flag set to true.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 66
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: qlx6cmt9svclci6rydk0ajjff
 Is Manager: true
 ClusterID: iln0ij4pnmr2rc2u69rgrss3t
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.140.0.2
 Manager Addresses:
  10.140.0.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.304 GiB
Name: instance-1
ID: EK6Y:L4L5:PSQE:CXBC:BYLT:CGWI:D423:WC3R:SU4J:ZX6F:WOFK:QBGZ
Docker Root Dir: /docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 10.140.0.2:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
