### ISSUE TITLE
How to set up data volume containers with Docker compose?

### ISSUE THREAD

**Issue by anonmily** [docker/docker#30920]
I'm taking a look through the documentation, and I can't seem to find anywhere that shows how we can specify where a data volume container is located on the host. 

Below is the example given (from: https://docs.docker.com/compose/compose-file/#/volume-configuration-reference)

```
version: "3"

services:
  db:
    image: db
    volumes:
      - data-volume:/var/lib/db
  backup:
    image: backup-service
    volumes:
      - data-volume:/var/lib/backup/data

volumes:
  data-volume:
```

However, although we can see that data-volume has been mounted into /var/lib/db in the db container and into /var/lib/backup/data for the backup container, where do we specify where the data-volume is actually located on the host?
