### ISSUE TITLE
docker login command not working in swarm mode

### ISSUE THREAD

**Issue by mahmoudmahdi24** [docker/docker#31004]
Hello !
I am facing a problem with my docker registry in a swarm mode cluster.
I created a swarm cluster on my machine using this command :
```
swarm init
```
Then i deployed my stack on it ( which is a private docker registry ) :
here's my docker-compose file (version 3) :
```

version: "3"
services:
  registry:
    image: "registry:2"
    ports:
      - 5000:5000
    networks:
      - registry_internal
    environment:
      SETTINGS_FLAVOR: local
      STORAGE_PATH: "/data/"
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  registry_internal:

```

if i launch the command docker login, i don't get a response : 
```
docker login http://localhost:5000
```

but when i try to ping my registry with a curl, it responds : 
```
curl http://localhost:5000/v2/_catalog
{"repositories":[]}
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: gdaxrnrfp9lu92xdrcu12xu58
 Is Manager: true
 ClusterID: gut3h0xfrjpfrospbwqc57oaf
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: CX7Z:B3WX:4FMB:FHAV:CDQQ:CGKW:HBAL:PFRK:WPYW:RE7V:WANI:FIPS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 63
 Goroutines: 171
 System Time: 2017-02-14T13:50:27.230446067Z
 EventsListeners: 2
Http Proxy: http://10.49.64.5:8080
Https Proxy: http://10.49.64.5:8080
No Proxy: *.local,169.254/16,localhost,127.0.0.1,0.0.0.0,localhost:3000,localhost:8080,localhost:8081,galaxy.ansible.com:443,galaxy.ansible.com/api/,index.docker.io/v1/repositories/dockercore/docker/images
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thanks for helping !
