### ISSUE TITLE
Specifying macaddress for service

### ISSUE THREAD

**Issue by jsharpe** [docker/docker#31092]
I've tried specifying the mac_address in a docker compose v3 file and it doesn't give any parse errors or warnings when deploying via docker stack deploy but the mac_address parameter is not set for the service.

It appears that the option to set a mac address for a service is not available. This is required for services that use the mac address for e.g. licensing purposes.

**Comment by cpuguy83** [comment]
Agreed on licensing issues.

Ping @dnephin for yaml parsing, this should throw an error since it's not supported.

**Comment by dnephin** [comment]
This is working correctly, it should be a warning:

```
Ignoring unsupported options: mac_address
```

**Comment by jsharpe** [comment]
My bad, I missed the warning; I'd been skimming the output as I was having to ignore the unable to pin image warnings too.

**Comment by trevorfuson** [comment]
We have containers that use mac address for licensing. Our legacy apps won't be able to run as a service because of this.

**Comment by thaJeztah** [comment]
Wondering what the approach should be for services, because a service can be backed by multiple tasks (containers); each one would need its own mac address.

**Comment by s-e-k** [comment]
We do also have a license container which needs a host and mac address. I would like to run the container in the swarm like we have all other containers.

**Comment by lwilliams10** [comment]
I've also encountered this trying to run with docker compose v 3.7

I need to fix the mac address of a container to support a node-locked license service.

**Comment by andyfisher100** [comment]
This feature would be really helpful for us. We have software that is licensed based on Mac addresses, as antiquated a technique as that is. I could see a solution being being something like specifying a MAC address range that can be used by the service for replicas. So if the service is 10 replicas, then a range of 10 Mac addresses is also required to be specified

**Comment by thaJeztah** [comment]
> I could see a solution being something like specifying a MAC address range that can be used by the service for replicas. So if the service is 10 replicas, then a range of 10 Mac addresses is also required to be specified

That would imply the licenses are tied to a consecutive range of MAC addresses; is that a realistic scenario? (wondering). Or did I misunderstand and you meant; allow setting a list of MAC addresses to use?

**Comment by andyfisher100** [comment]
> > I could see a solution being something like specifying a MAC address range that can be used by the service for replicas. So if the service is 10 replicas, then a range of 10 Mac addresses is also required to be specified
> 
> That would imply the licenses are tied to a consecutive range of MAC addresses; is that a realistic scenario? (wondering). Or did I misunderstand and you meant; allow setting a list of MAC addresses to use?

Ah yes, it would mean that licenses would need to be configured to a consecutive list of MAC addresses. We could configure this though, i think, for the software in question

**Comment by NonaSuomy** [comment]
https://github.com/moby/moby/pull/46406

**Comment by thaJeztah** [comment]
@NonaSuomy this ticket is a feature request for MacAddress support for swarm services; can you open a ticket instead, with details how to reproduce?

**Comment by NonaSuomy** [comment]
Are swarm services what Portainer **now** uses to set mac_addresses in their docker-composed webui? I was directed to this ticket as the issue as to why it currently doesn't work. This is odd if it was never in it to begin with unless they used to use just straight docker-compose to load up the containers which I believe may be the case when they switched to swarm and now it doesn't.

**Comment by NonaSuomy** [comment]
By service don't they just mean that its set under your defined service ie in this case below wyomingopenwakeword being the service?
```yaml
# Wyoming-OpenWakeWord Container for Docker
version: "3.9"
services:       #<== That you set mac_address under wyomingopenwakeword, etc being the "service"? 
  wyomingopenwakeword:
    container_name: "wyoming-openwakeword"
    image: "rhasspy/wyoming-openwakeword:latest"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/libvirt/images/usb001/docker-storage/wyoming-openwakeword/data:/data
    mac_address: "9e:de:ad:be:ef:01" #<== MAC Address set under "service: wyomingopenwakeword"
    hostname: "wyomingopenwakeword"
    networks:
      - dhcp
    ports:
      - 10400:10400
    devices:
      - /dev/snd:/dev/snd
    command: --model 'ok_nabu' --model 'hey_jarvis' --model 'hey_rhasspy' --model 'hey_mycroft' --model 'alexa' --preload-model 'ok_nabu'    
    # --uri 'tcp://0.0.0.0:10400'
    restart: "no"
    #restart: unless-stopped
    #privileged: true
    #network_mode: host

networks:
  dhcp:
    name: "dbrv700"
    external: true
```
