### ISSUE TITLE
Exporting volume from container running in windows 10 insider preview doesn't work

### ISSUE THREAD

**Issue by git-jiby-me** [docker/docker#31118]
**Description**

I am trying the latest windows 10 insider preview build with docker overlay driver support.

I have a image thats build with the below `Dockerfile`

```
FROM microsoft/windowsservercore

COPY . C:/temp

SHELL ["powershell", "-Command"]

RUN New-Item c:\Qumram -Type directory; \
    New-Item C:\Qumram\start.ps1 -Type File -Value \
    'Param( \
        [string]$LogFilePath = \"C:\Qumram\config\config.log\" \
    ) \
    Copy-Item C:\temp\*  C:\Qumram\config -Recurse | Out-Null; \
    New-Item -Path $LogFilePath -Itemtype file -Force | Out-Null; \
    Get-Content -Path $LogFilePath -Wait;'

VOLUME C:\\Qumram\\config

SHELL ["powershell", "-File"]

HEALTHCHECK CMD exit 0
ENTRYPOINT C:\Qumram\start.ps1
```

And i deploy a stack using the below `compose.yml` file

```
version: '3.0'

volumes:
    windows-configuration:

services:
    config-windows-volume:
        image: josejiby/qumram:testconfig-windows-dev
        volumes:
            - windows-configuration:\\c\Qumram\config
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - engine.labels.type == windows
            restart_policy:
                condition: on-failure
```

I used to use `volumes_from` in the earlier 2.0 format in windowsservercore to share the volume, however i am using the new v3 format hence the named volume in compose file.

**Steps to reproduce the issue:**
1. I run `docker -H linuxhost stack deploy -c compose.yml test
2. It schedules and starts running the container
3. The container fails throwing an error `starting container failed: container a85162e691c88570cc097eb709862659838d6e68291bf55f6aa1672b887bbc7c encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106)`

**Describe the results you received:**

The container should have started exporting the folder as a named volume

**Describe the results you expected:**

The container crashes

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 57
Server Version: 1.13.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: active
 NodeID: mzpe8u9g1448u9aw7ph2s8wub
 Is Manager: false
 Node Address: 10.211.55.7
 Manager Addresses:
  10.211.55.8:2377
Default Isolation: hyperv
Kernel Version: 10.0 15031 (15031.0.amd64fre.rs2_release.170204-1546)
Operating System: Windows 10 Enterprise Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.983 GiB
Name: windows
ID: 5262:FAUI:VLWB:COL4:Z3HH:5XGE:DBPD:HFBS:VYXB:CNAY:VKV3:CGFT
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: josejiby
Registry: https://index.docker.io/v1/
Labels:
 type=windows
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The windows host is running inside parallels along side an ubuntu vm, which is the master of the swarm.
