### ISSUE TITLE
docker stack deploy - no such image

### ISSUE THREAD

**Issue by missionrulz** [docker/docker#31169]
**Description**

I have a swarm cluster (1 manager, 2 workers), when trying to deploy a stack to the swarm using a private registry, the image is not being pulled even with auth credentials being present on each node.

**Steps to reproduce the issue:**
1. Create swarm consisting of 1 manager, 2 works + external private registry (not in the swarm)
2. Deploy stack to swarm using an image from the private registry

**Describe the results you received:**
The image cannot be found

```
docker stack deploy --compose-file swarm.yml stack
docker stack ps stack
ID            NAME                IMAGE                                                             NODE          DESIRED STATE  CURRENT STATE           ERROR                             PORTS
7pcl8hwo57ax  stack_consul.1      private-registry.com/consul:latest  swarm-master  Ready          Rejected 4 seconds ago  "No such image: private-regist..."  
kdt9jithrmmz   \_ stack_consul.1  private-registry.com/consul:latest  swarm-master  Shutdown       Rejected 4 seconds ago  "No such image: private-regist..."
```

I have also tried using the `--with-registry-auth` option when deploying the stack, which has the same result.

```
version: '3'

services:
  consul:
    image: private-registry.com/consul:latest
    command: ["agent", "-server", "-bind=0.0.0.0", "-bootstrap-expect=3", "-ui", "-client", "0.0.0.0", "-dns-port=53", "-log-level=info", "-recursor=8.8.8.8", "-config-dir=/consul/config", "-data-dir=/consul/data"]
    hostname: consul
    ports:
      - 8500:8500
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
```

**Describe the results you expected:**
Each node should pull the image and start the container.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: opxx0ia4dd40msfgn74iij8dt
 Is Manager: true
 ClusterID: 2pkudbtmrrvpvakz7vvhd6zw2
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.10.10.112
 Manager Addresses:
  10.10.10.112:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.47-boot2docker
Operating System: Boot2Docker 1.13.1 (TCL 7.2); HEAD : b7f6033 - Wed Feb  8 20:31:48 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: swarm-master
ID: KH4O:2FID:TNEX:4WIA:2MVD:XZYL:WXCZ:7K2A:KBBP:7PPN:OKGO:S4TV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 80
 Goroutines: 249
 System Time: 2017-02-19T21:02:47.168179173Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```
docker-machine ls
NAME           ACTIVE   DRIVER       STATE     URL                       SWARM   DOCKER    ERRORS
node-01        -        virtualbox   Running   tcp://10.10.10.113:2376           v1.13.1   
node-02        -        virtualbox   Running   tcp://10.10.10.114:2376           v1.13.1   
swarm-master   -        virtualbox   Running   tcp://10.10.10.112:2376           v1.13.1  
```

```
docker-machine --version
docker-machine version 0.9.0, build 15fd4c7
```

```
docker-compose --version
docker-compose version 1.11.1, build 7c5d5e4
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
