### ISSUE TITLE
Stack deploy with default network is not working as expected

### ISSUE THREAD

**Issue by mostolog** [docker/docker#31228]
**Description**

After reading https://github.com/docker/docker/issues/29982, according to https://docs.docker.com/compose/compose-file/#/networks and as https://docs.docker.com/compose/compose-file/#/external-1 states:
> If set to true, specifies that this network has been created outside of Compose. docker-compose up will not attempt to create it, and will raise an error if it doesn’t exist.

However, seems stack networks are not working as expected.

**Steps to reproduce the issue:**
1.Create overlay attachable network mynet
```
$docker network create --attachable --driver overlay mynet
kc9u8lgi1yugpudo5qk6o2g58
$docker network inspect mynet
[
    {
        "Name": "mynet",
        "Id": "kc9u8lgi1yugpudo5qk6o2g58",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": true,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4098"
        },
        "Labels": null
    }
]
```
2.Write stack.yml compose-file
```
version: "3"
networks:
  default:
    external:
      name: "mynet"
services:
  elasticsearch:
    command: "elasticsearch -E cluster.name=app -E node.name=app-elasticsearch -E discovery.zen.ping.unicast.hosts=elasticsearch"
    image: "elasticsearch:5.2.1"
```
3.Try to deploy the stack
> docker stack deploy --compose-file stack.yml myapp

**Describe the results you received:**

docker stack deploy --compose-file stack.yaml myapp
Creating service myapp_elasticsearch
Error response from daemon: network myapp_default not found

**Describe the results you expected:**

Simple stack with service attached to default network "mynet"

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 42
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ph56dmuj9xyp7v0mxngpi4wmg
 Is Manager: true
 ClusterID: jmdwt0h7bwcobihnfignepzwr
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 155.54.212.5
 Manager Addresses:
  155.54.212.5:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.4 GiB
Name: computer
ID: E4N3:47NS:3QGR:EWSK:L4ZR:RWXL:JJXE:U53F:4NIU:N6XK:6OVD:WY4C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Similar issue**

```
$cat stack.yml
version: "3"
networks:
  default:
    mynet:
      external: true
services:
  elasticsearch:
    command: "elasticsearch -E cluster.name=app -E node.name=app-elasticsearch -E discovery.zen.ping.unicast.hosts=elasticsearch"
    #hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    image: "elasticsearch:5.2.1"

$docker stack deploy --compose-file stack.yml myapp
mynet Additional property mynet is not allowed
```

```
$cat stack.yml
version: "3"
networks:
  default:
    external:
      name: mynet
services:
  elasticsearch:
    command: "elasticsearch -E cluster.name=app -E node.name=app-elasticsearch -E discovery.zen.ping.unicast.hosts=elasticsearch"
    image: "elasticsearch:5.2.1"
    networks:
      - mynet

$docker stack deploy --compose-file stack.yml myapp
service "elasticsearch" references network "mynet", which is not declared
```
