### ISSUE TITLE
Clean up unused images on all nodes in Docker Swarm

### ISSUE THREAD

**Issue by lsapan** [docker/docker#31254]
Currently we have to SSH into each node and run something like `rmi $(docker images -q)` to clean up old images. This seems fairly impractical for large swarms. It would be great to have command that can be run from the leader that instructs all the other nodes to clean up old images.

**Comment by grunichev** [comment]
Something like `docker swarm prune` (similar to `docker system prune`) can be useful.

**Comment by thaJeztah** [comment]
We were discussing some options recently (was looking if I could find the discussion back on GitHub). 

"Unused" is the tricky bit here, because services have an option to "roll back" to a previous version.

One option would be to make use of the service's history; whenever a service is updated, the previous version is kept around (which allows rolling back to the previous version). Any image that is no longer referenced in the history could be purged on nodes in the swarm.

Swarm scoped networks are already cleaned up when tasks are removed, so taking a similar approach for images could make sense.

/cc @aluzzardi

**Comment by aluzzardi** [comment]
/cc @ehazlett 

Long term, yes, that's what we want. We don't have a timeline yet

**Comment by yunghoy** [comment]
Any news from here?

**Comment by samuel-weber** [comment]
What about
```bash
swarm-exec docker system prune
```

**Comment by thaJeztah** [comment]
I don't think someone is working on this, but contributions welcome (starting with a full design for this feature)

**Comment by hoffa** [comment]
Here's quick and dirty workaround I've been using:

```
#!/usr/bin/env bash
set -ex

SSH_USER=myuser
SWARM_MANAGER=1.2.3.4

ips=$(ssh ${SSH_USER}@${SWARM_MANAGER} 'for n in $(docker node ls -q); do echo $(docker node inspect --format "{{ .Status.Addr }}" $n); done')

for ip in $ips; do
    ssh ${SSH_USER}@$ip 'sudo docker system prune -f'
done
```

**Comment by cpuguy83** [comment]
```
docker service create --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock --mode=global --restart-condition on-failure docker docker system prune -f
```

**Comment by adijes** [comment]
any updates regarding this issue? we really need it for production swarm!

**Comment by eleaner** [comment]
@cpuguy83 
> docker service create --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock --mode=global --restart-condition on-failure docker docker system prune -f

is it possible for docker to run this service daily?

**Comment by cpuguy83** [comment]
@eleaner Docker does not have a mechanism to trigger jobs on some interval.
You could run a cron service on manager node to deal with this.

**Comment by eleaner** [comment]
does it sound like a bad idea if I try to setup a docker service with 24h
delay or something like that?

**Comment by binlab** [comment]
first at all create a service as suggested before:
```
docker --host $DOCKER_HOST service create -d \
    --name system-prune \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    --mode=global \
    --restart-condition on-failure \
    docker docker system prune -f
```

then form CI/CD tools (e.g. Jenkins) just update it after successful deploy 

```
docker --host $DOCKER_HOST service update --force -d system-prune
```

please note, environment variable need `$DOCKER_HOST` for connecting to remote Docker Swarm from CI/CD tools. You can remove it if not needed

**Comment by Monokai** [comment]
Thank you. I've ended up adding this service to my `docker-compose` file:

```
system-prune:
    image: docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: docker system prune --all --force
    deploy:
      mode: global
      restart_policy:
        delay: 24h
```

I think it does the same as what you're suggesting.

**Comment by reg2005** [comment]
@Monokai big thanks, [my config](https://gist.github.com/bastman/5b57ddb3c11942094f8d0a97d461b430#gistcomment-2865234)

**Comment by kraduk** [comment]
Not specifically a docker solution but it works

setup inventory once eg
```
echo "[staging]
host1
host2 " > inventory
```

Run this after whenever you want
`ansible -m shell -a "docker system prune -fa " -i inventory staging -bkK
`

**Comment by rajpushpa1** [comment]
command: docker system prune --all --force This command is not working while using docker stack.
getting error "container_linux.go:235: starting container process caused "exec: \"docker\": executable file not found in $PATH", how to run docker commands in compose file?

**Comment by rajpushpa1** [comment]
version: "3"
services:
  test:
    image: "test01"
    restart: always
    ports:
      - "8888:8080"
    volumes:
     # - /apps/glowroot:/var/glowroot
     # - /apps/glowroot/setenv_api.sh:/usr/local/tomcat/bin/setenv.sh
    command: docker system prune --all --force

this is my compose file

**Comment by kraduk** [comment]
you wouldnt normally run it in compose, as you have no idea which command would actually run 1st, so you have got a race command.  If for some reason you did want to run it in a container the relevant container would have to have the docker clients in it, and you would have to map in the docker.socket with a bindmount. This wont work very well for swarms though. Best to run it outside the compose file. Wrap it all up in a shell script

eg

#!/bin/bash

docker-compose up && docker system prune --all --force

**Comment by rajpushpa1** [comment]
Hi kraduk, 
Thanks for your suggestion.
how to run with docker stack deploy command,  the command you have suggested will it work on all the nodes in swarm cluster?

**Comment by maxisme** [comment]
Perhaps use [alpinelinux/docker-cli](https://hub.docker.com/r/alpinelinux/docker-cli) for a smaller image ([18MB](https://hub.docker.com/layers/alpinelinux/docker-cli/latest/images/sha256-5a20306efabf88af268f4a295204200eeb81f8edfcfd93c1f32c0acab1483265?context=explore)) than `docker` ([62MB](https://hub.docker.com/layers/docker/library/docker/latest/images/sha256-18d39b6848cecae067cc0d94c554029bfc88d3069c80bb5049d54da659249b94?context=explore) seeing as we are all trying to reduce storage :)
```
  system-prune:
    image: alpinelinux/docker-cli
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: docker system prune --all --force
    deploy:
      mode: global
      restart_policy:
        delay: 24h
```

**Comment by thnk2wn** [comment]
This [stack-prune.yml](https://github.com/BretFisher/dogvscat/blob/master/stack-prune.yml) example works for me (from [this talk](https://youtu.be/V9fxU5zJKb4)) - simple global Docker service with a loop sleeping 24 hours and running whatever prune that's desired on each node.

```yaml
version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "1m" 
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  image-prune:
    <<: *default-opts
    image: docker
    command: sh -c "while true; do docker image prune -af; sleep 86400; done"
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

networks:
  bridge:
    external: true
    name: bridge
```
