### ISSUE TITLE
Requests to Swarm cluster get stucked.

### ISSUE THREAD

**Issue by sombralibre** [docker/docker#31293]
Hi there,

I'm not sure if it's the right place to post this, but I really need some help with the follows issues:

I've create a swarm cluster as follow 

```
docker swarm init --advertise-addr 10.0.0.240 --listen-addr 10.0.0.240
```
Add a node by 

```
docker swarm join --token SWMTKN-1-44vris9xsytcrms6kg-3p2yktgdubc828u4gzc6rxdas --advertise-addr 10.0.0.241 --listen-addr 10.0.0.241  10.0.0.240:2377
```

I run "docker node ls' and apparently everthing is ok, then I've created a compose file to be deployed with "docker stack deploy", with successful return, it created a stack with its own network and its services.

```
version: "3"
services:
 rabbitmq:
  image: rabbitmq:3
  networks:
   - " AlkaOverlay"
 backend:
  image: "IMAGEB:TAGB"
  networks:
   - " AlkaOverlay"
  ports:
   - "1080:80"
  environment:
   - "DJANGO_SETTINGS_MODULE=alka.settings_staging"
  command: "/srv/www/bin/gunicorn.sh"
  deploy:
   mode: "replicated"
   replicas: 2
 celery:
  image: "IMAGEB:TAGB"
  networks:
   - " AlkaOverlay"
  environment:
   - "DJANGO_SETTINGS_MODULE=alka.settings_staging"
  command: "/srv/www/bin/celery.sh"
 frontend:
  image: "IMAGEF:TAGF"
  networks:
   - " AlkaOverlay"
  ports:
   - "80:80"
   - "443:443"
  deploy:
   mode: "replicated"
   replicas: 2

networks:
 AlkaOverlay:
  driver: overlay
  ipam:
   driver: default
   config:
    - subnet: 10.0.253.0/24
```

The connections issues start to appears when try to use the web app throught tcp port 80, I've basically tried curl request like this:
```
for t in {1..10};do echo "LOOP $t"; timeout 3s curl 10.0.0.240:1080 ;done

for t in {1..10};do echo "LOOP $t"; timeout 3s curl 10.0.0.241:1080 ;done
```
and from inside of the "frontend" containers

```
for t in {1..10};do echo "LOOP $t"; timeout 3s curl backend ;done
```

However always I run the tests, the response of the "backends" I get works like a "round robin", that means one request work fine, and the next get stucked waiting for response however the request reach the timeout and the petitions die; these timeout are translates to server errors (5XX) to the clients.

On an intent to get the stack work fine, I've run every component (backend, frontend, rabbit, celery) on separated container and make its network connections through physical network interface of the hosts instances; well with this setup all work fine, but the pearks of scaling has been gone.

I've checked the udp connections between hosts and these works fine, also have change the deploy mode from "replicated" to "global", but any of this setup to swarm has get the cluster to work fine.

I would appreciate any help or advice with the issue. Thanks a lot.
