### ISSUE TITLE
Local NFS4 volumes do not resolve hostnames

### ISSUE THREAD

**Issue by zh99998** [docker/docker#31365]
Just like #26639, #27329 but for `nfs4` mount type.

**Comment by cpuguy83** [comment]
So you are doing `type=nfs4`?
This doesn't seem right. Should be `type=nfs` and `o=nfsvers=4`

**Comment by zh99998** [comment]
but `type=nfs4` works.
It should throw error or warning if considered `doesn't right`.

part of my `docker-compose.yml` file, it works.
```
volumes:
  nginx:
    driver_opts:
      type: nfs4
      o: addr=<IP Address>
      device: :/nginx
```
