### ISSUE TITLE
how to restart docker service

### ISSUE THREAD

**Issue by hehailong5** [docker/docker#31375]
I don't see any option to restart a docker service, if I docker restart the container belonging to a docker service. a duplicate container will be created and running.

**Comment by thaJeztah** [comment]
correct, there's no "restart" option for services; see the discussion on https://github.com/docker/docker/issues/24413. If you have a specific use-case please describe your use-case on that issue.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

I'm going to close this is a duplicate of https://github.com/docker/docker/issues/24413, but feel free to continue the conversation 👍

**Comment by rssllyn** [comment]
You can scale the service to 0 node, then back again.

$ docker service scale=0
$ docker service scale=1

Check [this](https://docs.docker.com/engine/swarm/how-swarm-mode-works/services/#pending-services)

**Comment by michaellenhart** [comment]
@rssllyn 
Hello rssllyn,
you can use scale only if your services are in replicated modus. It's not working in global modus.

@thaJeztah 
Hello thaJeztah,
My useCase and why a restart option makes sense.
Using three containers which depends on each other:
Container with GUI (Angularjs, ExpressJs, Nodejs)->Container with API (Nodejs, ExpressJs)->Container with MongoDB

Hier a snippet of the docker-compose V3 file:
 ... 
```
 angebot-db:
      image: mongo:latest
      container_name: "angebot-db"
      ports:
        - "27019:27019"
      command: --smallfiles
      deploy:
        restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 10
          window: 60s
        mode: global
        placement:
          constraints: [node.role == manager]
      networks:
        - lager
      volumes:
        - ~/shared/data/db/angebot:/data/db
      labels:
         org.label-schema.group: "angebot webapp"

    angebot-server:
      image: mlenhart/chemcologne-angebot-server
      container_name: "angebot-server"
      ports:
        - "4000:4000"
      command: npm start
      depends_on:
        - angebot-db
      deploy:
        restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 10
          window: 60s
        mode: global
      networks:
        - lager
      labels:
         org.label-schema.group: "angebot webapp"

    angebot-client:
      image: mlenhart/chemcologne-angebot-client
      container_name: "angebot-client"
      ports:
        - "8888:8888"
      command: npm start
      depends_on:
        - angebot-server
      deploy:
        restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 10
          window: 60s
        mode: global
      networks:
        - lager
      labels:
         org.label-schema.group: "angebot webapp" 
```
After starting the Services in Swarm mode with 
`docker stack deploy -c docker-compose.yml SWARM`
The docker logs command of my Service angebot-server shows an connection error  

```
angebot-server@0.0.0 start /src
> node ./bin/www

Produktionsumgebung
Verbindung zur Datenbank 'angebot' fehlgeschlagen
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
GET /angebot - - ms - -
GET /angebot - - ms - -
GET / 404 6.740 ms - 10
```
This is because the mongo database takes to many time for initializing and the Container with the API can't connect.
If I could restart the API container, it would connect to the database.
