### ISSUE TITLE
Swarm-wide plugin deployment and lifecycle management

### ISSUE THREAD

**Issue by anusha-ragunathan** [docker/docker#31401]
In 1.13, plugin installation and lifecycle management is possible on a single engine node only. In 17.04, we should add the ability to deploy plugins across a swarm as well as manage plugin lifecycle in swarm-mode. /

For this, `docker plugin` CLI/API endpoints can be made swarm aware. With the exception of `plugin create` and `plugin push`, all other plugin endpoints (`install`, `enable`, `disable`, `ls`, `rm`, `set`, `upgrade`) will be applicable in swarm mode.

**Comment by anusha-ragunathan** [comment]
cc @ehazlett @aluzzardi @icecrime

**Comment by ehazlett** [comment]
Related: https://github.com/docker/swarmkit/pull/1964

**Comment by SvenDowideit** [comment]
I use a service like:

```
  docker-volume-plugin-run-once:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "docker plugin install --alias swarm --grant-all-permissions svendowideit/seaweedfs-volume-plugin:next DEBUG=true"
    deploy:
      mode: global
      restart_policy:
        condition: none
```

but this kind of thing won't work so well for upgrading, because it seems you need to delete the volumes, so you can disable the plugin first

and I'm sure what we really want, is for `docker plugin upgrade` to set things up so that at some point when its convenient, we switch over to the new plugin - worst case, would be when we reboot, and so need to start the plugin container anyway.
