### ISSUE TITLE
can't mount single file in NFS as volume

### ISSUE THREAD

**Issue by zh99998** [docker/docker#31406]
part of my docker-compose file
```
version: "3"
services:
  ygopro-match:
    image: mycard/ygopro-match
    volumes:
      - ygopro-match:/ygopro-match.json
volumes:
  ygopro-match:
    driver: local
    driver_opts:
      type: nfs
      o: addr=0f82c484e6-iee57.cn-hangzhou.nas.aliyuncs.com
      device: :/ygopro-match.json
```

the `/ygopro-match.json` is a regular file exists in nfs.

now that service cant startup, says:

```
docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/mycard_ygopro-match/_data': error while mounting volume with options: type='nfs' device=':/ygopro-match.json' o='addr=0f82c484e6-iee57.cn-hangzhou.nas.aliyuncs.com': not a directory.
```

manually `docker run` behaves same
```
➜  ~ docker run -v mycard_ygopro-match:/1 -it debian bash 
docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/mycard_ygopro-match/_data': error while mounting volume with options: type='nfs' device=':/ygopro-match.json' o='addr=0f82c484e6-iee57.cn-hangzhou.nas.aliyuncs.com': not a directory.
```
