### ISSUE TITLE
Feature Request: Namespace Volumes For Replicated Swarm Services

### ISSUE THREAD

**Issue by jamespedwards42** [docker/docker#31671]
The feature would enable dynamically creating a unique volume for each instance (container) of a replicated service.  This would be useful for network attached block storage, which usually can only be attached to a single server for writes.

Currently, if you want replication for a service using networked block storage, the configuration has to be copy/pasted N times and the built in load balancing is lost.... As far as I can figure... Is there a better way to do this currently?

Here is a stripped down Swarm Compose file to illustrate the kind of service I would like to be able to increase replication on:

```yaml
version: '3.1'
# docker stack deploy --compose-file=ec2-compose.yml mystack

services:
 my_service:
  image: org/image
  volumes:
   - my_volume:/dir
  deploy:
    mode: replicated
    replicas: 1
  command: ['cmd']
  
volumes:
  my_volume:
    driver: rexray/ebs
    driver_opts:
      size: 100
      volumeType: gp2
      fsType: ext4
      availabilityZone: us-east-1e
```

I originally opened this request under the rexray project, [codedellemc/rexray/issues/7650](https://github.com/codedellemc/rexray/issues/765), but then realized it was out of scope at the volume plugin level.

**Comment by cpuguy83** [comment]
If you don't give a volume a name, each task (instance) will get it's own volume.

**Comment by jamespedwards42** [comment]
@cpuguy83 If the server hosting the first instance fails and is rescheduled on another swarm node will it reattach the same volume it had before?

**Comment by cpuguy83** [comment]
@jamespedwards42 If you provide no source, there would be nothing to re-attach to.
You could (not in the compose format, but in the CLI) provide a template like `--mount source='{{.Service.ID}}.{{.Task.Slot}}'`, but I think this is not necessarily **always** going to give you what you want either.

**Comment by jamespedwards42** [comment]
@cpuguy83 I've updated the original post to give some more context... Would it be possible to configure multiple/separate services under a single name within Swarms internal load balancing?

**Comment by cpuguy83** [comment]
@jamespedwards42 No, but you can throw your own LB in front to handle this case.

**Comment by jamespedwards42** [comment]
@cpuguy83 yes, that is why I mentioned having to configure your own load-balancer like haproxy or nginx.

**Comment by s4s0l** [comment]
@cpuguy83 what do you mean when saying: 'this is not necessarily always going to give you what you want either'? In what situation it would not work as expected? I'm feeling I'm missing something, because it looks like perfect solution for @jamespedwards42 use case. 

This would be great if it could work from docker-compose.yml, without it it's hard to utilize swarm mode features for containers needing persistence (replicated mode, updates, scaling, routing mesh etc). And if it works from docker service level it deserves to work from compose file;)

**Comment by cpuguy83** [comment]
@s4s0l `slot` isn't guaranteed, and also this would not work from a compose file just because the UX is funky for this.

We just need to support stateful services properly in swarm.
It's definitely a known problem.

**Comment by lipingxue** [comment]
@cpuguy83 I agreed with you that support stageful services properly in swarm is needed.  Any progress in this area? What is docker's plan in supporting this? Thanks!

**Comment by cpuguy83** [comment]
I opened docker/swarmkit#2168 to discuss the interface for this.
Needs to get buy-in from the swarmkit maintainers (and validation from people for whom it would be thrust upon, of course!)... and of course someone(s) to work on it.

It will require some changes to the driver API as well.

**Comment by friism** [comment]
Some moby-based Docker products (for AWS and Azure) support persistent volumes of the kinds requested here: https://docs.docker.com/docker-for-aws/persistent-data-volumes/#use-a-unique-volume-per-task-using-ebs

**Comment by jaschaio** [comment]
Somebody proposed a solution in https://github.com/rexray/rexray/issues/804 which appears to be working in compose for me:

```
volumes:
  data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-vol'
    driver: cloudstor:aws
```

Am I missing something or doesn't this do exactly what is asked for in this issue?
