### ISSUE TITLE
Ubuntu 16.04: some containers not restarting after reboot

### ISSUE THREAD

**Issue by bscheshirwork** [docker/docker#31753]
From https://github.com/docker/compose/issues/4603

Some container composition don't (re)start correctly after reboot.
docker-compose.yml (1)
```
version: '2'
services:
  php:
    image: bscheshir/php:7.1.2-fpm-4yii2-xdebug
    restart: always
    volumes:
      - ../php-code:/var/www/html #php-code
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=192.168.0.83 remote_port=9001 var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=yii2"
  nginx:
    image: bscheshir/nginx:alpine
    restart: always
    ports:
      - "8081:80"
      - "8082:8080"
      - "8083:8088"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ../nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ../nginx-logs:/var/log/nginx #nginx-logs
    environment:
      TZ: Europe/Moscow
  mysql:
    image: mysql:8.0.0
    restart: always
    expose:
      - "3306" #for service mysql-proxy
    ports:
      - "3307:3306" #for external connection
    volumes:
      - ../mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2
      MYSQL_DATABASE: yii2
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2
  db: #mysql-proxy
    image: bscheshir/mysql-proxy:0.8.5
    expose:
      - "3306" #for service php
    ports:
      - "3308:3306" #for external connection
    restart: always
    volumes:
      - ../mysql-proxy/log.lua:/opt/log.lua
      - ../mysql-proxy/mysql.log:/opt/mysql-proxy/mysql.log
    environment:
      TZ: Europe/Moscow
      PROXY_DB_PORT: 3306
      REMOTE_DB_HOST: mysql
      REMOTE_DB_PORT: 3306
      PROXY_LUA_SCRIPT: "/opt/log.lua"
    depends_on:
      - mysql

```

In the `docker ps` list STATUS is "Up 5 minutes"

`docker inspect -f "{{ .HostConfig.RestartPolicy }}" <container>` return `always` for all container

But service does not work correctly 
http access to web server 0.0.0.0:8081 0.0.0.0:8082 0.0.0.0:8083 (Connection was dropped), 
connect to db 3307 (Some strange: I can connect, but I can see the information schema only) 
(php not tested) 

Same situation with (2)
```
version: '2'
services:
  php:
    image: bscheshir/php:7.1.2-fpm-4yii2-xdebug
    restart: always
    volumes:
      - ./php-code:/var/www/html #php-code
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
  nginx:
    image: nginx:1.11.10-alpine
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "8088:8088"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ./nginx-logs:/var/log/nginx #nginx-logs
  db:
    image: mysql:8.0.0
    restart: always
    volumes:
      - ./mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2
      MYSQL_DATABASE: yii2
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2
```

And other composition is running correctly at same time: `sameersbn/gitlab`

The another composition for same config (env difference) may up correctly after reboot
https://github.com/bscheshirwork/docker-yii2-app-advanced-rbac/blob/master/docker-compose.yml (3)
```
version: '2'
services:
  php:
    image: bscheshir/php:7.1.2-fpm-4yii2-xdebug
    restart: always
    volumes:
      - ./php-code:/var/www/html #php-code
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
  nginx:
    image: nginx:1.11.10-alpine
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ./nginx-logs:/var/log/nginx #nginx-logs
  db:
    image: mysql:8.0.0
    restart: always
    volumes:
      - ./mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2advanced
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: yii2advanced
```

And if I up then together ( (2) and (3) ) - all of it is fails after reboot  

```
docker -v
Docker version 17.03.0-ce, build 60ccb22
docker-compose -v
docker-compose version 1.9.0, build 2585387
```

After run docker-compose restart manually 
```
/usr/local/bin/docker-compose -f /home/dev/projects/project/docker-compose.yml restart
```
services is run correctly 

 

Any ideas?

**Comment by thaJeztah** [comment]
Can you add the full output of `docker version` and `docker info`? Also, do the daemon logs show why the containers didn't restart?

**Comment by bscheshirwork** [comment]
$ docker info
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 46
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55 GiB
Name: dev-Aspire-V3-772
ID: 2LVF:BUKN:WLE3:CPC7:VG3B:BFCE:2T5I:SDB3:ZG56:VJEO:Z4PT:3VVN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: bscheshir
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

$ docker -v
Docker version 17.03.0-ce, build 60ccb22

**Comment by bscheshirwork** [comment]
$ docker info
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 46
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55 GiB
Name: dev-Aspire-V3-772
ID: 2LVF:BUKN:WLE3:CPC7:VG3B:BFCE:2T5I:SDB3:ZG56:VJEO:Z4PT:3VVN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: bscheshir
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by bscheshirwork** [comment]
After rebut - 1 service just off
So... I got a errors in log: 
```
мар 13 16:28:56 dev-Aspire-V3-772 dockerd[1291]: time="2017-03-13T16:28:56.262005237+03:00" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/home/dev/projects/yii2/mysql-proxy/log.lua\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/c905edb53c9d0d341ba8be9c1513095005bb3a3f5a9d01510fdf4a3996f7e0e5\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/c905edb53c9d0d341ba8be9c1513095005bb3a3f5a9d01510fdf4a3996f7e0e5/opt/log.lua\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n" id=d28cf82770916b354ce115a9ebfa277aaa9a56591b94bd2bd551e5c89bc16d4d

мар 13 16:28:56 dev-Aspire-V3-772 dockerd[1291]: time="2017-03-13T16:28:56.262820834+03:00" level=error msg="Create container failed with error: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/home/dev/projects/yii2/mysql-proxy/log.lua\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/c905edb53c9d0d341ba8be9c1513095005bb3a3f5a9d01510fdf4a3996f7e0e5\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/c905edb53c9d0d341ba8be9c1513095005bb3a3f5a9d01510fdf4a3996f7e0e5/opt/log.lua\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"

d28cf82770916b354ce115a9ebfa277aaa9a56591b94bd2bd551e5c89bc16d4d: oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/home/dev/projects/yii2/mysql-proxy/log.lua\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/c905edb53c9d0d341ba8be9c1513095005bb3a3f5a9d01510fdf4a3996f7e0e5\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/c905edb53c9d0d341ba8be9c1513095005bb3a3f5a9d01510fdf4a3996f7e0e5/opt/log.lua\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"
``` 
But after "docker-compose restart" / "docker restart name1 name2 name3 name4" all 4 is up

Next - testing without mysql-proxy services...

**Comment by thaJeztah** [comment]
The reason it's failing to start is because you're trying to bind-mount a _file_ into the container; when using bind-mounts, docker will check if the file (or directory) you want to bind-mount from the host exists on the server the daemon runs on. If the file/directory doesn't exist, docker automatically creates a _directory_ with the given name (as it doesn't know if it needs to be a file or a directory), and bind-mounts that into the container.

However, if there's an existing file in the container at the path it's trying to mount, this will fail, because you cannot mount a directory on top of a file.

In your case;

```
- ../mysql-proxy/log.lua:/opt/log.lua
```

If the file ` ../mysql-proxy/log.lua` does not exist on the daemon host, docker creates a _directory_ named ` ../mysql-proxy/log.lua`, then bind-mounts that inside the container at `/opt/log.lua` (but there's a file already inside the container), thus produces an eror "not a directory" (because the target is not a directory, but a file).

Bind-mounting single files is known to be problematic, and is generally discouraged (there's some warnings in the documentation about this as well)

To work around this, consider bind-mounting a _directory_ instead of individual files. For example;

```
- ../mysql-proxy:/opt/mysql-proxy/
```

 And make your application look inside that directory for the configuration files.

I'm closing this issue, because this is not a  bug, but feel free to continue the conversation

**Comment by bscheshirwork** [comment]
only 3 `warning`, all other `info` level
```
мар 13 17:01:00 dev-Aspire-V3-772 dockerd[1293]: time="2017-03-13T17:01:00.902284205+03:00" level=warning msg="Your kernel does not support swap memory limit"
мар 13 17:01:00 dev-Aspire-V3-772 dockerd[1293]: time="2017-03-13T17:01:00.902326178+03:00" level=warning msg="Your kernel does not support cgroup rt period"
мар 13 17:01:00 dev-Aspire-V3-772 dockerd[1293]: time="2017-03-13T17:01:00.902335600+03:00" level=warning msg="Your kernel does not support cgroup rt runtime"
```
So. I think its another mount volume error
`$ docker-compose logs` not consist any string from the nginx service
After restart ONLY ...nginx_run_1 (
```   
volumes_from:
      - php
```
)
the php send to output 
```
php_1    | [13-Mar-2017 17:17:18] WARNING: [pool www] child 7 said into stderr: "ERROR: Unable to open primary script: /var/www/html/frontend/web/index.php (No such file or directory)"
```
and http output of nginx is "No input file specified."

i.e. php volume mount broken

**Comment by bscheshirwork** [comment]
> I'm closing this issue, because this is not a bug, but feel free to continue the conversation
problem not resolved
see (2) configuration (first msg)

**Comment by bscheshirwork** [comment]
Is an wrong chmod/chown possible when mounting a volume (after system reload) as a superuser (before login as user)?

**Comment by thaJeztah** [comment]
The warnings can be ignored, and are not related to this issue; those warnings show that certain features are not supported by your kernel;

```
мар 13 17:01:00 dev-Aspire-V3-772 dockerd[1293]: time="2017-03-13T17:01:00.902284205+03:00" level=warning msg="Your kernel does not support swap memory limit"
мар 13 17:01:00 dev-Aspire-V3-772 dockerd[1293]: time="2017-03-13T17:01:00.902326178+03:00" level=warning msg="Your kernel does not support cgroup rt period"
мар 13 17:01:00 dev-Aspire-V3-772 dockerd[1293]: time="2017-03-13T17:01:00.902335600+03:00" level=warning msg="Your kernel does not support cgroup rt runtime"
```


All that `volumes_from:` does, is to _copy_ the volume-definition from the `php` service. Using `volumes_from` in your situation is exactly the same as writing your nginx service like this;

```yaml
  nginx:
    image: nginx:1.11.10-alpine
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - php
    volumes:
      - ./php-code:/var/www/html #php-code
      - ./nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ./nginx-logs:/var/log/nginx #nginx-logs
```

Is docker running in a VM, and are is the `php-code` directory on the same machine? If it's running in a VM, and you're using (e.g.) VirtualBox guest additions to share the host's filesystem with the VM, this problem could be due to the share between your host and the VM not yet being "up".

Also keep in mind that once you ran `docker-compose up`, docker compose is no longer running, so all you need to check is if the container's are configured correctly. For example, check `docker inspect <container>` to see if the volumes are correctly set in the container's definition.

The same applies to the `depends_on`; `depends_on` is only used during `docker-compose up`. When restarting docker (or the machine that docker is running on), this is not taken into account, so you won't know in which order the containers are started. For that reason, it's always important to make sure your services are resilient against failures of dependent services (for example, by using a retry-loop to wait for the other service to be "up").

**Comment by bscheshirwork** [comment]
> Using volumes_from in your situation is exactly the same as writing your nginx service like this;
yes, 
I write this dependencies for reason
directly same/match path into nginx / into php

>Is docker running in a VM, and are is the php-code directory on the same machine? 
Docker run without VM

**Comment by thaJeztah** [comment]
When it's giving the ` Unable to open primary script` error; have you tried to `docker exec` into the container to see if the file is actually missing? Are other files there?

If you inspect the `php` container before, and after restarting the container, is anything different in the output?

**Comment by bscheshirwork** [comment]
>have you tried to docker exec into the container to see if the file is actually missing?
Hmmm... Interesting idea. 

After restat nginx first (only nginx) - nginx have access to volume, static files (for exp 404.html) is worc correctly.
After restart nginx and php - both is work correctly, static and php

p.s.:  So... You sure 
```
  nginx:
    volumes:
      - ./php-code:/var/www/html #php-code
  php:
    volumes:
      - ./php-code:/var/www/html #php-code
```
is work same to
```
  nginx:
    volumes_from:
      - php
  php:
    volumes:
      - ./php-code:/var/www/html #php-code

```
into docker volume mechanism?

I see into `docker inspect` output 
have 2 place for this:
```
        "HostConfig": {
            "Binds": [
                "/home/dev/projects/yii2/nginx-conf:/etc/nginx/conf.d:rw",
                "/home/dev/projects/yii2/nginx-logs:/var/log/nginx:rw"
            ],
...
            "VolumesFrom": [
                "0e1d8e3937ad7e595c97a99a796bba743422a3c0976130530f5f1e885d98aa47:rw"
            ],
...
```
