### ISSUE TITLE
Swagger API: NetworkConfig is not correct

### ISSUE THREAD

**Issue by johnflavin** [docker/docker#31822]
(Note that the title is a joke, referring to [swagger.yaml line 818](https://github.com/docker/docker/blob/master/api/swagger.yaml#L818): `"TODO check is correct"`.)

In the swagger spec for inspecting a container (`operationId: "ContainerInspect"`), one of the object properties is `NetworkSettings`. For that value, the spec refers to the object definition at `#/definitions/NetworkConfig`. However, that definition is not complete.

Here is the incomplete `NetworkConfig` swagger spec:
```yaml
NetworkConfig:
  description: "TODO: check is correct"
  type: "object"
  properties:
    Bridge:
      type: "string"
    Gateway:
      type: "string"
    Address:
      type: "string"
    IPPrefixLen:
      type: "integer"
    MacAddress:
      type: "string"
    PortMapping:
      type: "string"
    Ports:
      type: "array"
      items:
        $ref: "#/definitions/Port"
```

The spec for inspecting a container gives an example `NetworkSettings` with many more properties than are defined in the `NetworkConfig` spec that supposedly defines it:
```yaml
NetworkSettings:
  Bridge: ""
  SandboxID: ""
  HairpinMode: false
  LinkLocalIPv6Address: ""
  LinkLocalIPv6PrefixLen: 0
  SandboxKey: ""
  SecondaryIPAddresses: null
  SecondaryIPv6Addresses: null
  EndpointID: ""
  Gateway: ""
  GlobalIPv6Address: ""
  GlobalIPv6PrefixLen: 0
  IPAddress: ""
  IPPrefixLen: 0
  IPv6Gateway: ""
  MacAddress: ""
  Networks:
    bridge:
      NetworkID: "7ea29fc1412292a2d7bba362f9253545fecdfa8ce9a6e37dd10ba8bee7129812"
      EndpointID: "7587b82f0dada3656fda26588aee72630c6fab1536d36e394b2bfbcf898c971d"
      Gateway: "172.17.0.1"
      IPAddress: "172.17.0.2"
      IPPrefixLen: 16
      IPv6Gateway: ""
      GlobalIPv6Address: ""
      GlobalIPv6PrefixLen: 0
      MacAddress: "02:42:ac:12:00:02"
```

The properties in the example should be added to the `NetworkConfig` definition. This should be mostly straightforward, with a couple exceptions. The `Networks` property will follow the same spec from `ContainerSummary`:
```yaml
Networks:
  type: "object"
  additionalProperties:
    $ref: "#/definitions/EndpointSettings"
```

I'm not sure about the two `null` properties from the example: `SecondaryIPAddresses` and `SecondaryIPv6Addresses`. Are they lists of strings? Some object?
