### ISSUE TITLE
v3 compose volumes not mounting via stack deploy

### ISSUE THREAD

**Issue by monowai** [docker/docker#32217]
I was trying to mount a provisioned IOPS EBS on a machine acting as a Swarm master. I followed the instructions on this issue https://github.com/docker/docker/issues/30441 and used a definition such as:

```
version: "3"
services:
    postgres:
    image: postgres:9.5
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - uat
    deploy:
      placement:
        constraints:
          - engine.labels.com.myco.postgres.master==yes

volumes:
  postgres:
    driver_opts:
      o: bind
      type: none
      device: /data/database/postgres/bp
```

Works as expected when I run `docker-compose up -d` - postgres writes to the mounted volume.
Doesn't work when started via `docker stack deploy ...`  - the volume data is written to `/var/lib/docker/volumes/{net}-{volume}/_data` within the host.

I'm running `version 17.03.0-ce, build 60ccb22`. I'm guessing it's not yet supported? Cheers

**Comment by AkihiroSuda** [comment]
> volumes

`:` missing?

**Comment by cpuguy83** [comment]
Are you seeing an error?
Also, why are you doing this? You can just specify
```
volumes:
    - /data/database/postgres/bp:/var/lib/postgresql/data
```

**Comment by monowai** [comment]
The question is that the config works as expected when using `docker-compose`, but fails when using `docker stack deploy`.  Variations in behaviour should be documented, otherwise one might consider it a bug.

To answer the previous question, I want my data persisted between restarts when deploying via swarm - yes I'm aware of tying the service to the instance. The volumes suggestion above does not write to the mounted volume - at least not when using `docker stack deploy`

**Comment by cpuguy83** [comment]
This is a bug in 17.03 where driver options are not applied unless "driver" is set.

17.03:
https://github.com/docker/docker/blob/v17.03.0-ce/cli/compose/convert/volume.go#L85

17.04:
https://github.com/docker/docker/blob/v17.04.0-ce-rc1/cli/compose/convert/volume.go#L77

So if update the volume spec to look like this, it will work:
```yaml
volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/database/postgres/bp
```
