### ISSUE TITLE
Can't pull on own server (no space left)

### ISSUE THREAD

**Issue by erperejildo** [docker/docker#32343]
I'm running a pipeline on Gitlab every time I do a push to master. This pipeline is quite simple:
```
image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_IMG: myUSER/myAPP
before_script:
  - docker login --username="myUSER" --password="myPASS"
stages:
  - Pull
Pull:
  stage: Pull
  tags:
    - deploy # private runner on server
  script:
    - docker pull $DOCKER_IMG
```

This pull is a 1-2GB image from Docker Hub and it's connected with a private runner so this detects I want to pull on my server (no ssh connection required).

The issue that I get when I run this is that I don't have any more space on my server.
This is the available space that I've got:
```
recipic@recipic:/var/lib/docker$ sudo df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G  6.4G   13G  34% /
```

Here you can see further info:
https://forum.gitlab.com/t/pull-from-my-server/7264

I'm also talking with DigitalOcean staff and they told me that this is quite weird. Also previous link is on Gitlab forum to discard problems from them as well.

Am I doing something wrong?  :S
