### ISSUE TITLE
Docker for Mac can't use loaded environment variable from file

### ISSUE THREAD

**Issue by boshido** [docker/docker#32428]
I use shared .env from my application and the key that contains the database name is not the same as mysql database name environment variable

I use 'env_file: .env.local' for loading my application environment variable instead and reassign
to required mysql environment variable key. This technical works fine when I run docker-compose on linux but It is not working when I run in my Mac

Docker for mac version 
 - 17.03.1-ce-mac5 (16048)

Docker-compose version 
 - 1.12.0, build b31ff33

My shared .env file
```
DB_NAME=this_is_db_name
DB_PASS=
DB_USER=root
DB_HOST=127.0.0.1
DB_DIALECT=mysql
DB_PORT=3306
```

My docker-compose
```
version: '3.2'
services:
  mysql:
    restart: always
    image: mysql:5.6
    hostname: mysql
    volumes:
      - .tmp/mysql:/var/lib/mysql
    env_file: .env.local
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
```

**Steps to reproduce the issue:**
1. docker-compose -f docker-compose.yml up

**Describe the results you received:**
Mysql does not create the database because docker-compose did not assign DB_NAME value to MYSQL_DATABASE and the result when I type command 'env' the environment is loaded fine from file except MYSQL_DATABASE
 
Result from 'env'
```
DB_HOST=127.0.0.1
HOSTNAME=mysql
DB_NAME=this_is_db_name
DB_PASS=
TERM=xterm
MYSQL_VERSION=5.6.35-1debian8
DB_PORT=3306
MYSQL_DATABASE=
DB_DIALECT=mysql
```
**Describe the results you expected:**
Result from 'env'
```
MYSQL_DATABASE=this_is_db_name
```

**Comment by thaJeztah** [comment]
This is expected. Using this `docker-compose.yml`;

```yaml
version: '3.2'
services:
  mysql:
    image: nginx:alpine
    env_file: .env.local
    environment:
      MYSQL_DATABASE: ${DB_NAME}
```

And `.env.local` file;

```
cat .env.local
MYSQL_DATABASE=from_file
```

You'll see that it warns that the environment variable wasn't set:

```
docker-compose up -d 
WARNING: The DB_NAME variable is not set. Defaulting to a blank string.
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "repro32428_default" with the default driver
Creating repro32428_mysql_1
```

And the container's ENV-var is empty;

```
docker inspect --format '{{json .Config.Env }}' repro32428_mysql_1

[
  "MYSQL_DATABASE=",
  "no_proxy=*.local, 169.254/16",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "NGINX_VERSION=1.11.9"
]
```

Now export the environment variable, and do it again. The warning is not printed;

```
export DB_NAME=from_environment

docker-compose up -d

WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "repro32428_default" with the default driver
Creating repro32428_mysql_1
```

And the container has the env-var set from the environment;

```
docker inspect --format '{{json .Config.Env }}' repro32428_mysql_1

[
  "MYSQL_DATABASE=from_environment",
  "no_proxy=*.local, 169.254/16",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "NGINX_VERSION=1.11.9"
]
```


If, instead, you want to use the value from the `.env.local` file, remove the `environment:` from your `docker-compose.yml`;

```yaml
version: '3.2'
services:
  mysql:
    image: nginx:alpine
    env_file: .env.local
```

```
docker inspect --format '{{json .Config.Env }}' repro32428_mysql_1 | jq .
[
  "MYSQL_DATABASE=from_file",
  "no_proxy=*.local, 169.254/16",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "NGINX_VERSION=1.11.9"
]
```
