### ISSUE TITLE
How to use mount instead of volume in docker compose

### ISSUE THREAD

**Issue by jonathan-kosgei** [docker/docker#32478]
Hi,
I'm trying to do something like 

```
version: '3'

services:
  mongo:
    image: mongo:3.4.3
    command: bash -c "mongod --replSet zipgo-rs0 --journal"
    ports:
      - "27017:27017"
    volumes:
      mount:
        type: volume
        src: "{{.Service.Name}}-{{.Task.Slot}}"
        dst: /data
        volume-driver: ebs
    deploy:
      mode: global
```

However I get an error saying mongo.volumes has to be a list. 

Where do I place mount in a compose file?
