### ISSUE TITLE
Docker in IPv6 only - network problem

### ISSUE THREAD

**Issue by valentin2105** [docker/docker#32675]
**Description**

I'm trying to deploy Docker containers using Docker-Compose in a IPv6 Only network.
I got some problem and timeout with the Docker embedded DNS (127.0.0.11) who is don't able to request IPv6 DNS servers.  

**Steps to reproduce the issue:**
1. Create a IPv6 Only machine
2. Launch containers stack with docker-compose and IPv6 Enabled
3. Ping6 google.com from inside a container. 

example compose file : 

```
version: '2.1'

services:
    wp_front:
      image: nginx:latest
      restart: always
      links:
        - wp_fpm
      networks:
        v6:
          ipv6_address: <v6-ip>
    wp_fpm:
      image: php-fpm:7.0.12
      restart: always
      links:
        - wp_db:mysql

      networks:
        v6:
          ipv6_address: <v6-ip>
    wp_db:
      image: mariadb:latest
      restart: always
      networks:
        v6:
          ipv6_address: <v6-ip>
networks:
  v6:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: <v6-range>/112
```

**Describe the results you received:**
The ping with dns resolution timeout and if I disable DNS query (ping -n), got no issue. 

Here is the resolv.conf on the containers :
```
nameserver 127.0.0.11 ## This line give problems. 
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
```

**Describe the results you expected:**
Be able to use Docker container in a IPv6 only system. 
Maybe disable Docker v4 DNS while using IPv6 (or give the capability to do this).

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Xen VMs in full IPv6 with DNS64 resolution.
