### ISSUE TITLE
Is there any way to use hostname command in the container?

### ISSUE THREAD

**Issue by quantonganh** [docker/docker#8902]
The situation: I would like to use docker for testing Salt states which include a `hostname` command:

```
hostname:
  file:
    - managed
    - template: jinja
    - name: /etc/hostname
    - user: root
    - group: root
    - mode: 444
    - source: salt://hostname/hostname.jinja2
  cmd:
    - run
    - name: hostname `cat /etc/hostname`
    - watch:
      - file: hostname
```

Calling it via `docker` I got something like this:

```
----------
          ID: hostname
    Function: file.managed
        Name: /etc/hostname
      Result: True
     Comment: File /etc/hostname updated
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1 +1 @@
                  -4be067f0e54e
                  +integration-docker

              mode:
                  0444
----------
          ID: hostname
    Function: cmd.run
        Name: hostname `cat /etc/hostname`
      Result: False
     Comment: Command "hostname `cat /etc/hostname`" run
     Changes:
              ----------
              pid:
                  159
              retcode:
                  1
              stderr:
                  hostname: you must be root to change the host name
              stdout:
```

As you can see, `/etc/hostname` can be updated but I cannot use `hostname` command to change it accordingly. Sure, it's running as `root`. You can try it manually:

```
$ docker exec -it 4be067f0e54e bash
root@4be067f0e54e:/# id
uid=0(root) gid=0(root) groups=0(root)
root@4be067f0e54e:/# hostname blah
hostname: you must be root to change the host name
```

Could you please tell me why? As a temporary, I have to create a "fake" `hostname` command to make my states return "Succeeded".
